### PR TITLE
Add a mechanism for per-test configs

### PR DESCRIPTION
**Pull request by richvdh**
It's useful to be able to tweak the homeserver config to be used for each test. This PR adds a mechanism to do so.

### CODE REVIEW

**Comment by hawkowl** [comment]
I also added a mechanism in the backoff PR -- https://github.com/matrix-org/synapse/pull/5556/files#diff-9161fd33123787f063a0f71aad7c3272R382 -- obviously we should pick one of them :)

I'm not in love with attaching objects to functions, personally, so IDK.

**Comment by richvdh** [comment]
Well, obviously we should land this one, because it's not tied up into a larger, more contentious, PR ;)

Building a config, configuring the HS, and then reconfiguring the HS feels like a bit of a funny way of doing things to me.

I agree that attaching things to functions isn't super-lovely either, though in practice (https://github.com/matrix-org/synapse/pull/5660/files#diff-afaefb43d2d504f504fb4d4a8840e70eR191) it felt quite usable.

Perhaps a casting vote? @erikjohnston ?

**Comment by hawkowl** [comment]
@richvdh a side effect of doing my method in our tests is that we can start potentially exercising in-production-SIGHUP reconfiguration changes of more than just our logs, which might be valuable?

but yes lets make @erikjohnston make all the big decisions for us, so we can blame him :D

**Comment by richvdh** [comment]
> we can start potentially exercising in-production-SIGHUP reconfiguration changes of more than just our logs, which might be valuable?

it would indeed, though I'm not convinced I'd want to end up doing that process for lots of unit tests.

**Comment by erikjohnston** [comment]
I'm not a fan of attaching attributes to functions, what about using a decorator?

```python
@override_config(enable_registration=False, ...)
def test_foo(self):
   ...
```

**Comment by erikjohnston** [comment]
I also think that relying on `reload_config` is a bit annoying if you want to change config for stuff that can't be reloaded. So I vote decorators, then maybe this PR.

**Comment by richvdh** [comment]
ok, I have implemented erik's plan.

**Pull request merged**
