### PR TITLE
Use cryptographically secure RNG.

### PR DESCRIPTION
**Pull request by rrigby**
Using the current PRNG there's the possibility of someone untwisting it to get the seed and being able to calculate resourceids. Using SystemRandom() should stop any chance of this.

### CODE REVIEW

**Comment by richvdh** [comment]
can you check the failures on travis please

**Comment by richvdh** [comment]
Ok, thank you.

I have concerns about making this change in a utility function which is used widely across the application. There are two reasons for this: (1) since it's in a hot path, any performance overhead could end up being significant; (2) since SystemRandom is implemented as a read from `/dev/urandom`, this could block, which would end up freezing the *whole* application.

I therefore wonder if a better approach would be to define a separate `secure_random_string` function, which could return a Deferred and delegate its activity to a separate thread, and then modify code which actually needs a secure random to use it.

What do you think?

**Comment by rrigby** [comment]
That sounds good, I'll give it a go on the weekend.

**Comment by Valodim** [comment]
> (2) since SystemRandom is implemented as a read from /dev/urandom, this could block, which would end up freezing the whole application

this is incorrect, /dev/urandom does not block

**Comment by richvdh** [comment]
> this is incorrect, /dev/urandom does not block

At some level, any file i/o operation can block, and /dev/urandom is no exception. I agree that it doesn't block in the same way as /dev/random, and tbh farming out reads to a separate thread may be overkill.

Nevertheless I don't really agree with the principle of using SystemRandom wherever random numbers are required, so I think this PR needs some re-work, and it appears to have stalled, so I am closing it for now. @rrigby: feel free to open a new PR if you get a chance to revisit this.

**Pull request closed without merging**
