### PR TITLE
Remove content repository, obsoleted by media server

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by NegativeMjark** [comment]
There are still clients out there that read from this repository. I think the android client and the angular web client based on the apache logs for matrix.org

**Comment by illicitonion** [comment]
Eww. Sadsies. We should fix that, probably...

**Comment by NegativeMjark** [comment]
Nothing is writing to it, So you can probably get rid of that half of the API

**Comment by illicitonion** [comment]
bleh, as far as I can tell neither the android app nor the angular client use /content on master. How long do we need to support obsolete things?

**Comment by NegativeMjark** [comment]
They shouldn't be writing to it. However there are a number of image events and member events in the older rooms that have ``https://`` URLs for images that point to /media/content. Newer clients ignore those URLs cause they tend to have SSL issues cause of the self-signed certificates used by most HSes.
However some of the older clients still read from those URLs. It should be reasonable to stop serving the old URLs, but it will have an effect on the older clients.

**Pull request closed without merging**
