### PR TITLE
Don't ignore `set_tweak` actions with no explicit `value`.

### PR DESCRIPTION
**Pull request by reivilibre**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by richvdh** [comment]
Are you sure this is the correct interpretation of the spec?

See also: https://github.com/matrix-org/matrix-doc/issues/2643

**Comment by reivilibre** [comment]
The spec is a bit yucky in this regard, but it says that:

* set_tweak without a `value` is a valid action.
* for `highlight` tweaks, `True` is to be assumed if `value` is absent. (see 1.)
* other tweaks (`sound`, plus any other tweaks that clients and push gateways may agree on, as is their permission to do according to spec) don't have a spec-defined value.

Ideally (imo) the spec should have had the guts to fully define this or not made `value` optional at all... Seems like a silly place to introduce needless ambiguity. But it is what it is, and this solution solves the case of `highlight` and at least sets *something* reasonable for other arbitrary tweaks.


1. [highlight](https://matrix.org/docs/spec/client_server/r0.6.1#tweaks)
A boolean representing whether or not this message should be highlighted in the UI. This will normally take the form of presenting the message in a different colour and/or style. The UI might also be adjusted to draw particular attention to the room in which the event occurred. **If a highlight tweak is given with no value, its value is defined to be true.** If no highlight tweak is given at all then the value of highlight is defined to be false.

**Comment by richvdh** [comment]
sorry I'm not entirely following you. Agreed that the spec says `highlight` with no `value` is the same as `highlight` with `value=true`. Are you telling me that synapse does not correctly implement that? (Not that it makes much difference in practice, since the neither of the pushkins care about `highlight`)?

I'm obviously missing something else: my understanding was that synapse passes the `tweaks` dictionary straight through to the push gateway. What is this `tweaks_for_actions` trying to do?

**Comment by reivilibre** [comment]
> sorry I'm not entirely following you. Agreed that the spec says `highlight` with no `value` is the same as `highlight` with `value=true`. Are you telling me that synapse does not correctly implement that? (Not that it makes much difference in practice, since the neither of the pushkins care about `highlight`)?

Yes, a tweak with no value is currently discarded.

> I'm obviously missing something else: my understanding was that synapse passes the `tweaks` dictionary straight through to the push gateway. What is this `tweaks_for_actions` trying to do?

Converts a list of actions e.g. `[{"set_tweak": "a", "value": "AAA"}, {"set_tweak": "b", "value": "BBB"}, "notify"]`
into a tweaks dict e.g. `{"a": "AAA", "b": "BBB"}` which is then passed to Sygnal (and used for #7765).

**Comment by richvdh** [comment]
right, what a mess. thanks for explaining.

**Pull request merged**
