### PR TITLE
Remove incorrect migration file from `state` logical DB

### PR DESCRIPTION
**Pull request by DMRobertson**
The table `ex_outlier_stream` is part of the `main` logical DB; it should not have been created in the `state` logical DB. We remove this migration now as a tidy-up.

Note: we cannot `DROP TABLE IF EXISTS ex_outlier_stream` in a new migration, because some (most) instances of Synapse host both of these logical DBs on the same DB cluster.

### CODE REVIEW

**Comment by DMRobertson** [comment]
Complement failures are known (https://github.com/matrix-org/complement/pull/459 merged, but Synapse not fixed)

**Comment by clokep** [comment]
> Note: we cannot `DROP TABLE IF EXISTS ex_outlier_stream` in a new migration, because some (most) instances of Synapse host both of these logical DBs on the same DB cluster.

Would it make sense to document that it can be dropped manually or something? 🤷 Sounds like potential to break things if it is just an empty table though.

**Comment by DMRobertson** [comment]
> Sounds like potential to break things if it is just an empty table though.

Yeah, I think I'm inclined to leave it be since it should never be written to in the `state` logical DB.

**Review by erikjohnston — APPROVED** [review]

**Comment by DMRobertson** [comment]
Manually merging due to known complement tests that have since been implemented on develop

**Comment by erikjohnston** [comment]
I'm not aware of anyone actually using two separate DBs in the wild, so I don't think we should worry too much about it

**Pull request merged**
