### PR TITLE
Add support for setting the room avatar on /createRoom

### PR DESCRIPTION
**Pull request by turt2live**
Spec: https://github.com/matrix-org/matrix-doc/pull/1326
Sytest: https://github.com/matrix-org/sytest/pull/455

### CODE REVIEW

**Comment by richvdh** [comment]
@matrixbot : ok to test

**Comment by richvdh** [comment]
lgtm, though we should probably not merge it until there is agreement on https://github.com/matrix-org/matrix-doc/pull/1326 ?

**Comment by turt2live** [comment]
This is where the proposal process gets awkward for short circuiting it (which I'm playing with the idea of here, sorry). The current process is gdoc -> approval -> implementation -> spec PR, which implies that in this case the implementation should come first?

I'd rather wait though - seems to be the path of least resistance (and makes it easier to back out the change if for whatever reason the proposal gets declined).

**Comment by turt2live** [comment]
Closing this: Community feedback on https://github.com/matrix-org/matrix-doc/pull/1326 has shown that people would rather the `name` and `topic` be deprecated. Synapse requires no changes at this time to fulfill that.

**Pull request closed without merging**
