### PR TITLE
Add information about the matrix-docker-ansible-deploy playbook

### PR DESCRIPTION
**Pull request by spantaleev**

### CODE REVIEW

**Comment by spantaleev** [comment]
Now that #3378 got merged, I've rebased this to fix a merge conflict and changed the wording a bit.

**Comment by spantaleev** [comment]
I've just added a changelog entry. Hopefully, it's good to merge now.

**Comment by richvdh** [comment]
Hum. There is also the ansible playbook at https://github.com/matrix-org/matrix-ansible-synapse. I'd have thought if we were going to point to an ansible playbook it should be that one, but I have no idea how it is different to yours.

/cc @michaelkaye

**Comment by aaronraimist** [comment]
I'd say it is different in several ways including the readme is not rubbish (https://github.com/matrix-org/matrix-ansible-synapse/issues/5)

In fact `@julian:foad.me.uk` [said earlier today in `#synapse:matrix.org`](https://matrix.to/#/!HsxjoYRFsDtWBgDQPh:matrix.org/$154019418315MJtDc:foad.me.uk)
> Two of you just recommended https://github.com/spantaleev/matrix-docker-ansible-deploy ... I've just read through its docs and it looks 100x better than any of the "Installing Synapse" guides listed on https://matrix.org/docs/guides/
> Really this one IS a guide: it is documented so well, like you really understand what I need to know and you write it clearly. None of the other guides match it.

This playbook also installs a lot more things that real world users are going to want besides just Synapse like Riot, coturn, Postfix, mxisd, etc.

**Comment by aaronraimist** [comment]
It is also just generally maintained, just glancing at https://github.com/matrix-org/matrix-ansible-synapse, it seems to install Synapse v0.28.1

**Comment by richvdh** [comment]
Yup, it seems https://github.com/matrix-org/matrix-ansible-synapse isn't currently being maintained, so thanks!

**Pull request merged**
