### PR TITLE
Implement cancellation support/protection for module callbacks

### PR DESCRIPTION
**Pull request by squahtx**
There's no guarantee that module callbacks will handle cancellation
appropriately. Protect module callbacks with read semantics from
cancellation and avoid swallowing `CancelledError`s that arise.

Other module callbacks, such as the `on_*` callbacks, are presumed to
live on code paths that involve writes and aren't cancellation-friendly.
These module callbacks have been left alone.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by H-Shay** [comment]
> We could probably do with some instructions for developers who want to add new callbacks. Where could they be placed so that they would be noticed?

Perhaps in https://github.com/matrix-org/synapse/blob/develop/docs/modules/writing_a_module.md#registering-a-callback?

**Comment by squahtx** [comment]
> > We could probably do with some instructions for developers who want to add new callbacks. Where could they be placed so that they would be noticed?
> 
> Perhaps in https://github.com/matrix-org/synapse/blob/develop/docs/modules/writing_a_module.md#registering-a-callback?

Hm, that seems to be aimed at module developers, rather than developers extending the module API.

**Comment by babolivier** [comment]
> We could probably do with some instructions for developers who want to add new callbacks. Where could they be placed so that they would be noticed?

Maybe create a new page in the "Development" section of the doc site?

**Comment by squahtx** [comment]
> > We could probably do with some instructions for developers who want to add new callbacks. Where could they be placed so that they would be noticed?
> 
> Maybe create a new page in the "Development" section of the doc site?

We probably do need a guide to extending the module API in the development docs.
Trouble is I would absolutely not read them when adding new callbacks. Is there somewhere in the code I could stick a comment that wouldn't be missed?

**Comment by babolivier** [comment]
> Trouble is I would absolutely not read them when adding new callbacks.

Yeah I assume most people wouldn't... If we made more people aware of a guide we might at least get people to raise stuff from it in reviews though?

> Is there somewhere in the code I could stick a comment that wouldn't be missed?

I don't think so, there isn't really a central place to define new callbacks (the closest I can think of is the module API's `register_...` methods but that doesn't sound like an ideal place for it).

(as an aside, heads up module callbacks aren't part of what we call "the module API" terminology-wise, if you think that's confusing feel free to weigh in on https://github.com/matrix-org/synapse/issues/12186)

**Review by erikjohnston — APPROVED** [review]

**Pull request merged**
