### PR TITLE
Merge account data streams

### PR DESCRIPTION
**Pull request by erikjohnston**
We want to do this so that we can always send out `POSITION` replication notices when a stream's token advances without any data to replicate. This ensures that all workers always rapidly converge on what the current token for a stream is, c.f. 

https://github.com/matrix-org/synapse/blob/b50c008453001aee8dd7dbd6f36ec32039e6ce76/synapse/replication/tcp/resource.py#L199-L206

### CODE REVIEW

**Comment by clokep** [comment]
@erikjohnston Can you describe a bit more what this is actually doing under the hood? I'm unsure what "merging streams" means.

**Comment by erikjohnston** [comment]
> @erikjohnston Can you describe a bit more what this is actually doing under the hood? I'm unsure what "merging streams" means.

Sure! Basically, when we send data over Redis it is separated into different "replication streams" (very similar to sync tokens). Every "row" sent over replication contains the stream name, sending instances, the stream token and the actual data. The stream tokens come from the various ID generators in the storage layer, and instances receiving replication traffic use the stream token from the replication rows to advance the associated ID generators.

Now, for reasons, we have some replication streams that share an underlying ID generator. This is *fine* for current purposes, albeit confusing. The knock on effect of this though is that if we see the stream token advance (on the sending side), without seeing any updates in the stream, then we can't tell if a) we advanced the token but then didn't write an update, or b) we wrote an update to a different stream that shares the same ID generator. 

What I want to be able to do is notify replication when we have advanced the stream token locally but have no update to send. This is to ensure that all instances advance the stream token quickly after its been advanced, even if no update has been written. This is important for #14820.

So the solution is to take the replication streams that share a single ID generator and merge them into a single stream, which includes all the updates from the old streams. This results in all the stream tokens being properly independent.

**Comment by clokep** [comment]
> So the solution is to take the replication streams that share a single ID generator and merge them into a single stream, which includes all the updates from the old streams. This results in all the stream tokens being properly independent.

Where "merging" means having them send the same "stream name"?

Thanks for tying it to #14820, I didn't realize there was any connection between these!

Would this be a step backwards for #12461?

**Comment by erikjohnston** [comment]
> Where "merging" means having them send the same "stream name"?

Yes!

> Would this be a step backwards for #12461?

Not really, sort of, it just means that we wouldn't be able to split e.g. the tag and account data into different redis channels as they would be in one stream. However, there are still plenty of independent streams

**Pull request merged**
