### PR TITLE
Don't recommend :8448 to people on public_baseurl

### PR DESCRIPTION
**Pull request by turt2live**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#changelog)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off) (N/A)

### CODE REVIEW

**Comment by aaronraimist** [comment]
Also here: 
https://github.com/matrix-org/synapse/blob/d731b75c7bcada708f1acbb83e2521da6a7d97a9/debian/homeserver.yaml#L79

I guess it's not in the docker config?

**Comment by turt2live** [comment]
That file doesn't exist on develop, so I assume it is being auto-generated now.

**Comment by richvdh** [comment]
looks plausible, but assumes people have somehow forwarded port 443 to synapse. Was the existing config causing confusion?

**Comment by richvdh** [comment]
[also, once we require people to have proper certs on port 8448, does the problem go away?]

**Comment by turt2live** [comment]
> [also, once we require people to have proper certs on port 8448, does the problem go away?]

Probably, assuming people have client listeners.

**Pull request merged**
