### PR TITLE
Pull out bits of StateStore to a mixin

### PR DESCRIPTION
**Pull request by richvdh**
... so that we don't need to secretly gut-wrench it for use in the slaved
stores. I haven't done the other stores yet, but we should. I'm tired of
the workers breaking every time we tweak the stores because I forgot to
gut-wrench the right method.

~(includes #2658)~

fixes https://github.com/matrix-org/synapse/issues/2655.

### CODE REVIEW

**Comment by erikjohnston** [comment]
Do we have an end goal in how we want this to look?

**Comment by richvdh** [comment]
My end goal would be "no more gut-wrenching of private fields of Stores, *especially* via the `__dict__` hack"

More concretely, I think we ought to factor out all the bits of Stores which are used by the SlavedEventStore so that they can be used without gut-wrenching. There's quite a lot of it though so I'd rather do it gradually.

**Comment by erikjohnston** [comment]
Right, I guess I was more wondering what the end goal from an architecture perspective was. Will we get rid of the slave stores entirely and just use the Read Stores? Can we separate out the readers and writers entirely, e.g. so that readers can't accidentally write? Are we aiming to make the monolith and workers share more of the code paths? etc.

I'm not saying we need an answer to all that, but an idea where this is heading would be useful I think.

**Comment by richvdh** [comment]
It sounds like you've done a whole lot more thinking about this than I have. Honestly I just wanted to get rid of the code that most offended me and took what looked like the shortest path to get there.

To answer your questions:

> Will we get rid of the slave stores entirely and just use the Read Stores? 

I'm not sure. Perhaps the slave stores will still have a place, to do the management of some of the replication handling. But that feels like a question that will become clearer once we move some of the other gut-wrenching out of the slave stores.

> Can we separate out the readers and writers entirely, e.g. so that readers can't accidentally write?

I'm not quite sure what you mean. Something like taking all of the `simple_insert` etc out of SQLBaseStore into a WritableSQLBaseStore and having the writers inherit from that? Sounds like a nice thing to do... one day.

> Are we aiming to make the monolith and workers share more of the code paths?

Deduplicating code is pretty much always good. What do you have in mind?

> etc.
...

**Comment by erikjohnston** [comment]
Ok, fair enough.

**Pull request merged**
