### PR TITLE
Use v1 endpoints for appservices

### LINKED ISSUE #3780: Call appservices with /_matrix/app/v1
As per https://github.com/matrix-org/matrix-doc/pull/1629

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #3780 

This PR updates the prefix of all appservice endpoints to v1 to be inline with the AS spec. This change however is **extremely breaking** as currently all matrix-org bridges rely on the old behaviour. Comments welcome on how we could support both (not as simple as checking for 404s, as that's a valid response for some of these endpoints).

### CODE REVIEW

**Comment by richvdh** [comment]
@Half-Shot have you looked at what's wrong with the CI?

**Comment by Half-Shot** [comment]
Looking into it now.

**Comment by Half-Shot** [comment]
>How about updating the AS config file to include the version of the AS API the AS supports?

We could do, although since the registration file format is also part of the spec we would also need to spec that.

**Comment by Half-Shot** [comment]
With much sadness, I present https://github.com/matrix-org/matrix-doc/pull/2379

**Comment by richvdh** [comment]
@Half-Shot are you still interested in working on this? what's the situation?

**Comment by Half-Shot** [comment]
Yes, need to figure out what I'm doing with https://github.com/matrix-org/matrix-doc/pull/2379

**Comment by erikjohnston** [comment]
I'm going to close this as it appears blocked on the MSC

**Pull request closed without merging**
