### PR TITLE
Add base pushrule to notify for jitsi conferences

### PR DESCRIPTION
**Pull request by dbkr**
This could be customised to trigger a different kind of notification in the future, but for now it's a normal non-highlight one.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
* <del>[ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)</del>
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Review by anoadragon453 — COMMENTED** [review]
We had a chat about this PR in #synapse-dev and whether it was OK to put "jitsi" related stuff into the spec. It's a little wibbly, but as jitsi widgets and such were conceived pre-Matrix 1.0 (the goal of which was to update the spec to reflect reality, and then tweak for the better), we're happy to allow this change in.

There was also some discussion about client support for this change. For now clients will need to requery their push rules in order for this update to apply - it won't be actively pushed to clients, they must request the most up-to-date push rules again (or re-login). It's worth noting that Element does this on startup.

@dbkr I noticed that there's a change requested on the linked MSC. Did you want to fix that before we continue here? And what's your timeline for this PR?

**Comment by clokep** [comment]
@dbkr I think this is waiting for feedback from you?

**Comment by dbkr** [comment]
Have also updated the MSC so that the rule ID implemented here is the unstable identifier

**Review by anoadragon453 — APPROVED** [review]
Nobody seemed to contend merging this in its current state according to a [conversation in #synapse-dev](https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$UVRtCTK-mxMU9Mom5eb7NWzDNxLCWgO48u4t7clApzI?via=matrix.org&via=jboi.nl&via=amorgan.xyz).

From the MSC it seems that only the ID may change at some point, which should not block this PR.

Note that once this is merged, clients will need to update their push rules (Element Web does this on startup, but this is not standardised). The surefire way to do so is to clear your client's cache, or relogin.

If the push rule's ID is modified later, this will not affect any user-visibile functionality, and clients will receive the updated ID on another push rule update.

**Pull request merged**
