### PR TITLE
Use TLSv1.x rather than SSLv2/3

### PR DESCRIPTION
**Pull request by bashrc**
Signed-off-by: Bob Mottram <bob@freedombone.net>

### CODE REVIEW

**Comment by ara4n** [comment]
lgtm - thanks. can you re-target the PR to the develop branch? otherwise i'll manually apply it there.

**Comment by bashrc** [comment]
Another possibility might be ssl.PROTOCOL_TLSv1_2

I also tried allowing all protocols and then disabling SSL 2 and 3, but that didn't work for me.

**Comment by kroeckx** [comment]
This looks completely wrong. You're turning it from supporting all version to only TLS v1.0. The current code is correct.

**Comment by bashrc** [comment]
SSL 2 and 3 are not secure.

**Comment by kroeckx** [comment]
PROTOCOL_SSLv23 does not mean SSLv2 and SSLv3. It means all supported versions, and take the highest supported by both sides, which should give you TLS 1.2 in most cases now. On the other hand PROTOCOL_TLSv1 only supports TLS 1.0, which is not what you want, and is also insecure. You're turning the correct code into an insecure one.

If you want to disable SSLv2 and SSLv3 support, there are options to do that, but it's not by changing the version method.

**Comment by feld** [comment]
OpenSSL API is confusing and bad, but this should not be changed to anything except perhaps **PROTOCOL_TLS**

https://docs.python.org/2/library/ssl.html#ssl.PROTOCOL_SSLv23

**Comment by kroeckx** [comment]
Because the name was so confusing we have renamed it in OpenSSL and deprecated the SSLv23 one, and so python has done the same. I have also deprecated all those version specific functions. I also improved the documentation in OpenSSL, and I at least hope that it's clear now: https://www.openssl.org/docs/manmaster/man3/SSL_CTX_new.html

**Comment by ara4n** [comment]
sounds like the current behaviour is correct then (modulo using the deprecated constant). What is the correct new term we should be using to avoid confusion recurring? PROTOCOL_TLS?

**Comment by kroeckx** [comment]
Yes.

**Comment by ara4n** [comment]
i've ported this into a new PR with the right constant. thanks all for clarifying.

**Pull request closed without merging**
