### PR TITLE
Add missing event type at Docker conf template

### PR DESCRIPTION
**Pull request by landergate**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by richvdh** [comment]
why is this required? afaik this file is unused except for a one-off migration step: https://github.com/matrix-org/synapse/tree/master/docker#legacy-dynamic-configuration-file-support.

**Comment by landergate** [comment]
@richvdh 

I thought it was used on config initialization using `synapse generate`?
[contrib/docker/README.md](https://github.com/matrix-org/synapse/blob/c3772a71cbf35a4af229494d7fc0f0c809671b89/contrib/docker/README.md)

Following above recommendations, I was planning to generate a fresh static config, where I found a difference within `room_invite_state_types`.

**Comment by richvdh** [comment]
hrm sorry, you're right.

In that case I think the right solution is to remove `room_invite_state_types` altogether, so that synapse uses its defaults.

**Comment by landergate** [comment]
ya makes sense :)

**Comment by landergate** [comment]
@richvdh you were right, that template is not used at all

wanted to see what env variables are available, was a bit disoriented by [docker/conf/homeserver.yaml](https://github.com/matrix-org/synapse/blob/c7b48bd42deb4b8c320c6c1b4006e689a9eefe14/docker/conf/homeserver.yaml), while actual creation happens by [docker/start.py](https://github.com/matrix-org/synapse/blob/3be2abd0a9a089a147b23c6d58fc26dde63faa27/docker/start.py) that don't use templates and copy default config instead

**Pull request closed without merging**
