### PR TITLE
Fix running complement.sh script.

### LINKED ISSUE #11362: scripts-dev/complement.sh broke after 13f084e
### Description

It seems like  13f084e broke the complement.sh script included here, it doesn't find any tests to run anymore:

```
Successfully built 41beaabb3d44
Successfully tagged complement-synapse:latest
no Go files in /home/bubu/projects/oss/synapse/complement-master
```

When manually reverting the changes to that file it works again (the actual tests fail somewhere down the line, but that another matter).

### Steps to reproduce

- run `./scripts-dev/complement.sh` from an up-to-date synapse checkout

### PR DESCRIPTION
**Pull request by clokep**
By reverting changes from #11166 in this script. Specifically commit 13f084eb58c379b2fc073680818d5931e94626f4.

Fixes #11362

### CODE REVIEW

**Comment by clokep** [comment]
I opted to fully revert the changes to this script since there's a variety of ways to run this script and that made me more confident.

I debated about removing `msc2716` to also handle #11363 here, but opted not to. Will wait to see if @MadLittleMods has thoughts first.

**Review by DMRobertson — COMMENTED** [review]
Guessing this was #11166?

**Comment by clokep** [comment]
> Guessing this was #11166?

Yes, see the description.

**Review by DMRobertson — APPROVED** [review]
I'd like to understand what went wrong here, but let's get it back to a known-good state for now.

**Comment by clokep** [comment]
> I'd like to understand what went wrong here, but let's get it back to a known-good state for now.

That was my thought process, yes!

**Pull request merged**
