### PR TITLE
Don't try to run tox from setup.py

### PR DESCRIPTION
**Pull request by richvdh**
Using tox to run the tests is a bad idea, as per the comments.

### CODE REVIEW

**Comment by erikjohnston** [comment]
LGTM, though this is a mjark thing.

**Comment by NegativeMjark** [comment]
Please make running ``setup.py test`` fail in a helpful fashion rather than:

```
/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.18.5-rc2' to '0.18.5rc2'
  normalized_version,
running test
Searching for pyasn1
Reading https://pypi.python.org/simple/pyasn1/
Best match: pyasn1 0.1.9
Downloading https://pypi.python.org/packages/c3/ea/03328a42adfc16a1babbe334ad969f6e27862bcaff9576444d423d2c9257/pyasn1-0.1.9-py2.7.egg#md5=08eef0e822233609f6cad55b419ae00c
Processing pyasn1-0.1.9-py2.7.egg
Moving pyasn1-0.1.9-py2.7.egg to /home/testmarkjh/synapse/.eggs

Installed /home/testmarkjh/synapse/.eggs/pyasn1-0.1.9-py2.7.egg
Searching for pysaml2<4.0.0,>=3.0.0
Reading https://pypi.python.org/simple/pysaml2/
Best match: pysaml2 3.0.2
Downloading https://pypi.python.org/packages/a0/c6/71f2944e8d192f700c28793c6522e1adcf844330f910b4c9dba5e282bb4d/pysaml2-3.0.2.tar.gz#md5=9a618b472c3057fadaa97a1414be9a6d
Processing pysaml2-3.0.2.tar.gz
Writing /tmp/easy_install-8JxVNl/pysaml2-3.0.2/setup.cfg
Running pysaml2-3.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8JxVNl/pysaml2-3.0.2/egg-dist-tmp-2vMdmn
warning: no files found matching 'README'
creating /home/testmarkjh/synapse/.eggs/pysaml2-3.0.2-py2.7.egg
Extracting pysaml2-3.0.2-py2.7.egg to /home/testmarkjh/synapse/.eggs

Installed /home/testmarkjh/synapse/.eggs/pysaml2-3.0.2-py2.7.egg
Traceback (most recent call last):
  File "./setup.py", line 83, in <module>
    scripts=["synctl"] + glob.glob("scripts/*"),
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 150, in run
    self.distribution.install_requires)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 825, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1063, in best_match
    dist = working_set.find(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 700, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (Jinja2 2.7.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('Jinja2>=2.8'))
```

**Comment by NegativeMjark** [comment]
Without your changes running ``setup.py test`` on my box installs tox and runs the tests.

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

**Comment by richvdh** [comment]
> Without your changes running setup.py test on my box installs tox and runs the tests.

In a clean virtualenv, following the instructions at https://github.com/matrix-org/synapse/blob/master/README.rst#synapse-development?

**Comment by NegativeMjark** [comment]
On a clean account without a virtualenv.
With a virtualenv it fails in the way you describe.

**Comment by NegativeMjark** [comment]
Although ``pip install virutalenv; setup.py test`` seems to work fine.

**Comment by NegativeMjark** [comment]
I'm not trying to argue that you should make ``setup.py test`` run tox correctly fwiw. I'm happy to see that hack die.

It'd just be nice to make ``setup.py test`` give a more helpful error message.

**Comment by NegativeMjark** [comment]
Can you put back the ``Tox`` command, but rather than making it run tox, could it just print an error explaining how people are supposed to run the tests?

**Comment by NegativeMjark** [comment]
I don't think people should ever run the default implementation of ``setup.py test`` fwiw.

**Comment by NegativeMjark** [comment]
In fact if we can discourage people from running ``setup.py`` at all it'd be nice. It exists entirely as a way for pip, and the debian packaging tools to learn the dependencies and the package metadata.

**Comment by richvdh** [comment]
I'm a bit dubious, but have done as you suggest.

**Comment by NegativeMjark** [comment]
Maybe link to the README once the README has the correct instructions?

**Pull request merged**
