### PR TITLE
Enable cleaning up extremities with dummy events

### PR DESCRIPTION
**Pull request by neilisfragile**

### CODE REVIEW

**Comment by erikjohnston** [comment]
I think we decided to wait until we see how this goes on matrix.org?

**Comment by richvdh** [comment]
please can we give our PRs legible names?

**Comment by richvdh** [comment]
(incidentally, this happened because the first line of the git commit comment was [over 50 chars](https://chris.beams.io/posts/git-commit/#limit-50))

**Comment by neilisfragile** [comment]
> I'm kinda wondering if there is any point retaining the config option. Why not remove it, and there's one less toggle that we have to worry about tripping us up when we forget to test it works?

Only in the case that we discover it doesn't work for all cases, or need to roll it back. I'd be happy to remove it in a future release though.

**Comment by richvdh** [comment]
Given that this has been on matrix.org for some time without causing disasters, I see no real reason not to roll it out.

#6053 fixes an edge-case in it.

**Pull request merged**
