### PR TITLE
Fix bug where current_state_events renamed to current_state_ids

### PR DESCRIPTION
**Pull request by erikjohnston**

### CODE REVIEW

**Comment by erikjohnston** [comment]
fixes https://github.com/matrix-org/synapse/issues/1785

**Comment by NegativeMjark** [comment]
This looks like it probably fixes the ISE in #1785. I would appreciate if we had a slightly better idea of what the code is doing here since I think it should only be reached via https://github.com/matrix-org/synapse/blob/v0.18.7-rc2/synapse/federation/federation_server.py#L559

**Comment by NegativeMjark** [comment]
It seems a bit weird to attempt to store an outlier with state since I thought the whole point of an outlier was that it was an event without state. Would it make more sense to treat the event as some weird form of backfill in this case?

**Comment by erikjohnston** [comment]
We probably don't persist it, but use it to do some auth on the event.

**Pull request merged**
