### PR TITLE
Fix some bugs in the auth/ldap handler

### PR DESCRIPTION
**Pull request by sargon**
See the commit messages for more details.

### CODE REVIEW

**Comment by sargon** [comment]
Why is that bot commenting 5 times in a row?

**Comment by erikjohnston** [comment]
@matrixbot ok to test

Sorry abiut the spam, It's a bug in jenkins since we have 5 separate test
suites set up for synapse

**Comment by sargon** [comment]
No offense, just curious about it. 
But that explains.

**Comment by mweinelt** [comment]
lgtm

**Comment by erikjohnston** [comment]
Thanks for this!

Can you just sign off this PR by either signing the commit or commenting here (as per https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off). Once that's done I'll merge :)

**Comment by sargon** [comment]
Done.

**Pull request merged**
