### PR TITLE
Stop ignoring a couple more files for mypy

### PR DESCRIPTION
**Pull request by clokep**
We do this by adding specific `ignore` statements on the lines that break.

This is not ideal, but much more local than ignoring the entire file.

### CODE REVIEW

**Review by reivilibre — APPROVED** [review]
disadvantage is that these are hidden away a bit more now, but I don't think we've been burning down the ignore list for a while anyway so I guess this is probably better overall

**Comment by clokep** [comment]
I think finding all the `type: ignore` and fixing those is another problem, yes. We do (now) have mypy configured to tell us if there's an invalid one though.

**Comment by reivilibre** [comment]
> We do (now) have mypy configured to tell us if there's an invalid one though.

ah, nice :).

**Comment by clokep** [comment]
Err where "invalid" really means "unnecessary".

**Pull request merged**
