### PR TITLE
Support login using Javascript Web Tokens (JWT)

### PR DESCRIPTION
**Pull request by nikriek**
The flow is not fully tested. I'm open for comments first.

### CODE REVIEW

**Comment by erikjohnston** [comment]
Thanks! I'll take a look tomorrow.

Sorry about the matrixbot thing, its a bug in how we're using jenkins :(

**Comment by erikjohnston** [comment]
@matrixbot ok to test

**Comment by erikjohnston** [comment]
(Jenkins is now complaining about the fact that jwt isn't installed.)

**Comment by nikriek** [comment]
Thanks! I'll fix these things if you are ok with the rest.

**Comment by nikriek** [comment]
I'm using [PyJWT](https://github.com/jpadilla/pyjwt) for JWT decoding, but I can't get it work with the dependency handling.

**Comment by erikjohnston** [comment]
@matrixbot ok to test

**Comment by erikjohnston** [comment]
Some PEP8 warnings: http://matrix.org/jenkins/job/SynapseFlake8Packaging/129/violations/#pep8

**Comment by erikjohnston** [comment]
LGTM (even jenkins is happy!)

Our unit testing is a bit woeful atm; the bulk of the testing is done via [sytest](https://github.com/matrix-org/sytest/), which is written in Perl. Since this is a fairly simple PR I'm happy to just merge this now and for us to add a sytest for it down the line (unless you're happy writing Perl).

--

Could you also follow https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off, i.e. adding `Signed-off-by: Your Name <your@email.example.org>` to the commit or simply commenting here?

**Comment by nikriek** [comment]
Signed-off-by: Niklas Riekenbrauck <nikriek@gmail.com>

**Comment by nikriek** [comment]
Thanks!

**Comment by erikjohnston** [comment]
Thanks! Feel free to open a PR to add yourself to the AUTHORS.rst.

**Pull request merged**
