### PR TITLE
Opt out of cache expiry for `get_users_who_share_room_with_user`

### PR DESCRIPTION
**Pull request by DMRobertson**
We'll still invalidate the cache as usual, and we'll still throw away entries if the cache gets too big. But we won't prematurely throw away entries just because they haven't been used in a while.

Might help with #10786.

### CODE REVIEW

**Review by erikjohnston — APPROVED** [review]
I'm going to manually merge this onto the hotfixes branch while we decide if we want to make it part of the RC or not

**Comment by DMRobertson** [comment]
> I'm going to manually merge this onto the hotfixes branch while we decide if we want to make it part of the RC or not

We didn't end up adding it to the RC. I guess this is best pointed at develop now?

**Review by erikjohnston — APPROVED** [review]
I think people made noises that this helped?

**Comment by DMRobertson** [comment]
Sytest failures are in flakes that should be dealt with by matrix-org/sytest#1142.

**Pull request merged**
