### PR TITLE
Fix missing app variable in mail subject

### PR DESCRIPTION
**Pull request by br4nnigan**
homeserver.yaml documentation claims that you can use the %(app)s variable in password_reset and email_validation subjects, but if you do you end up with an error 500

for seo reasons here's the complete error

```
2022-01-09 19:57:33,737 - synapse.handlers.identity - 415 - ERROR - POST-43 - Error sending threepid validation email to operator@mydomain.net
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/identity.py", line 412, in send_threepid_validation
    await send_email_func(email_address, token, client_secret, session_id)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/push/mailer.py", line 212, in send_add_threepid_mail
    % {"server_name": self.hs.config.server.server_name},
KeyError: 'app'
2022-01-09 19:57:33,738 - synapse.http.server - 92 - INFO - POST-43 - <XForwardedForRequest at 0x7f3ebc607ef0 method='POST' uri='/_matrix/client/r0/account/3pid/email/requestToken' clientproto='HTTP/1.0' site='8008'> SynapseError: 500 - An error was encountered when sending the email
```

### CODE REVIEW

**Comment by clokep** [comment]
@br4nnigan Thank you for your contribution, could you please [sign-off](https://github.com/matrix-org/synapse/blob/develop/CONTRIBUTING.md#sign-off) by adding another commit or modifying the PR description. Thanks!

**Comment by br4nnigan** [comment]
> @br4nnigan Thank you for your contribution, could you please [sign-off](https://github.com/matrix-org/synapse/blob/develop/CONTRIBUTING.md#sign-off) by adding another commit or modifying the PR description. Thanks!

Does that make my information public? I can't find any sign offs in other merged commits. Also I'm using a Google account for github which makes associating it with my real name even worse. Sorry about that, I know it's in the docs. If everything fails just make the commit yourself. It was an annoying bug and it should be fixed.

**Comment by DMRobertson** [comment]
> I can't find any sign offs in other merged commits.

The synapse-core team don't include sign-offs; I think because their contributions are done on paid Element time, the ownership of the change it automatically assigned to the Matrix.org foundation. (Beware: I'm not a lawyer.)

> Does that make my information public? 

Yes. I've raised this internally and I don't think we need your formal sign-off for a small fix like this. We'd still like to assign you credit though if you'd like, as a show of gratitude! Are you happy to be credited as "@br4nnigan"?

In the meantime, I'll fixup the PR to pass lints and get CI underway.

**Comment by br4nnigan** [comment]
> In the interests of moving this forward quickly, I'll make a new PR with the fixes.

well the option is check as far as I can tell but go ahead with what you gotta do please

**Comment by DMRobertson** [comment]
Sorry, I think I made a mistake invoking `git` there. Anyway, let's continue this on #11745.

**Comment by DMRobertson** [comment]
All sorted now (https://github.com/matrix-org/synapse/commit/d70169bf9b4b4a2e8369ae7bd5af798cb8945fa3). Sorry for the slightly chaotic process there, and thanks again for your contribution!

**Pull request closed without merging**
