### PR TITLE
Update Debian packaging

### PR DESCRIPTION
**Pull request by behrmann**
### Pull Request Checklist

This PR updates the Debian packaging to a more recent version of debhelper (within the limits of current Debian targets, judging from `scripts-dev/build_debian_packages.py`). It drops stuff that is related to init scripts, since the package doesn't ship any anymore.

I also added an explicit system group for the system user, as currently the files owned by the `matrix-synapse` user will belong to the `nobody` group, which is not ideal, since that group will regularly be used for unrelated things, so having data owned by `matrix-synapse` possibly readable by other system users by accident. If there is some deeper meaning behind this, I'll happily drop this commit, but since the repo that initally did the Debian packaging doesn't seem to exist anymore, I couldn't find a reasoning right away.

The major reason for me wanting to touch the Debian packaging (something I generally try to avoid), was that I wanted to fold the worker config into the regular packaging. The idea is to ship the worker service file, but not enable it. This has the benefit, that the debhelper generated postinst script will restart the target, which leads to the workers being restarted, too. This is something that can bite people using workers, since only the main service unit will be restarted. 

I also moved the hardening config right into the service files. While I understand the idea of wanting to have a simple, easy to read service file, I think the upside of having a really locked down service, is a great benefit. I've been running that config for over a year by now (and a similar one before that). If you'd like to hide this, there would also be the option of moving all the hardening config into `matrix-.service` or `matrix-.service.d (units have multiple namespaces, separated by dashes, so `matrix-synapse.service` actually looks for config in `matrix-synapse.service`, `matrix-synapse.service.d/*.config`, `matrix-.service`, `matrix-.service.d/*.config`). This way the file itself would be simple, but systemd would still pick it up by default (and e.g. show it in the output of `systemctl cat matrix-synapse.service`)

What I haven't touched yet is the systemd readme and service file in `contrib/`, but the (already now) the quality of the service file shipped in the Debian packaging is higher than the example there, so maybe they should be dropped in favour of links to the ones in the Debian packaging.

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Review by richvdh — COMMENTED** [review]
thanks! Before we take a proper look at this, please could you split it up into several smaller PRs that aren't changing lots of things at once (eg, make the debhelper change one PR, and the removal of the init stuff another)

**Comment by DMRobertson** [comment]
> @richvdh I spun out the first three commits into #13593 and #13594. I'll leave the others for later, since they rest somewhat on these first ones.

It looks like those two changes landed. Please advise: is there more to extract from this PR, or should we close this?

**Comment by behrmann** [comment]
This one's not done yet and I picked up some more along the way, but I've been swamped with work the past few weeks and hadn't had time to update my PRs, sorry. I'll try to make room for them soon.

**Comment by DMRobertson** [comment]
(Not to worry---just checking if there's any tidying up to do on our part.)

**Comment by clokep** [comment]
@behrmann Hello! Any chance of finishing up this pull request?

**Comment by behrmann** [comment]
I'll close this one, as it's got to many conflicts anyhow and is better done piecemeal, but I'll get back to #13696.

**Pull request closed without merging**
