### PR TITLE
preview_url_resource: Ellipsis must be in unicode string

### PR DESCRIPTION
**Pull request by kyrias**
Been getting

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

errors due to the ellipsis not being marked as a unicode string.  Damn you py2.

### CODE REVIEW

**Comment by kyrias** [comment]
Err, whops, deleted the wrong branch .-.

**Comment by kyrias** [comment]
(Also, why is it doing it five times?)

**Comment by ara4n** [comment]
lgtm - thanks :)

**Comment by richvdh** [comment]
This has broken the unit tests. Please can we not merge PRs without running the tests.

**Comment by kyrias** [comment]
Huh, which test?  Because without it, this case is broken due to py2 handling of Unicode.

**Comment by kyrias** [comment]
And I just tried running the tests from master, and they succeed without any failures?  Can't find any failures related to this or the develop branch after this in develop either.

**Comment by kyrias** [comment]
s/from master/from develop/

**Comment by richvdh** [comment]
http://matrix.org/jenkins/job/SynapseUnittestsCommit/2165/testReport/

The problems are probably in the unit tests rather than your fix, but nevertheless they need fixing. I can do so if you don't beat me to it. My snarky comment was aimed at @ara4n ...

**Comment by kyrias** [comment]
Ah, seems they're also using non unicode strings.  Is there a simple way to run those tests from the commandline btw, since it didn't fail from `setup.py test`?

**Comment by richvdh** [comment]
`tox -e py27` should do it

Or if you already have a virtualenv, `trial tests`

**Comment by richvdh** [comment]
(maybe tox doesn't work; it's a bit of a black box to me tbh)

**Comment by kyrias** [comment]
Yeah, it seems `setup.py test` runs the same tests as `tox -e py27` though when I try running `./jenkins-unittests.sh` I just get the help output of the coverage command, argh.

**Comment by kyrias** [comment]
`tox -e py27` seems to run coverage properly, but no actual unit tests?

**Comment by kyrias** [comment]
Oh, managed to get them run by setting `PYTHONPATH` manually.

**Pull request merged**
