### PR TITLE
Introduce a concept of internal plugins

### PR DESCRIPTION
**Pull request by turt2live**
The first cut of this only supports listening to room alias association creations, however it adds the structure needed to add and support future events.

Sample plugin: https://github.com/turt2live/synapse-test-plugin
If the plugin is installed correctly and working, you should be able to grep for `TEST PLUGIN` in your logs after creating an alias on a room.

Full disclosure: This is something that t2bot.io is using, although as a really disgusting hack. This PR is an attempt to make it more generalized for everyone else.

### CODE REVIEW

**Comment by turt2live** [comment]
Decided to make this async because while developing https://github.com/turt2live/synapse-plugin-relate-groups I managed to deadlock synapse.

**Comment by turt2live** [comment]
Rebased to clean up the history a bit.

**Comment by richvdh** [comment]
we'll need a sign-off if this is Copyright Travis, as opposed to a thing you are doing with your employee hat on.

**Comment by richvdh** [comment]
oh, which we have on the commit. ignore me.

**Comment by richvdh** [comment]
> decided to make this async 

good decision I think, though note that it will cause problems for anyone who thinks it is a great idea to start poking into `hs` and running methods therein on the wrong thread.

**Comment by richvdh** [comment]
also: the CI is failing due to stylechecky things.

**Comment by turt2live** [comment]
I'm just going to make the commits easier on myself:

Signed-off-by: Travis Ralston <travpc@gmail.com>

**Comment by turt2live** [comment]
In the year this has been open, I've become more and more convinced that this isn't the right approach for things. The solution might indeed work for some use cases, but the use cases it aims to solve at the moment are best served with other tooling or in other places.

**Pull request closed without merging**
