### PR TITLE
Enable guest access for private rooms by default

### PR DESCRIPTION
**Pull request by erikjohnston**

### CODE REVIEW

**Comment by NegativeMjark** [comment]
Do we need to update the docs at https://github.com/matrix-org/matrix-doc/blob/master/api/client-server/create_room.yaml#L130 ?

**Comment by NegativeMjark** [comment]
LGTM

**Comment by erikjohnston** [comment]
@matrixbot retest this please

**Comment by erikjohnston** [comment]
@matrixbot retest this please

**Pull request merged**
