### PR TITLE
Replace old style error catching with 'as' keyword

### PR DESCRIPTION
**Pull request by NotAFile**
This is both easier to read and compatible with python3 (not that that
matters)

### CODE REVIEW

**Comment by richvdh** [comment]
thanks, but please could you see https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst - particularly regarding (a) PRing against develop and (b) signing off your contribution. Sorry!

**Comment by NotAFile** [comment]
Oh, right I should probably have checked that. Are you fine with force-pushing pull request branches? I assume so.

**Comment by NotAFile** [comment]
I've fixed this according to your requirements. I though it would notify you automatically when I push, but it seems not, so here's a manual notification.

**Comment by richvdh** [comment]
thanks!

[I wonder if there is a way to enforce this with flake8]

**Comment by NotAFile** [comment]
One way would be running tests under py3 :)

**Comment by richvdh** [comment]
> One way would be running tests under py3 :)

Yup. As soon as you've got the unit tests passing under py3, I'd be up for running them under py3 on Travis, even if we're a way off getting sytest passing.

**Pull request merged**
