### PR TITLE
Create user with short term expiry

### PR DESCRIPTION
**Pull request by negzi**
Create user with short term expiry.

### CODE REVIEW

**Comment by erikjohnston** [comment]
So, just stepping back a second and thinking a little about the best way of doing this, there are a couple of questions I have:

- Does this need to use an AS? AS's require a fair bit of config to set up, which isn't ideal if the only thing the other server needs to do is to create users. On the other hand, using an AS means that you can ensure the other server only creates users with a certain prefix.
- Could the other server register the user once, and then store a token? As the other server could simply add the time constraint to the macaroon/token itself each time it served the token to whatever used it.
- There is also the `registration_shared_secret` config option that might be another way of doing this; instead of requiring the other server be a registered AS, auth using the registration shared secret.

**Comment by erikjohnston** [comment]
Could you also pull in develop to fix the tests please? :)

**Comment by negzi** [comment]
Oj, sure I will pull the develop. Sorry for the clumsy mistakes, I will do better for the next pull request ;p I am leaving for the weekend now but will answer and fix soon :) Thanks for quick responses and all the help!!

**Comment by erikjohnston** [comment]
That's absolutely no problem! I still sometimes make PRs based on wrong branch.

Have a good weekend :)

**Pull request closed without merging**
