### PR TITLE
Add http2 to the nginx example config

### PR DESCRIPTION
**Pull request by auscompgeek**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by clokep** [comment]
A couple of questions:

* This causes nginx to terminate HTTP/2, but it still talks HTTP/1.1 to the backend?
* Is this available in older nginx versions? (Is someone blindly copying and pasting this likely going to break something?)

**Comment by auscompgeek** [comment]
> This causes nginx to terminate HTTP/2, but it still talks HTTP/1.1 to the backend?

Yes.

> Is this available in older nginx versions?

`http2` was added in nginx 1.9.5, released in 2015: https://www.nginx.com/blog/nginx-1-9-5/

**Comment by clokep** [comment]
Hmmm, their docs do say that HTTP/2 support isn't built by default though: https://nginx.org/en/docs/http/ngx_http_v2_module.html

**Comment by auscompgeek** [comment]
I can't imagine that'll be a problem in practice unless people are building their own nginx. [Debian's nginx-full](https://packages.debian.org/buster/nginx-full) (the default provider of the `nginx` package) ships with HTTP/2 support, and from what I can tell [Alpine also ship nginx with HTTP/2](https://git.alpinelinux.org/aports/tree/main/nginx/APKBUILD?h=3.9-stable#n188).

**Review by clokep — APPROVED** [review]

**Comment by clokep** [comment]
Fair enough. I hope it would give a reasonable error message in that case anyway.

**Pull request merged**
