### PR TITLE
Process cross-signing keys when resyncing device lists

### PR DESCRIPTION
**Pull request by babolivier**
It looks like `user_device_resync` was ignoring cross-signing keys from the results received from the remote server. This PR fixes this, by processing these keys using the same process [`_handle_signing_key_updates`](https://github.com/matrix-org/synapse/blob/bfae0f007e0b01415471e94ca48ac3b1f277a412/synapse/handlers/e2e_keys.py#L1286) does (and effectively factor that part out of that function).

Fixes https://github.com/matrix-org/synapse/issues/7504.

Fixes https://github.com/matrix-org/synapse/issues/7521.

### CODE REVIEW

**Comment by jcgruenhage** [comment]
ooi, I don't see the user signing key there. What's the reason to not process them here?

**Comment by babolivier** [comment]
> ooi, I don't see the user signing key there. What's the reason to not process them here?

It's not returned by `GET /user/devices/{userId}`, as detailed here: https://12682-24998719-gh.circle-artifacts.com/0/scripts/gen/server_server/unstable.html#get-matrix-federation-v1-user-devices-userid (which is the deployed artifact of https://github.com/matrix-org/matrix-doc/pull/2536), so that endpoint is following the spec and therefore, since we're processing its response, we can't process user signing keys.

I haven't worked on the cross-signing specification/implementation, so I don't know if this is right - I assume it is but I've binged internally some people who did to make sure we're not messing something up here.

**Comment by babolivier** [comment]
@dbkr said:

> that's correct - other people don't need your USK, you only use it yourself, so it doesn't need to be sent over federation

So it looks like we're doing the right thing here. I'm going to add a comment to this PR explaining this.

**Comment by jcgruenhage** [comment]
@babolivier yes for now that's true, but this is blocking any web-of-trust usecases. There is no harm in sharing the USK here and in general, right?

**Pull request merged**
