### PR TITLE
Fix possible AttributeError when account-api is called over unix socket

### LINKED ISSUE #16396: Calls to `/_matrix/client/v3/account/whoami` return 500 when called on a unix socket
### Description

I have synapse set up to listen on a unix socket, and mautrix-whatsapp trying to connect to it via that socket. This does not work, as when accessing the `whoami`-endpoint the server returns error code 500 with the message `M_UNKNOWN`.

The homeserver log reveals that this is due to the code expecting a host to be set, when this isn't applicable in a unix socket usecase.

### Steps to reproduce

- Configure synapse to listen on unix socket
- Configure appservice (mautrix-whatsapp) that accesses the `whoami` endpoint to connect to server via unix socket

### Homeserver

self-hosted

### Synapse Version

1.29.1

### Installation Method

Other (please mention below)

### Database

fresh postgresql 15.4 setup

### Workers

Single process

### Platform

archlinux arm

### Configuration

_No response_

### Relevant log output

```shell
2023-09-27 18:04:10,377 - synapse.http.server - 140 - ERROR - GET-660 - Failed handle request via 'WhoamiRestServlet': <XForwardedForRequest at 0
xffff94056e50 method='GET' uri='/_matrix/client/v3/account/whoami?user_id=%40whatsappbot%3Asir-photch.xyz' clientproto='HTTP/1.1' site='unix'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/synapse/http/server.py", line 326, in _async_render_wrapper
    callback_return = await self._async_render(request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/http/server.py", line 538, in _async_render
    callback_return = await raw_callback_return
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/rest/client/account.py", line 851, in on_GET
    requester = await self.auth.get_user_by_req(request, allow_guest=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/api/auth/internal.py", line 82, in get_user_by_req
    requester = await self._wrapped_get_user_by_req(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/api/auth/internal.py", line 118, in _wrapped_get_user_by_req
    ip_addr = request.getClientAddress().host
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UNIXAddress' object has no attribute 'host'
```

### Anything else that would be useful to know?

_No response_

### PR DESCRIPTION
**Pull request by Sir-Photch**
Fixes #16396

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off) **via email**
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Review by erikjohnston — APPROVED** [review]
Thanks!

**Comment by erikjohnston** [comment]
@Sir-Photch you need to sign off this PR, as per the [contributing guide](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off).

**Comment by Sir-Photch** [comment]
I've sent you guys an email about that

**Comment by InezMc** [comment]
Private sign off has been recieved. 

> @Sir-Photch you need to sign off this PR, as per the [contributing guide](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off).

**Comment by erikjohnston** [comment]
Thanks both!

**Pull request merged**
