### PR TITLE
Remove fixed and flakey tests from the sytest blacklist

### PR DESCRIPTION
**Pull request by DMRobertson**
Method:

- [x] Comment out all blacklisted tests
- [x] Run tests
- [x] Comment out that ones that fail
- [x] Run tests
- [x] Check that everything passes
- [ ] Check the tests which are still commented out are genuinely fixed (i.e. corresponding issues are closed)
- [ ] Delete those tests
- [ ] ???
- [ ] Profit

### CODE REVIEW

**Comment by DMRobertson** [comment]
I was quite optimistic, because many of these seemed not to fail. But reading around on github, I think the only one that has actually had a specific fix put in is `Enabling an unknown default rule fails with 404` from https://github.com/matrix-org/synapse/issues/1531. Perhaps many others are flakey?

**Comment by DMRobertson** [comment]
The worker-specific blacklist history is [here](https://github.com/matrix-org/synapse/blame/05111f8f26252cc936fce685846322289039128d/.buildkite/worker-blacklist). (My rename of .buildkite to .ci obscured that.)

These all succeeded so I'm guessing they're just prone to flakiness?

**Comment by DMRobertson** [comment]
> The worker-specific blacklist history is [here](https://github.com/matrix-org/synapse/blame/05111f8f26252cc936fce685846322289039128d/.buildkite/worker-blacklist). (My rename of .buildkite to .ci obscured that.)
> 
> These all succeeded so I'm guessing they're just prone to flakiness?

https://github.com/matrix-org/synapse/runs/3558256491 saw `Device list doesn't change if remote server is down` fail on 2/3 worker runs.

**Review by richvdh — APPROVED** [review]
thank you!

**Pull request merged**
