### PR TITLE
special case m.room.third_party_invite event auth to match invites,

### PR DESCRIPTION
**Pull request by ara4n**
otherwise they get out of sync and you get https://github.com/vector-im/vector-web/issues/1208

### CODE REVIEW

**Comment by erikjohnston** [comment]
Does this fix the associated sytests?

**Comment by ara4n** [comment]
hadn't spotted broken sytests - are you asking for them to be written, or are there existing disabled broken ones?

**Comment by ara4n** [comment]
yes, this fixes the SYN-611 bugs.

**Comment by erikjohnston** [comment]
LGTM

**Pull request merged**
