### PR TITLE
Allow appservice bots to use /sync

### PR DESCRIPTION
**Pull request by tulir**
This allows appservices to use /sync as the appservice bot by simply removing the special-casing of appservice bots.

Related spec proposal: matrix-org/matrix-doc#2190

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#changelog)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

### CODE REVIEW

**Comment by anoadragon453** [comment]
@tulir can you merge this PR forward please?

**Comment by ara4n** [comment]
please can someone take a look at this? i think the reason we removed it originally was because the AS /sync codepath wasn't tested and bitrotted, and at the time there wasn't anyone using it so we removed it rather than maintain it. But @tulir's use case is decent and it'd be good to support it.

**Comment by richvdh** [comment]
neil to have a look at this ticket and decide how to prioritise it

**Comment by neilisfragile** [comment]
[Immediate need has passed](https://github.com/matrix-org/matrix-doc/pull/2190#issuecomment-605667737), so waiting on the MSC to work through the spec process

**Comment by andrewshadura** [comment]
prod prod

**Comment by tchapi** [comment]
Hello all
Is there any update on when this will be merged ?
Thanks a lot !

**Comment by 3nprob** [comment]
> [Immediate need has passed](https://github.com/matrix-org/matrix-doc/pull/2190#issuecomment-605667737), so waiting on the MSC to work through the spec process

Disagree immediate need has passed - see follow-ups.

**Comment by erikjohnston** [comment]
This has been discussed as part of the related [MSC2190](https://github.com/matrix-org/matrix-doc/pull/2190#issuecomment-806955883), where the decision was made to postpone it. As such, I'm going to close this PR and we can reopen if and when the MSC gets resurrected.

**Pull request closed without merging**
