### PR TITLE
handlers/sync: style fix, line too long

### PR DESCRIPTION
**Pull request by Rugvip**

### CODE REVIEW

**Comment by illicitonion** [comment]
Can you wrap one per line?

**Comment by Rugvip** [comment]
In https://github.com/matrix-org/synapse/pull/598 instead :p

**Comment by Rugvip** [comment]
Reopened since https://github.com/matrix-org/synapse/pull/598 might not be merged in a while

**Comment by Rugvip** [comment]
... It wouldn't let me update this one ... https://github.com/matrix-org/synapse/pull/601

**Pull request closed without merging**
