### PR TITLE
Force encryption enabled for room type

### PR DESCRIPTION
**Pull request by FlorianJSa**
### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by anoadragon453** [comment]
Thank you for your changes! However I think they might be quite similar to an existing PR that's already being reviewed, unfortunately: https://github.com/matrix-org/synapse/pull/9983.

**Comment by FlorianJSa** [comment]
> Thank you for your changes! However I think they might be quite similar to an existing PR that's already being reviewed, unfortunately: #9983.

Okay, thanks for your reply. Can you close the issue if there is already a PR or point it out?

**Comment by anoadragon453** [comment]
@FlorianJSa Github does provide some (potentially subtle) UI when a PR links to an issue:

image

But I appreciate it may not be immediately obvious that exists, especially if there are a lot of comments already on the issue. I think as we've gotten used to using Github we've grown to notice these things, but that might not be super useful for new contributors.

We've "linked" the PR now using the Linked pull requests feature to try and make things a bit more obvious, as well as left a comment. Let us know if we can do anything more! :slightly_smiling_face: I'm going to close this now, but feel free to re-open if the other PR starts to stagnate or takes a different direction.

**Comment by FlorianJSa** [comment]
> ut I appreciate it may not be immediately obvious that exists, especially if there are a lot of comments already on the issue. I think as we've gotten used to using Github we've grown to notice these things, but that might not be super useful for new contributors.
> 
> We've "linked" the PR now using the Linked pull requests feature to try and make things a bit more obvious, as well as left a comment. Let us know if we can do anything more!  I'm going to close this now, but feel free to re-open if the other PR starts to stagnate or takes a different direction.

Okay, thank you

**Pull request closed without merging**
