### PR TITLE
Fix nginx config

### PR DESCRIPTION
**Pull request by koyuawsmbrtn**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)

`Signed-off-by: koyu <me@koyu.space>`

### CODE REVIEW

**Comment by dklimpel** [comment]
IMO this line is correct. The used URLs are `/_matrix` and `/_synapse/client`, e.g. used in OIDC (https://matrix-org.github.io/synapse/latest/openid.html#sample-configs)

What is wrong with this line?

**Comment by koyuawsmbrtn** [comment]
I used that line on my Raspberry Pi and it didn't work, `_synapse` just 404ed

**Comment by DMRobertson** [comment]
Agreed with @dklimpel, this doesn't look right. Can you find the log line for the 404 so we can see exactly which URL was not found?

**Comment by koyuawsmbrtn** [comment]
This doesn't 404 anymore since I changed it, but this is the URL Element was trying to reach: https://im.koyu.space/_synapse/admin/v1/users/%40koyu%3Aim.koyu.space/admin

**Comment by DMRobertson** [comment]
> This doesn't 404 anymore since I changed it, but this is the URL Element was trying to reach: https://im.koyu.space/_synapse/admin/v1/users/%40koyu%3Aim.koyu.space/admin

Ahh, I see---the admin API. The very [bottom of that documentation page](https://github.com/matrix-org/synapse/pull/11572) mentions this:

> Endpoints for administering your Synapse instance are placed under /_synapse/admin. These require authentication through an access token of an admin user. However as access to these endpoints grants the caller a lot of power, we do not recommend exposing them to the public internet without good reason.

For that reason, we don't want to encourage people to expose the admin API by default, and so I don't think we'd merge this change. We recommend that you only accept admin API requests from a machine whose access is strictly controlled, rather than the entire public internet.

Note: `\/_matrix|\/_synapse|\/client` will route requests to `$PUBLIC_BASEURL/client` to synapse---but Synapse has no such endpoint. If you still want to make this config change, I'd suggest either `\/_matrix|\/_synapse` or `\/_matrix|\/_synapse/client|\/_synapse/admin`.

**Comment by richvdh** [comment]
> this is the URL Element was trying to reach: https://im.koyu.space/_synapse/admin/v1/users/%40koyu%3Aim.koyu.space/admin

This doesn't sound right to me. Element should not be trying to use the admin api - if it is, that is a bug in element.

**Comment by richvdh** [comment]
@koyuawsmbrtn as a general point for any future contributions - it's very helpful if your PR can explain up front what it is you are trying to achieve, to save people having to ask.  Thank you for getting involved though!

**Comment by koyuawsmbrtn** [comment]
> > this is the URL Element was trying to reach: [im.koyu.space/_synapse/admin/v1/users/%40koyu%3Aim.koyu.space/admin](https://im.koyu.space/_synapse/admin/v1/users/%40koyu%3Aim.koyu.space/admin)
> 
> This doesn't sound right to me. Element should not be trying to use the admin api - if it is, that is a bug in element.

Even if I am admin on the server?

**Comment by callahad** [comment]
> Even if I am admin on the server?

Yep - the Admin API is only designed for use by external / standalone tools since it's a Synapse specific thing. Element itself _shouldn't_ ever try to access Synapse Admin APIs; it should be able to do everything it needs to through standardized Matrix APIs.

**Comment by dklimpel** [comment]
The URLs `/_synapse/admin/` are only for administration. A normal users and element client do not need access to this API.

**Comment by callahad** [comment]
It looks like Element may indeed be trying to access those APIs in [a few places](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/client.ts#L5977-L5992). We'll have to file a bug about that; thank you for bringing it to our attention!

**Pull request closed without merging**
