### PR TITLE
Change matrix.org/beta mentions to vector.im

### PR DESCRIPTION
**Pull request by wldhx**
https://matrix.org/jira/browse/ORG-30

I've heard you welcome small PR's :)

Signed-off-by: Dmitriy Volkov <wldhx+vcs+matrix_org@wldhx.me>

### CODE REVIEW

**Comment by ara4n** [comment]
This is a bit tricky - we don't want to point people by default to Vector, as vector isn't a "reference" client and we don't want to arbitrarily favour any given Matrix client.  Instead we should either make a new neutral reference client or just point people to http://matrix.org/blog/try-matrix-now so they can pick their own.  Will have a think.  Thanks for the PR though.

**Comment by wldhx** [comment]
I see. The second option is probably better for now because of its simplicity. Also, considering 'shiny' is relevant: it'd be nice to have https://try.matrix.org or something like this.

**Comment by ara4n** [comment]
The plan for shiny is the matrix.to domain - eg http://matrix.to/#matrix:matrix.org would both be a neutral way to list all the known clients and optionally jump to a room or user.

**Comment by wldhx** [comment]
Sounds nice. What's the ETA for this?

**Comment by ara4n** [comment]
Probably/hopefully a few weeks away.  In the short term I've resolved this issue by pointing to the try-matrix-now page, so will close off the PR.  Thanks for bringing attention to the issue here! :)

**Comment by wldhx** [comment]
Ok. But the problem is not fully solved yet as there are some mentions of 'matrix.org/beta' in some other projects too. Shall these be changed to 'try-matrix-now', or is it acceptable to just wait for matrix.to?

**Pull request closed without merging**
