### PR TITLE
Build debs for bookworm

### LINKED ISSUE #10609: build packages for debian bookworm
bullseye is now released as debian stable, so we should start building debs for new testing

### PR DESCRIPTION
**Pull request by richvdh**
Fixes #10609

### CODE REVIEW

**Comment by DMRobertson** [comment]
Do we need to update CI to be bookworm-aware? Didn't fully follow all of the details, but I think this will happen for free once `debian:testing` points to bookworm and we run sytest's build.sh/push.sh?

**Comment by richvdh** [comment]
hum; https://hub.docker.com/_/debian does not yet include `bookworm`, so I think this will need to be put on hold.

**Comment by richvdh** [comment]
> Do we need to update CI to be bookworm-aware?

I don't think there's any particular rush on that. We already run sytest against a synapse running on `testing`. The main thing is that we cover a range of python and postgres versions. If testing/bookworm starts to diverge from bullseye, we might want to consider adding extra tests against bullseye, but that can happen later.

**Comment by richvdh** [comment]
> hum; https://hub.docker.com/_/debian does not yet include `bookworm`, so I think this will need to be put on hold.

there is a `testing`, of course, but using it would require some hoop-jumping. I think we'll just wait.

**Comment by richvdh** [comment]
there's now a `bookworm` image, so this is unblocked.

**Review by erikjohnston — APPROVED** [review]

**Pull request merged**
