### PR TITLE
Refactor FederationServer._handle_new_pdu

### PR DESCRIPTION
**Pull request by richvdh**
This is a series of commits which move most of the processing of pdus received over federation /send requests to the FederationHandler.

Unfortunately this significantly increases the size of the already-rather-big FederationHandler, but the code fits more naturally here, and it paves the way for the tighter integration that I need between handling incoming PDUs and doing the join dance.

### CODE REVIEW

**Comment by erikjohnston** [comment]
@matrixbot retest this please

**Comment by erikjohnston** [comment]
@matrixbot test this please

**Comment by erikjohnston** [comment]
lgtm, assuming tests are ok

**Comment by richvdh** [comment]
retest this please

**Comment by richvdh** [comment]
This has finally passed the sqlite tests - not that I have done anything to fix them, so I may as well merge it.

**Pull request merged**
