### PR TITLE
Fix some races in the synapse presence handler caused by not yielding…

### PR DESCRIPTION
**Pull request by NegativeMjark**
… on deferreds

### CODE REVIEW

**Comment by leonerd** [comment]
Erik is assigned, but as the author of the original presence code, LGTM

**Comment by erikjohnston** [comment]
Assuming `set_state` doesn't do something silly like `yield` on a federation request, LGTM

**Comment by leonerd** [comment]
FYI, this may also be the synapse bug alluded to by SYT-34

**Comment by NegativeMjark** [comment]
So having stared at https://github.com/matrix-org/synapse/blob/8899df13bf80a5a3dda2a2df2bc28da0808faa4e/synapse/federation/federation_client.py#L107 a bit I can confirm that the federation send_edu will return immediately so we don't need to worry about yielding on it.

**Comment by leonerd** [comment]
This is tested by sytest commit 1146c0a

**Pull request merged**
