### PR TITLE
Update NixOS module URL

### PR DESCRIPTION
**Pull request by enterprisey**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by enterprisey** [comment]
Signed-off-by: Enterprisey <apersonwiki@gmail.com>

**Comment by DMRobertson** [comment]
Corresponding change was https://github.com/NixOS/nixpkgs/pull/172819

**Review by DMRobertson — CHANGES_REQUESTED** [review]
Change is good, but (as above) needs a sign-off to progress/

**Comment by DMRobertson** [comment]
Sign-off communicated privately, many thanks!

**Comment by DMRobertson** [comment]
Only failure was a known complement flake. I'm going to manually merge.

**Pull request merged**
