### PR TITLE
Fix M_USER_ACCOUNT_SUSPENDED error code for spec compliance

### PR DESCRIPTION
**Pull request by turt2live**
second attempt at https://github.com/matrix-org/synapse/pull/12922, this time without automerge

`M_` is a reserved namespace: https://spec.matrix.org/v1.2/client-server-api/#standard-error-response

For MSC2823.

### CODE REVIEW

**Comment by babolivier** [comment]
This fix needs to be cherry-picked on `release-v1.60` before the release otherwise it won't make it in

**Comment by babolivier** [comment]
Oh actually the original commit is _not_ lined up for the 1.60 release.

**Comment by babolivier** [comment]
Original PR is https://github.com/matrix-org/synapse/pull/12845

**Comment by erikjohnston** [comment]
Bah

**Comment by erikjohnston** [comment]
Wait, this isn't in the RC?

**Pull request merged**
