### PR TITLE
Improved workers.md inc. compact regex + caddy example

### PR DESCRIPTION
**Pull request by Someguy123**
- Changed `pip` to `pip3` to avoid users installing for Python 2.x by accident

 - Added sentence explaining where the virtualenv is, for those who installed it from their
   package manager, and how to use that virtualenv.

 - Added comment to `listeners` and `worker_listeners` example to make it more clear what they do

 - Added warning against simply copy pasting the `listeners` block since it will disable the
   default listener

 - Added `Compact Regular Expressions` section to `Available worker applications`, which contains
   compact regex which covers multiple endpoints in single lines of regex, reducing the number of
   redundant `route xxx {` blocks you'd need in your webserver

 - Added `Example Webserver Configurations` sections, with `Caddy v2` as the first example, which shows
   you how to configure your webserver to point certain routes to your workers, and everything else to
   your main process, with spare matcher blocks for future use by the user.

### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [X] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by anoadragon453** [comment]
Hey @Someguy123, thanks for the contribution! Some initial feedback (and to fix the failing CI):

* We encourage changelog entries to be one or two sentences at most, and have them fit all on one line. You can see existing examples [here](https://github.com/matrix-org/synapse/blob/master/CHANGES.md#synapse-1320rc1-2021-04-13). I'd suggest something along the lines of "Update worker documentation with clarifications regarding python virtualenvs, listener configuration and reverse proxy configuration."
* The changelog newsfile will need to end in `.doc`, rather than `.docs` :)

**Comment by Someguy123** [comment]
> Hey @Someguy123, thanks for the contribution! Some initial feedback (and to fix the failing CI):
> 
>     * We encourage changelog entries to be one or two sentences at most, and have them fit all on one line. You can see existing examples [here](https://github.com/matrix-org/synapse/blob/master/CHANGES.md#synapse-1320rc1-2021-04-13). I'd suggest something along the lines of "Update worker documentation with clarifications regarding python virtualenvs, listener configuration and reverse proxy configuration."
> 
>     * The changelog newsfile will need to end in `.doc`, rather than `.docs` :)

@anoadragon453 - Done 👍

**Review by anoadragon453 — CHANGES_REQUESTED** [review]
Thank you for your hard work here :slightly_smiling_face:  Some small notes, and then some concerns about the proxy routing I'm afraid.

**Comment by richvdh** [comment]
I'm going to close this as it appears to have been abandoned. If you're interested in picking it up again, we can reopen it.

**Pull request closed without merging**
