### PR TITLE
Add info about configuration in the url preview docs

### PR DESCRIPTION
**Pull request by H-Shay**
Adds a link to the relevant section of the config manual in the url preview documentation.

### CODE REVIEW

**Comment by clokep** [comment]
I was thinking we could move this entire page into the URL preview module instead?

**Comment by clokep** [comment]
I'm going to merge this and move them as suggested.

**Comment by clokep** [comment]
> Out of curiosity, why merge this PR vs closing it, as the document that was modified will be deleted by moving it?

In case it is decided that the other PR to move the documentation is unwanted or (for some reason) takes a while to complete it is still beneficial to accept this change.

**Comment by H-Shay** [comment]
Ah cool thanks for explaining!

**Pull request merged**
