### PR TITLE
Enforce all replication HTTP clients calls use kwargs

### PR DESCRIPTION
**Pull request by erikjohnston**
Should prevent https://github.com/matrix-org/synapse/pull/9130 from happening again

### CODE REVIEW

**Comment by clokep** [comment]
Looks like old-deps is failing with invalid syntax errors. 😢

**Comment by erikjohnston** [comment]
> Running setup.py install for frozendict: finished with status 'error'

Uh oh

**Comment by clokep** [comment]
> > Running setup.py install for frozendict: finished with status 'error'
> 
> Uh oh

This actually seems to be #9146.

**Review by clokep — APPROVED** [review]
This should be fine if the build passes.

**Pull request merged**
