### PR TITLE
Fix mypy error: auth handler "checkpw" internal function type mismatch

### PR DESCRIPTION
**Pull request by ShadowJonathan**
> (Wants bytes, got Union[bytes, str] due to context closure inheritance)

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

### CODE REVIEW

**Comment by clokep** [comment]
Are we sure that `validate_hash` accepts both `bytes` and `str`? Looking briefly it seems to only be called in one spot which feeds it a `str`?

**Comment by ShadowJonathan** [comment]
@clokep the function signature announces it accepts `Union[bytes, str]`, you can smooth it to `str` (and replace the `isinstance` with a transform), but i think that's a little out of scope for this PR

**Comment by clokep** [comment]
> @clokep the function signature announces it accepts `Union[bytes, str]`, you can smooth it to `str` (and replace the `isinstance` with a transform), but i think that's a little out of scope for this PR

I'm asking if the function signature is correct. From a cursory look it seems to always accept `str`.

**Comment by clokep** [comment]
I'm also a bit confused at how you found this, `synapse/handlers/auth.py` is already checked via mypy. So, where is this error appearing?

**Comment by ShadowJonathan** [comment]
> I'm also a bit confused at how you found this, synapse/handlers/auth.py is already checked via mypy. So, where is this error appearing?

I found this by running `mypy` as-is on the `develop` branch

I just ran `mypy` and `tox -e mypy` on the same `develop` branch, `mypy` produced
```
synapse/handlers/auth.py:1131: error: Argument 2 to "checkpw" has incompatible type "Union[bytes, str]"; expected "bytes"  [arg-type]
```
while `tox -e mypy` produced nothing.

**Comment by ShadowJonathan** [comment]
Seems like the problem was `tox.ini` not installing `all` dependencies because `skip_install = True` existed.

**Review by richvdh — APPROVED** [review]
as @clokep said, it might have been good to take the opportunity just to change this to accept a `bytes`, but I guess this is fine.

**Pull request merged**
