### PR TITLE
Implement E2E for guests

### PR DESCRIPTION
**Pull request by richvdh**
Expose the endpoints needed to do e2e to to guest users

### CODE REVIEW

**Comment by richvdh** [comment]
retest this please

**Comment by richvdh** [comment]
retest this please

**Comment by richvdh** [comment]
retest this please

**Comment by richvdh** [comment]
TODO: update the spec to add these endpoints to the allowed-for-guests list

**Comment by NegativeMjark** [comment]
LGTM

**Comment by richvdh** [comment]
ta

**Pull request merged**
