### PR TITLE
Add docs for undoing room shutdowns

### PR DESCRIPTION
**Pull request by turt2live**
These docs were tested successfully in production by a customer, so it's probably fine.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by richvdh** [comment]
If everyone has been kicked out of the blocked room, surely you can't rejoin it?

**Comment by turt2live** [comment]
If it's public you can.

**Comment by richvdh** [comment]
You can't rejoin an empty room whether it's public or not

**Comment by turt2live** [comment]
Ah, everyone meaning literally everyone? 

There's a number of cases where you can't undo, hence the "you really screwed up" notice in the second paragraph.

**Comment by richvdh** [comment]
> Ah, everyone meaning literally everyone?

isn't that what the shutdown room API does?

to be clear, I don't object to adding something here... I just fear it adds more confusion than it removes.

**Comment by turt2live** [comment]
The API only deals with local users. Federated users can't be touched, so they're left alone.

**Pull request merged**
