### PR TITLE
Don't change status_msg on /sync

### PR DESCRIPTION
**Pull request by Half-Shot**
Addressing https://matrix.org/jira/browse/SYN-747

Signed-off-by: Will Hunt half-shot@molrams.com

### CODE REVIEW

**Comment by erikjohnston** [comment]
@matrixbot ok to test

**Comment by erikjohnston** [comment]
From the dendron logs:

```
2016-08-10 13:29:26,688 - synapse.http.server - 135 - ERROR - GET-0 - Failed handle request synapse.http.server._async_render on <synapse.http.server.JsonResource object at 0x5421590>: <SynapseRequest at 0x5038248 method=GET uri=/_matrix/client/r0/sync?access_token=<redacted> clientproto=HTTP/1.1 site=20005>
Traceback (most recent call last):
  File "/home/jenkins/jenkins/workspace/SynapseSytestDendronPR/synapse/http/server.py", line 114, in wrapped_request_handler
    yield request_handler(self, request)
  File "/home/jenkins/jenkins/workspace/SynapseSytestDendronPR/.tox/py27/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/jenkins/jenkins/workspace/SynapseSytestDendronPR/.tox/py27/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jenkins/jenkins/workspace/SynapseSytestDendronPR/synapse/http/server.py", line 261, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/home/jenkins/jenkins/workspace/SynapseSytestDendronPR/.tox/py27/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/jenkins/jenkins/workspace/SynapseSytestDendronPR/synapse/rest/client/v2_alpha/sync.py", line 149, in on_GET
    yield self.presence_handler.set_state(user, {"presence": set_presence}, True)
TypeError: set_state() takes exactly 3 arguments (4 given)
```

**Comment by Half-Shot** [comment]
Ooookay? So is dendron testing off an older synapse? ``set_state`` *now* has 4 arguments with one optional.

**Comment by erikjohnston** [comment]
To be honest I don't really understand it either. Dendron is basically testing the split out synapse stuff. I'm guessing there is a `set_state` function somewhere that is being used instead only in dendron? @NegativeMjark ?

**Comment by NegativeMjark** [comment]
Hmm might be something to do with: https://github.com/matrix-org/synapse/blob/master/synapse/app/synchrotron.py#L122

**Comment by Half-Shot** [comment]
O.o
...I'll make it happy

**Comment by erikjohnston** [comment]
LGTM

*cough* you need to sign off the PR *cough

**Comment by Half-Shot** [comment]
I stealth edited it on my original message?

**Pull request merged**
