### PR TITLE
Track why we're evicting from caches

### PR DESCRIPTION
**Pull request by DMRobertson**
So we can see how often we're evicting because the cache is too big or because
the cache entries haven't been recently used. Previously these weren't
distinguishable on Grafana.

### CODE REVIEW

**Review by erikjohnston — APPROVED** [review]
We'll need to remember to update the synapsh grafana dashboard (and export it into `contrib/`)

**Comment by DMRobertson** [comment]
> We'll need to remember to update the synapsh grafana dashboard (and export it into `contrib/`)

Thanks. I guess it's best to wait for a deployment on matrix.org for this?

**Comment by erikjohnston** [comment]
Yup, though feel free to redeploy matrix.org whenever :)

**Comment by DMRobertson** [comment]
> Yup, though feel free to redeploy matrix.org whenever :)

For completeness: this is done now.

**Pull request merged**
