### PR TITLE
Fix broken Arch Linux package link

### PR DESCRIPTION
**Pull request by SnipeXandrej**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [ ] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

`Signed-off-by: Andrej Halveland <andrej.halv@gmail.com>`

### CODE REVIEW

**Review by clokep — APPROVED** [review]

**Comment by SnipeXandrej** [comment]
The change of the word "community" to "official" was meant to mean that the package is no longer a "community" package on Arch Linux but now as an official *Arch Linux* package.

And now that I am looking at it again, it sounds like it's an official package from Matrix.

Is that a problem? Should I change that?

**Comment by clokep** [comment]
> And now that I am looking at it again, it sounds like it's an official package from Matrix.

Oh yes, good thought on how others might interpret this. Maybe something like:

> The quickest way to get up and running with ArchLinux is probably with the package provided from ArchLinux

**Comment by SnipeXandrej** [comment]
I am sorry, I am just overthinking way too much if it's better written with "from" or with "by" in `the package provided {from,by} ArchLinux` sentence.

I kinda hate myself for this, I just spend waaay too long at such trivial stuff.

**Comment by clokep** [comment]
Thank you! 🎉

**Pull request merged**
