### PR TITLE
Use OpenID Connect users with existing accounts

### LINKED ISSUE #7633: Use OpenID Connect users with existing accounts
I have a homeserver that is using LDAP and I want to migrate to OpenID Connect. This requires that existing users can login with OpenID Connect. If an existing user tries to login, I get the following error and login doesn't work: `synapse.handlers.oidc_handler.MappingException: mxid '@snowball:test.example.com' is already taken`

I think this behavior is reasonable as a default because merging with existing users may be a security problem if the admin isn't careful.

[This patch](https://github.com/BBBSnowball/synapse/commit/a1821f320f7a42682a71b79eede1c03879c26c44) adds a config option to allow using existing users. This seems to work for me but needs more testing.

What do you think? Is this a good solution? Are there any better ways to migrate from LDAP (or other password login) to OIDC?

### PR DESCRIPTION
**Pull request by OmmyZhang**
fix #7633 and #8155

### CODE REVIEW

**Comment by clokep** [comment]
Can you merge develop into this for the conflicts / CI? Thank you!

**Comment by OmmyZhang** [comment]
Fine, I need to resolve conflicts at first.

**Comment by clokep** [comment]
No reason to close this, you can push back to the same branch!

**Comment by OmmyZhang** [comment]
@clokep It seems a little complex, as I need to open a PR in BBBSnownball's repository to update this branch.
I have fork BBBSnownball's repository and I will open a new PR soon with my own branch.

**Comment by BBBSnowball** [comment]
@OmmyZhang I have added you as a collaborator. Please feel free to use my repository or yours - whatever is easier for you.

Thanks for continuing this work :-)

**Comment by OmmyZhang** [comment]
@BBBSnowball Thanks for your help! This work seems almost done. (pull #8180 )

**Pull request closed without merging**
