### PR TITLE
Remove unspecced GET endpoints for e2e keys

### PR DESCRIPTION
**Pull request by richvdh**
GET /keys/claim is a terrible idea, since it isn't idempotent; also it throws
500 errors if you call it without all the right params.

GET /keys/query is arguable, but it's unspecced, so let's get rid of it too to
stop people relying on unspecced APIs.

### CODE REVIEW

**Comment by erikjohnston** [comment]
I take it these are unused?

**Comment by erikjohnston** [comment]
(I don't see any calls to those APIs on matrix.org over the weekend)

**Comment by richvdh** [comment]
Yeah... apparently the tests don't think so though. Working on them.

**Comment by richvdh** [comment]
retest this please

**Pull request merged**
