### PR TITLE
Deduplicate new deviceinbox rows for replication

### PR DESCRIPTION
**Pull request by erikjohnston**

### CODE REVIEW

**Comment by richvdh** [comment]
ok, so this looks like it will make the server send fewer RDATAs (or the equivalent json for http) for device inbox messages.

Where do we define what the rows should be for each stream?

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/blob/develop/synapse/replication/tcp/streams.py#L61 are the formats for each type of stream in RDATA

**Comment by richvdh** [comment]
right, but that doesn't really define whether it is valid to skip rows.

**Comment by richvdh** [comment]
Oh, I'm being stupid. LGTM

**Pull request merged**
