### PR TITLE
Correctly ignore invites from ignored users

### LINKED ISSUE #11506: Invites from ignored users may not be ignored
Midway down the digestive system of Synapse's sync code, we fetch all membership changes for a user across the sync period.

After 1709, `event` will be the last element in the list of events, or it'll be unset if there were no such events. They're fetched in ascending stream ordering order, so `event` will be the membership change with highest stream ordering.

https://github.com/matrix-org/synapse/blob/d26808dd854006bd26a2366c675428ce0737238c/synapse/handlers/sync.py#L1703-L1709

There are no other writes to `event`, but there is a read:

https://github.com/matrix-org/synapse/blob/d26808dd854006bd26a2366c675428ce0737238c/synapse/handlers/sync.py#L1794-L1800

I smell a bug. 

- Suppose my `membership_change_events` consists of three events in this order:
   - I'm invited to room A by someone I've ignored
   - I'm invited to room B by someone I've not ignord.
- `event` will be the invite event in room B.
- mem_change_events_by_room_id will be the dictionary `{A: [invite_A], B: [invite_B]}`.
- We start looping over the keys of this dictionary.
- When I process room A, we test `event.sender not in ignored users`
- **`event` refers `invite_B`, whose sender is not ignored. We then push invite_A down to the user.

Well this is just embarrassing. Should be an easy fix though.

### PR DESCRIPTION
**Pull request by DMRobertson**
Fixes #11506. Corresponding test case at matrix-org/complement#267.

### CODE REVIEW

**Review by squahtx — APPROVED** [review]
LGTM!

I found the double negative in the changelog slightly hard to read.
`s/not be omitted/included/`?

**Comment by DMRobertson** [comment]
Thanks, I'll reword that. Is it best to wait for the complement test to be approved before merging too?

**Comment by squahtx** [comment]
> Thanks, I'll reword that. Is it best to wait for the complement test to be approved before merging too?

Probably! I guess we'd want the complement test to be included in the CI for this change.

**Comment by DMRobertson** [comment]
> Probably! I guess we'd want the complement test to be included in CI for this change.

It has done, because the branch names match. see https://github.com/matrix-org/synapse/runs/4431172326?check_suite_focus=true#step:7:1048

**Comment by DMRobertson** [comment]
That sytest is a known flake. I'll rerun CI.

**Pull request merged**
