### PR TITLE
Adding missing API documentation: /_synapse/admin/v1/admin/register

### PR DESCRIPTION
**Pull request by Torxed**
### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by richvdh** [comment]
This is documented at https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/register_api.rst...

(though I realise it may not be easy to find. Maybe it needs a link?)

**Comment by Torxed** [comment]
> This is documented at https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/register_api.rst...
> 
> (though I realise it may not be easy to find. Maybe it needs a link?)

Any reason why this isn't in master so it's searchable from any search engine or even making it easier to find via github?

**Comment by richvdh** [comment]
it's also in master. https://github.com/matrix-org/synapse/blob/master/docs/admin_api/register_api.rst

**Comment by richvdh** [comment]
(by the way, note that our default branch is `develop`, not `master`.)

**Comment by Torxed** [comment]
I accept defeat, hehe! Thanks for the information! :)

**Pull request closed without merging**
