### PR TITLE
Only run trial CI on all python versions on non-PRs

### PR DESCRIPTION
**Pull request by erikjohnston**
To reduce the number of CI jobs we have.

### CODE REVIEW

**Comment by clokep** [comment]
Do we get notified if `develop` fails to build?

**Comment by erikjohnston** [comment]
> Do we get notified if `develop` fails to build?

Ermh, if you've got it set up then yeah? We already have a bunch of tests that only get run on develop.

**Comment by erikjohnston** [comment]
I wonder if we should also skip the TCP replication worker tests that are duplicated by Redis?

**Comment by clokep** [comment]
> Ermh, if you've got it set up then yeah? We already have a bunch of tests that only get run on develop.

If you have what setup? 😕 

> I wonder if we should also skip the TCP replication worker tests that are duplicated by Redis?

All these tests only run on Redis now, see matrix-org/sytest#1282 and the conversation at https://github.com/matrix-org/synapse/pull/13647#discussion_r958760380.

**Comment by erikjohnston** [comment]
> > Ermh, if you've got it set up then yeah? We already have a bunch of tests that only get run on develop.
> 
> If you have what setup? confused

If you have set GHA to email you when a build fails, I'm pretty sure if you have that enabled you get emailed if develop breaks.
 
> > I wonder if we should also skip the TCP replication worker tests that are duplicated by Redis?
> 
> All these tests only run on Redis now, see [matrix-org/sytest#1282](https://github.com/matrix-org/sytest/pull/1282) and the conversation at [#13647 (comment)](https://github.com/matrix-org/synapse/pull/13647#discussion_r958760380).

Ah, OK. I think that makes `(buster, postgres, workers, redis)` pretty redundant, compared with `(buster, multi-postgres, workers)`

**Review by reivilibre — APPROVED** [review]
Can't ever remember seeing a failure only on an intermediate version of Python, so this seems reasonable to me

**Pull request merged**
