### PR TITLE
document how to make IPv6 work

### PR DESCRIPTION
**Pull request by ara4n**

### CODE REVIEW

**Comment by erikjohnston** [comment]
Its probably worth mentioning that Twisted 17 will be installed by default for new pip installations to avoid confusion

**Comment by richvdh** [comment]
fixes #2086 I guess

**Comment by jython234** [comment]
@erikjohnston Will it? My PR (#1909) did that and was rejected.

**Comment by richvdh** [comment]
@jython234: #1909 *required* 17.1 for *all* installations. That's different to "will be installed by default for *new* *pip* installations".

**Comment by richvdh** [comment]
@ara4n this is on you I think

**Comment by ara4n** [comment]
@erikjohnston ptal.

**Comment by jython234** [comment]
@richvdh ah I understand.

**Comment by ZerataX** [comment]
should also either mention https://github.com/matrix-org/synapse/issues/2556 or directly allow empty bind to listen on IPv6

**Pull request merged**
