### PR TITLE
XWiki OIDC provider mapping example

### PR DESCRIPTION
**Pull request by tmortagne**
I documented this on [XWiki side](https://extensions.xwiki.org/xwiki/bin/view/Extension/OpenID%20Connect/OpenID%20Connect%20Provider/Synapse/), but I thought it might be interesting to have it here too.

Signed-off-by: Thomas Mortagne <thomas.mortagne@gmail.com>

### CODE REVIEW

**Comment by clokep** [comment]
@tmortagne Thanks for making a PR for this! Looks like you based it off the `master` branch instead of the `develop` branch. Could you resolve the conflict by merging in `develop`? Thanks!

**Comment by tmortagne** [comment]
Sorry looks like I read the pull request instructions too fast. Fixing that.

**Comment by tmortagne** [comment]
Should be in a better shape now.

**Comment by clokep** [comment]
Thanks!

**Review by clokep — APPROVED** [review]
Seems to match the XWiki documentation! Thanks!

**Pull request merged**
