### PR TITLE
Allow synapse's useragent to be customized

### PR DESCRIPTION
**Pull request by illicitonion**
This will allow me to write tests which verify which server made HTTP
requests in a federation context.

### CODE REVIEW

**Comment by ara4n** [comment]
lgtm, although might it be nice to postpend the version number anyway, to avoid people customising the UA for vanity and stopping us from being able to see in logs etc what version they're running?

**Comment by erikjohnston** [comment]
Yes, please do keep the version string in there too.

**Comment by illicitonion** [comment]
Done

**Comment by erikjohnston** [comment]
From a huge nitpicking perspective, I'd prefer if the user agent string remained in a valid user agent format, which is as simple as changing the delimiter from ` - ` to a single space.

After fixing the tests, LGTM

**Pull request merged**
