### PR TITLE
hide state redaction events from clients as an emergency temporary measure

### PR DESCRIPTION
**Pull request by ara4n**
...to stop a recurrence of the thundering herd problems described at
https://matrix.org/blog/2017/02/17/load-problems-on-the-matrix-org-homeserver/
until we've optimised room initialSync etc.
I know that we've punted room initialSync to the synchrotrons for now, but
hopefully this is a better mitigation for the next few days until we get
to the proper soln.

### CODE REVIEW

**Comment by ara4n** [comment]
this is a proposed *temporary* (like, 1 or 2 day) solution to stave off a repeat of the thundering herd until we've got a slightly less kludging fix in place.  This buys us time to focus on the UpCloud mig and #1760 and #1935 and other even-more-burning fires.

**Comment by ara4n** [comment]
/me realises his deliberate mistake and tweaks

**Comment by ara4n** [comment]
right, this might be more useful now.

**Comment by erikjohnston** [comment]
This is no longer necessary as we have cached the API endpoints the clients hit

**Pull request closed without merging**
