### PR TITLE
Move admin endpoints into separate files

### PR DESCRIPTION
**Pull request by awesome-manuel**
@richvdh @erikjohnston this is a prerequisite for #5925 

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#changelog)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

### CODE REVIEW

**Comment by anoadragon453** [comment]
@awesome-manuel are you still around?

**Comment by awesome-manuel** [comment]
> @awesome-manuel are you still around?

Yes. The PR was rebased to `develop` when I updated it. There also were no linting issues at that time.
But I can update it again to the latest `develop`, hopefully this week.

**Comment by awesome-manuel** [comment]
@anoadragon453 can you trigger buildkite please?

**Comment by richvdh** [comment]
@awesome-manuel I triggered it; it should run automatically in future. Looks like the CI is very unhappy about something - could you investigate?

**Comment by richvdh** [comment]
mostly `builtins.ImportError: cannot import name 'assert_user_is_admin'` apparently.

**Comment by awesome-manuel** [comment]
> mostly `builtins.ImportError: cannot import name 'assert_user_is_admin'` apparently.

Strange, since `assert_requester_is_admin` is imported the same way and has no problems...

**Comment by awesome-manuel** [comment]
@richvdh Should be fixed now

**Comment by awesome-manuel** [comment]
@richvdh @anoadragon453 everything is fixed now.

**Pull request merged**
