### PR TITLE
Add GET method to admin API /users/@user:dom/admin

### PR DESCRIPTION
**Pull request by reivilibre**
Signed-off-by: Olivier Wilkinson (reivilibre) <olivier@librepush.net>

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#changelog)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

### CODE REVIEW

**Comment by erikjohnston** [comment]
Would be good to get some tests for these APIs

**Comment by awesome-manuel** [comment]
@reivilibre I'd prefer a PUT on `/_synapse/admin/v1/users/<user_id>` with optional fields in the body: `admin`, `displayname`, `password`, `avatar`.

**Comment by richvdh** [comment]
@awesome-manuel PUT seems inappropriate for an API which doesn't change anything?

**Comment by awesome-manuel** [comment]
> @awesome-manuel PUT seems inappropriate for an API which doesn't change anything?

Ah, sorry wrong PR. This one add GET, but there is already a PUT on `/_synapse/admin/v1/users/<user_id>/admin`.
So this one could be GET `/_synapse/admin/v1/users/<user_id>` and return all information for this user.

**Comment by richvdh** [comment]
I guess it's nice to have a `GET /_synapse/admin/v1/users/<user_id>/admin` to match the existing PUT endpoint.

A (working) `GET /_synapse/admin/v1/users/<user_id>` is probably a separate job. See also #2522.

**Comment by reivilibre** [comment]
I heard the option of `PATCH` for doing something like that, and it isn't a terrible idea.

That said, setting display name and avatar requires impersonating the user to send state events currently – not sure how great that is.

**Pull request merged**
