### PR TITLE
SYN-646 - Register endpoint returns refresh_token

### PR DESCRIPTION
**Pull request by blide**
Guest registration still doesn't return refresh_token

### CODE REVIEW

**Comment by erikjohnston** [comment]
@matrixbot ok to test

**Comment by erikjohnston** [comment]
The flake8 test failed due to: http://matrix.org/jenkins/job/SynapseFlake8Packaging/51/violations/file/tests/rest/client/v2_alpha/test_register.py/

**Comment by blide** [comment]
Fixed

**Comment by erikjohnston** [comment]
Brilliant, thanks for this! Could you just follow the sign off steps: https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off? Just commenting with "Signed-off-by: Your Name <your@email.example.org>" here is fine.

**Comment by erikjohnston** [comment]
Also feel free to add yourself to `AUTHORS.rst` :)

**Comment by blide** [comment]
Thanks for a good project. 
Signed-off-by: Roman Shakhov <r.intval@gmail.com>

**Pull request merged**
