### PR TITLE
add org.matrix.login.jwt so that m.login.jwt can be deprecated

### PR DESCRIPTION
**Pull request by Sorunome**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

`m.login.jwt` is not part of the spec, and the `m.` namespace is reserved for things in the spec. When soru asked about this a few months ago, the reply was to **not** use this endpoint and that it might be removed at any point in time, due to not being in the spec. This PR namespaces the endpoint properly.

Signed-off-by: Sorunome <mail@sorunome.de>

### CODE REVIEW

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/matrix-doc/issues/1658

**Comment by Sorunome** [comment]
Also related: https://github.com/matrix-org/matrix-doc/pull/2416

**Comment by Sorunome** [comment]
Done

**Comment by Sorunome** [comment]
Done!

**Pull request merged**
