### PR TITLE
Fix /federation/v1/state for recent room versions

### PR DESCRIPTION
**Pull request by richvdh**
Turns out this endpoint was completely broken for v3 rooms. Hopefully this
re-signing code is irrelevant nowadays anyway.

### CODE REVIEW

**Comment by richvdh** [comment]
(test in https://github.com/matrix-org/sytest/pull/716)

**Comment by anoadragon453** [comment]
This PR is consistently failing on the `Name/topic keys are correct`. Perhaps your branch needs to be merged forwards?

**Comment by richvdh** [comment]
the latter, I think

**Comment by anoadragon453** [comment]
\* tries to run the tests again

**Pull request merged**
