### PR TITLE
Update to reflect new location at github.

### PR DESCRIPTION
**Pull request by RickCogley**
Additionally it does not appear there is turnserver.conf.default, but rather, just /etc/turnserver.conf.

### CODE REVIEW

**Comment by RickCogley** [comment]
We should be a little more clear on the part about importing certificates for TLS, I think.

When I set this up, I used ``sudo apt-get install coturn`` on debian, which worked fine. I set up the realm as turn.mydomain.com, and, had letsencrypt make a certificate for that domain. I was not sure if I should use the same certificates as my matrix server is using, on matrix.mydomain.com. 

It appears to be working, but, I'm unsure how to prove it. If someone can shed some light, I'll edit again to improve further.

**Comment by erikjohnston** [comment]
@RickCogley Thanks for this! You do seem to have managed to introduce some spurious white space changes in the PR though, any chance they could get removed?

**Comment by RickCogley** [comment]
@erikjohnston hi - I made a patch here: https://github.com/matrix-org/synapse/pull/899

**Comment by RickCogley** [comment]
Closing; Cleaned up in: https://github.com/matrix-org/synapse/pull/900

**Pull request closed without merging**
