### PR TITLE
Add m.id_access_token flag

### LINKED ISSUE #5927: Add a m.id_access_token flag to unstable_features
For https://github.com/matrix-org/synapse/issues/5786#issuecomment-523879040

### PR DESCRIPTION
**Pull request by anoadragon453**
Adds a flag to `/versions`' `unstable_features` section indicating that this Synapse understands what an `id_access_token` is, as per https://github.com/matrix-org/synapse/issues/5927#issuecomment-523566043

Fixes #5927

### CODE REVIEW

**Comment by richvdh** [comment]
(could you link to the PR(s) which added the relevant support, for future reference?)

**Comment by jryans** [comment]
> (could you link to the PR(s) which added the relevant support, for future reference?)

For Riot Web at least, this was done in https://github.com/matrix-org/matrix-js-sdk/pull/1022.
For Riot iOS, work is in progress under https://github.com/vector-im/riot-ios/issues/2603.
For Riot Android, work has not yet happened yet under https://github.com/vector-im/riot-android/issues/3228.

**Comment by anoadragon453** [comment]
@richvdh Assume you want to wait for this to merge before MSC'ing happens?

**Comment by anoadragon453** [comment]
And speaking of which, the MSC has gone into FCP: https://github.com/matrix-org/matrix-doc/pull/2264

**Comment by richvdh** [comment]
> > (could you link to the PR(s) which added the relevant support, for future reference?)
> 
> For Riot Web at least, this was done in [matrix-org/matrix-js-sdk#1022](https://github.com/matrix-org/matrix-js-sdk/pull/1022).
> For Riot iOS, work is in progress under [vector-im/riot-ios#2603](https://github.com/vector-im/riot-ios/issues/2603).
> For Riot Android, work has not yet happened yet under [vector-im/riot-android#3228](https://github.com/vector-im/riot-android/issues/3228).

Thanks for this, but I was really looking for where the synapse support was added...

**Comment by anoadragon453** [comment]
Oh you mean where `id_server` has been made optional?

That would be inside of https://github.com/matrix-org/synapse/pull/5835

**Pull request merged**
