### PR TITLE
move parse_filter to synapse.api.filtering

### PR DESCRIPTION
**Pull request by krombel**
This is useful for deduplication. I am planning to use this
as well on the websocket-implementation so I try do deduplicate this
part.

Signed-Off-By: Matthias Kesler <krombel@krombel.de>

### CODE REVIEW

**Comment by hawkowl** [comment]
matrixbot: test this please

**Comment by erikjohnston** [comment]
@matrixbot retest this please

**Comment by clokep** [comment]
It looks like this has bitrotted. Is this still useful? I'm guessing it was to reduce the diff of #2388? Could you rebase this and we can try to get it in?

**Comment by erikjohnston** [comment]
Closing for now, but feel free to reopen if you rebase it :+1:

**Pull request closed without merging**
