### PR TITLE
Fetch keys directly before using trusted key servers

### LINKED ISSUE #6086: Fetch signing-keys directly from servers before falling back to the trusted_key_server
Currently we try fetching keys from the trusted_key_server before asking the server itself. We should reverse this.

### PR DESCRIPTION
**Pull request by erikjohnston**
Fixes #6086.

### CODE REVIEW

**Comment by richvdh** [comment]
The thing to note about this, which I meant to write in #6086 but forgot, is that I worry about what it will do for the experience of joining a large room for the first time.

When you join a big room, we have to get hundreds of server keys. Currently that all goes in one big request to matrix.org. If we make it so that we go to the key server first... well, I expect they'll all time out and we'll end up going back to matrix.org anyway (and that failing too, because the cpu is still pinned).

**Comment by erikjohnston** [comment]
Ah, I guess in which case we should probably test this a bit

**Comment by army1349** [comment]
It seems to me that there should be no such thing as trusted key server in federated environment.

**Comment by richvdh** [comment]
we've decided to park this in favour of waiting for MSC1228 (for now, at least)

**Comment by hex-m** [comment]
> It seems to me that there should be no such thing as trusted key server in federated environment.

Actually the idea would be that there should be multiple. ([spec](https://spec.matrix.org/unstable/server-server-api/#retrieving-server-keys))

> It has the advantage of avoiding a single trust-root since each server is free to pick which notary servers they trust and can corroborate the keys returned by a given notary server by querying other servers.

**Pull request closed without merging**
