### PR TITLE
Allow ASes to opt out of rate limiting

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by Kegsay** [comment]
LGTM

**Comment by erikjohnston** [comment]
Is this rate limiting per user or per AS?

**Comment by Kegsay** [comment]
Each user that an AS creates are currently rate limited. There is no AS-specific rate limit. This PR removes the per-user rate limit.

**Comment by erikjohnston** [comment]
What's the use case?

**Comment by illicitonion** [comment]
https://matrix.org/jira/browse/BOTS-131

(Note that I'm actually shelving this PR until I make some fixes to Synapse, because it doesn't quite work as-is)

**Pull request closed without merging**
