### PR TITLE
fix SQL when searching all users

### PR DESCRIPTION
**Pull request by ara4n**

### CODE REVIEW

**Comment by ara4n** [comment]
apparently i never tested this and failed to spot that we dropped the `s` alias when searching all users, so adding a dummy one in.  Should fix https://github.com/matrix-org/synapse/issues/2801

**Comment by ara4n** [comment]
yup, agreed. just trying to fix it rapidly at this point. (just as the original PR was a rush job to try to impress a consulting customer who then promptly ignored it)

**Comment by romainchassaigne** [comment]
Thanks guys, i'll check that right now and tell you more

**Comment by richvdh** [comment]
sigh, the SQL in this isn't even valid

**Pull request merged**
