### PR TITLE
Improve tracebacks on exceptions

### PR DESCRIPTION
**Pull request by richvdh**
Use addErrback rather than try/catch to handle exceptions thrown by request
handlers, which improves the tracebacks.

### CODE REVIEW

**Comment by erikjohnston** [comment]
Is there a reason to do it like this rather than to try using the twisted logger?

**Comment by richvdh** [comment]
Good question. I failed to realise that was a thing that would help.

I'm not super-keen on using the twisted logger per se, because it means that we lose log categories etc. Nevertheless, it turns out that we can do what the twisted logger does to recover the original Failure, and 
get the best of both worlds.

**Comment by ara4n** [comment]
the other significant advantage of the twisted logger aiui is that it never blocks?

**Comment by richvdh** [comment]
that's #1727, and as I said there, there are other solutions to that problem.

**Pull request merged**
