### PR TITLE
Regarding allowing guest users to access the TURN server login info

### PR DESCRIPTION
**Pull request by magiccpp1**
Hi , 

we would like to allow the guest users to access the TURN server login info, please review the minor change on voip.py. thanks.

### CODE REVIEW

**Comment by richvdh** [comment]
@matrixbot: ok to test

**Comment by ara4n** [comment]
[cue huge debate over security implications of letting guests relay traffic via TURN if they haven't completed a captcha]

**Comment by ara4n** [comment]
The conclusions here were:
 * Yes, it's a slight security risk to let guests relay traffic via TURN
 * One can mitigate it a bit by turning off TCP-over-TURN relaying (#2010), and adding in application layer filtering (#2009), and configuring per-user quotas for TURN streams
 * However, it's desirable to avoid VoIP being flakey as hell for guests.

I've documented the security implications and made this a configurable setting, and PR'd it as #2010, which supersedes this one.  Thanks for bringing this into the spotlight! :)

**Comment by Rugvip** [comment]
Ok, thanks :) And just to fix some confusion, the PR is #2011, not #2010

**Comment by ara4n** [comment]
oops, thanks; fixed

**Pull request closed without merging**
