### PR TITLE
Fix hiding devices names over federation

### PR DESCRIPTION
**Pull request by aaronraimist**
Follow up to https://github.com/matrix-org/synapse/pull/9945. Turns out, while that PR appears to work most of the time there is one more spot where device names can be sent over federation.

I also noticed all these blank `org.matrix.opentracing_context` lines while I was debugging why my first PR wasn't working. I assume those don't need to be there unless opentracing is enabled so I also prevented those from being sent if they were blank.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by erikjohnston** [comment]
Did you want review of this, or is it still a WIP?

**Comment by aaronraimist** [comment]
It is still WIP but I think I'm going to need some help to finish it.

I tested this patch locally using the demo federation script and it seemed to work. But then I installed it on my server and device names were still being shared so this PR must not have fixed it. I haven't been able to figure out how the device names are being shared. I asked in `#synapse-dev:matrix.org` a few days ago but it got lost.

**Comment by erikjohnston** [comment]
Shout if/when this is ready for review :slightly_smiling_face:

**Comment by squahtx** [comment]
> I tested this patch locally using the demo federation script and it seemed to work. But then I installed it on my server and device names were still being shared so this PR must not have fixed it. I haven't been able to figure out how the device names are being shared. I asked in `#synapse-dev:matrix.org` a few days ago but it got lost.

Does the PR work now? I'm missing some context here.

**Comment by aaronraimist** [comment]
@squahtx context is that I still have not had time to take another look and this PR still probably does not fix 100% of the places where devices names can leak. However this PR is better than nothing since it definitely leaks without this PR and [this feature is being turned on by default in 1.59.0rc1](https://github.com/matrix-org/synapse/releases/tag/v1.59.0rc1).

Unless someone else is able to put in some time to figure out all of the places where device names can leak then I would say just merge this and try to get it in to v1.59.0 so the feature at the top of the release notes is at least a bit more reliable.

Otherwise if this can't get in to v1.59.0, I would recommend postponing hiding device names over federation by default until someone has time to investigate it further.

Discussed at https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$A0Fo6Y5TQgS_mboU_QErLzehgW1xE9UE0hVcxQVeSUA?via=matrix.org&via=element.io&via=vector.modular.im

**Review by squahtx — APPROVED** [review]
Thanks for the explanation! I agree that it makes sense to land this fix as-is. I've filed #12750 to track the leakiness.

As part of future work, we could look into automated testing for the option. I also wonder if it would be more appropriate for the logic to sit in a higher layer than the data store.

LGTM

**Comment by squahtx** [comment]
CI seems to be stuck from a year ago. Could you merge in the latest develop or a dummy commit to give it a kick?

**Review by squahtx — CHANGES_REQUESTED** [review]
Merging in the latest develop branch has revealed a handful of test failures unfortunately.
We'll want to investigate and fix them before merging.

**Comment by DMRobertson** [comment]
There is one failing sytest `Can query remote device keys using POST after notification` and one known flakey complement test. Otherwise no complaints.

**Comment by DMRobertson** [comment]
I think this should pass (modulo complement flakes) with https://github.com/matrix-org/sytest/pull/1307.

**Comment by anoadragon453** [comment]
Note that this does not look to solve https://github.com/matrix-org/synapse/issues/13114 (tested manually).

**Comment by DMRobertson** [comment]
> Note that this does not look to solve #13114 (tested manually).

I'll update the changelog to reflect this.

**Pull request merged**
