### PR TITLE
Remove tests/utils.py from mypy's exclude list

### PR DESCRIPTION
**Pull request by anoadragon453**
Replaces #11349.

Not many changes needed to do this these days compared to back then. Let's finish it off!

### CODE REVIEW

**Comment by DMRobertson** [comment]
There is also https://github.com/matrix-org/synapse/pull/13028 which I seem to have forgotten about

**Comment by anoadragon453** [comment]
@DMRobertson huh! I'm happy to close this PR if you think #13028 will be pushed forwards soon. It seems to do mostly everything here and more.

I am interested in whether you think `db_conn.autocommit = True` -> `db_engine.attempt_to_set_autocommit(db_conn, autocommit=True)` is valuable, over typecasting `db_conn` to `psycopg2.extensions.connection`. This PR proposes the former.

**Comment by DMRobertson** [comment]
> I am interested in whether you think `db_conn.autocommit = True` -> `db_engine.attempt_to_set_autocommit(db_conn, autocommit=True)` is valuable, over typecasting `db_conn` to `psycopg2.extensions.connection`. This PR proposes the former.

I don't have a strong opinion here (other than my previously-expressed Opinion that I don't want us to be reinventing a library that abstracts over database drivers when e.g. sqlalchemy core exists).

In fact, since we're not using very much of psycopg2 here, the casts aren't getting us much compared to `db_engine.attempt_to_set_autocommit`. I'd be happy to accept this and rebase/merge #13159 on top afterwards.

**Comment by anoadragon453** [comment]
Roger!

**Review by squahtx — APPROVED** [review]
lgtm!

**Comment by DMRobertson** [comment]
> I'd be happy to accept this and rebase/merge #13028 on top afterwards.

I'm gonna merge this and start that rebase now.

**Pull request merged**
