### PR TITLE
Some small fixes for #4594, #4842, #3715

### PR DESCRIPTION
**Pull request by jo-so**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#changelog)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

Signed-off-by: Jörg Sommer <joerg@jo-so.de>

### CODE REVIEW

**Comment by jo-so** [comment]
I've rebased my changes on the *develop* branch, but I don't know how to change the upstream branch of this pull-request.

**Comment by jo-so** [comment]
Found it 🙂

**Comment by richvdh** [comment]
Before you go too much further on this: would you mind putting different fixes in different PRs? Sorry I know it's a bit of a pain but it will make it much easier to review and manage.

**Comment by jo-so** [comment]
Do I have to create separate changelog entries for these pull requests? Is
it really worth for these small commits?

**Comment by jo-so** [comment]
I open new pull requests each with a single commit.

**Pull request closed without merging**
