### PR TITLE
Better error message when a remote resource uses invalid Content-Type

### PR DESCRIPTION
**Pull request by anoadragon453**
I noticed while working on #8421 that Synapse will raise a wrapped `RuntimeError` and 500 when a remote server responds to a request with a `Content-Type` header that Synapse was not expecting.

This is a tiny PR to change it to a 502 (Bad Gateway) instead, which I think makes more sense. I also spruced up the error message text a bit.

### CODE REVIEW

**Comment by erikjohnston** [comment]
I think we probably want to fix this by not returning a 500 in response to a `RequestSendFailed`?

**Comment by anoadragon453** [comment]
In this case the upstream server is at fault. What should we return instead to the user?

**Comment by erikjohnston** [comment]
I think we generally use 502 for such things. E.g.:

https://github.com/matrix-org/synapse/blob/6abb1ad0be1cde7cd414eee0e0a1f195462eb1bd/synapse/rest/media/v1/media_repository.py#L387-L394

The general approach is that:

1. we don't know whether `SynapseError` is appropriate for what the caller is trying to do; and
2. we should always be handling `RequestSendError` when making http requests, as otherwise we'll be generating 500s and `ERROR` logs for situations which aren't bugs in the server.

**Comment by anoadragon453** [comment]
@erikjohnston Thanks for the explanation! Fixing this will need to happen in other places then. For now I've changed this PR to just update the error message to be slightly clearer.

**Review by erikjohnston — APPROVED** [review]

**Pull request merged**
