### PR TITLE
Fix bug which caused rejected events to be stored with the wrong room state 

### LINKED ISSUE #6289: room state is persisted incorrectly for rejected events
I think we're persisting rejected events with the wrong state_group. Need to investigate a bit more.

### PR DESCRIPTION
**Pull request by richvdh**
The problem here was the code in `StateStore` which assumed that `prev_group` gave the state before the event being persisted. Whilst this may (sometimes) have been true for state events, it was *never* true for message events.

I'm not entirely sure if this is the best way to fix it, but the general idea is to rewrite `compute_event_context` to ensure that we always have a state group for the state before the event being persisted (and to store it in a new field in the `EventContext`). That also allows us to rewrite it to reduce a bunch of duplication between the code paths.

Fixes #6289.

This PR builds on #6319.

### CODE REVIEW

**Comment by erikjohnston** [comment]
Do we have any unit tests for `compute_event_context`?

**Comment by richvdh** [comment]
> Do we have any unit tests for compute_event_context?

there are a bunch in https://github.com/matrix-org/synapse/blob/develop/tests/test_state.py.

I guess I know where that question is leading...

**Comment by erikjohnston** [comment]
> > Do we have any unit tests for compute_event_context?
> 
> there are a bunch in https://github.com/matrix-org/synapse/blob/develop/tests/test_state.py.
> 
> I guess I know where that question is leading...

Just adding some checks for the new fields in those tests would be good :innocent:

**Comment by richvdh** [comment]
tests (and a lying docstring) updated in ba3a5e8

**Pull request merged**
