### PR TITLE
Populate synapse_federation_client_sent_pdu_destinations:count again

### LINKED ISSUE #3360: synapse_federation_client_sent_pdu_destinations:count no longer populated
The metric appears to have gone missing as of 0.31.0

### PR DESCRIPTION
**Pull request by hawkowl**
Fixes #3360

### CODE REVIEW

**Comment by hawkowl** [comment]
@turt2live could you check if this works on your homeserver? :)

**Comment by turt2live** [comment]
I'll try it out today/tonight (MDT). Thanks for looking into it!

**Comment by turt2live** [comment]
@hawkowl This appears to publish the wrong metric, although if it shows up in the changelog as a loud change that is fine.

**Comment by turt2live** [comment]
Looks good to me! Although I don't have the power to say that and have it count as approval :p

**Comment by hawkowl** [comment]
Another one for you to rubber stamp, @richvdh  :)

**Pull request merged**
