### PR TITLE
Add 'event' result to 'context' endpoint

### PR DESCRIPTION
**Pull request by richvdh**
... because the context isn't much use without the event.

### CODE REVIEW

**Comment by richvdh** [comment]
retest this please

**Comment by erikjohnston** [comment]
The original reason for not including an event was that you generally would never see an event_id without the event.

Are there any doc PRs?

LGTM

**Comment by richvdh** [comment]
> The original reason for not including an event was that you generally would never see an event_id without the event.

heh. Obviously we're changing that.

> Are there any doc PRs?

Not yet. It's on my todo list.

**Comment by erikjohnston** [comment]
kul

**Pull request merged**
