### PR TITLE
Allow clients to supply access_tokens as headers

### PR DESCRIPTION
**Pull request by NegativeMjark**
Clients can continue to supply access tokens as query parameters
or can supply the token as a header:

   Authorization: Bearer <access_token_goes_here>

This matches the ouath2 format of
https://tools.ietf.org/html/rfc6750#section-2.1

### CODE REVIEW

**Comment by ara4n** [comment]
what clients are you expecting to be using this, btw?

**Comment by erikjohnston** [comment]
LGTM, other than tests.

**Comment by NegativeMjark** [comment]
> what clients are you expecting to be using this, btw

None at the moment. I was thinking of hacking up the JS client to use it at somepoint.

**Comment by richvdh** [comment]
I appreciate this expands the scope significantly, but if we're going so far as to move the access token into headers, perhaps it's a good time to consider making the access token into a session key and using it to sign requests (per https://www.ietf.org/archive/id/draft-ietf-oauth-v2-http-mac-05.txt) instead of sending the whole thing back on each request?

**Pull request merged**
