### PR TITLE
Fix #12880 : notifications stop to work if last read event has been purged in a room

### LINKED ISSUE #12880: Push notifications stop working when a history purge deletes the event a read receipt is pointing at
### Description

We have a matrix homeserver which is configured without using additional workers. When the default message retention policy is on, and after the purge job took place, users stop to receive push notifications until they enter a room and send a message
### Steps to reproduce

- setup matrix homeserver from synapse docker container;
- turn on message retention policy in```hemoserver.yaml``` file:
```retention:
  # The message retention policies feature is disabled by default. Uncomment the
  # following line to enable it.
  #
  enabled: true

  # Default retention policy. If set, Synapse will apply it to rooms that lack the
  # 'm.room.retention' state event. Currently, the value of 'min_lifetime' doesn't
  # matter much because Synapse doesn't take it into account yet.
  #
  default_policy:
    min_lifetime: 1m
    max_lifetime: 2d
```
- write encrypted messages from user A to user B in room R. Receive push notifications as expected. Server logs for 'normal' behaviour:
```synapse_1         | 2022-05-26 07:00:53,195 - synapse.access.http.8008 - 427 - INFO - PUT-2030 - ::ffff:172.31.0.4 - 8008 - {@user_a:my.homeserver.com} Processed request: 0.049sec/0.004sec (0.006sec, 0.001sec) (0.001sec/0.004sec/4) 59B 200 "PUT /_matrix/client/r0/rooms/!XYwqVywzUXnTMmIwvf:my.homeserver.com}/send/m.room.encrypted/48729b0d-8506-4c5f-89cf-f257286d4ee3 HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
synapse_1         | 2022-05-26 07:00:53,213 - synapse.push.httppusher - 192 - INFO - httppush.process-15 - Processing 1 unprocessed push actions for @user_b:my.homeserver.com}/com.chatApp/AAAA:XXXX starting at stream_ordering 24659
synapse_1         | 2022-05-26 07:00:53,222 - synapse.access.http.8008 - 427 - INFO - GET-2025 - ::ffff:172.31.0.4 - 8008 - {@user_a:my.homeserver.com} Processed request: 7.244sec/0.001sec (0.008sec, 0.002sec) (0.006sec/0.010sec/3) 1352B 200 "GET /_matrix/client/r0/sync?since=s24659_46789_0_25324_1_194_8725_1775_1&timeout=45000 HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
synapse_1         | 2022-05-26 07:00:53,230 - synapse.access.http.8008 - 427 - INFO - GET-2026 - ::ffff:172.31.0.4 - 8008 - {@suer_b:homeserver.com} Processed request: 7.136sec/0.001sec (0.009sec, 0.001sec) (0.011sec/0.016sec/5) 1296B 200 "GET /_matrix/client/r0/sync?since=s24659_46789_0_25324_1_194_8725_1775_1&timeout=45000 HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
synapse_1         | 2022-05-26 07:00:53,328 - synapse.http.client - 442 - INFO - httppush.process-15 - Received response to POST https://sygnal-dev.my.homeserver.com/_matrix/push/v1/notify: 200
synapse_1         | 2022-05-26 07:00:53,547 - synapse.access.http.8008 - 427 - INFO - GET-2031 - ::ffff:172.31.0.4 - 8008 - {@user_b:my.homeserver.com} Processed request: 0.013sec/0.001sec (0.006sec, 0.000sec) (0.001sec/0.007sec/4) 883B 200 "GET /_matrix/client/r0/rooms/!XYwqVywzUXnTMmIwvf:my.homeserver.com/event/$otYFwSkMlcAr-K3GpxeL5T8d1lMHEf6262p22gtVMd4 HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
```
- The DB purge process seem to go as expected, no visible errors seem to occur in logs:
```
synapse.handlers.pagination - 227 - INFO - purge_history_for_rooms_in_range-28 - [purge] Attempting to purge messages in room !XYwqVywzUXnTMmIwvf:matrix-dev.kryptr.li
synapse_1         | 2022-05-26 07:45:19,349 - synapse.storage.databases.main.purge_events - 229 - INFO - _purge_history-4926 - [purge] removing events from event_auth
synapse_1         | 2022-05-26 07:45:19,351 - synapse.storage.databases.main.purge_events - 162 - INFO - _purge_history-4927 - [purge] found 0 events before cutoff, of which 0 can be deleted
synapse_1         | 2022-05-26 07:45:19,352 - synapse.storage.databases.main.purge_events - 283 - INFO - _purge_history-4925 - [purge] updating room_depth to 0
synapse_1         | 2022-05-26 07:45:19,354 - synapse.storage.databases.main.purge_events - 168 - INFO - _purge_history-4927 - [purge] Finding new backward extremities
synapse_1         | 2022-05-26 07:45:19,356 - synapse.storage.databases.main.purge_events - 124 - INFO - _purge_history-4928 - [purge] looking for events to delete
synapse_1         | 2022-05-26 07:45:19,357 - synapse.storage.databases.main.purge_events - 181 - INFO - _purge_history-4927 - [purge] replacing backward extremities: []
synapse_1         | 2022-05-26 07:45:19,358 - synapse.storage.databases.main.purge_events - 194 - INFO - _purge_history-4927 - [purge] finding state groups referenced by deleted events
synapse_1         | 2022-05-26 07:45:19,359 - synapse.storage.databases.main.purge_events - 206 - INFO - _purge_history-4927 - [purge] found 0 referenced state groups
synapse_1         | 2022-05-26 07:45:19,359 - synapse.storage.databases.main.purge_events - 210 - INFO - _purge_history-4927 - [purge] removing events from event_to_state_groups
synapse_1         | 2022-05-26 07:45:19,361 - synapse.storage.databases.main.purge_events - 229 - INFO - _purge_history-4926 - [purge] removing events from event_edges
synapse_1         | 2022-05-26 07:45:19,361 - synapse.storage.databases.main.purge_events - 229 - INFO - _purge_history-4927 - [purge] removing events from events
synapse_1         | 2022-05-26 07:45:19,362 - synapse.storage.databases.main.purge_events - 229 - INFO - _purge_history-4927 - [purge] removing events from event_json
synapse_1         | 2022-05-26 07:45:19,363 - synapse.storage.databases.main.purge_events - 229 - INFO - _purge_history-4926 - [purge] removing events from event_forward_extremities
synapse_1         | 2022-05-26 07:45:19,363 - synapse.storage.databases.main.purge_events - 229 - INFO - _purge_history-4927 - [purge] removing events from event_auth
synapse_1         | 2022-05-26 07:45:19,363 - synapse.storage.databases.main.purge_events - 229 - INFO - _purge_history-4926 - [purge] removing events from event_reference_hashes
synapse_1         | 2022-05-26 07:45:19,364 - synapse.storage.databases.main.purge_events - 229 - INFO - _purge_history-4926 - [purge] removing events from event_relations
synapse_1         | 2022-05-26 07:45:19,365 - synapse.storage.databases.main.purge_events - 309 - INFO - _purge_history-4925 - [purge] done
```
- send a message from user A to user B after DB is purged. User B receives no notifications. Logs for those messages:
```
synapse_1         | 2022-05-26 07:56:16,220 - synapse.access.http.8008 - 427 - INFO - PUT-3128 - ::ffff:172.31.0.4 - 8008 - {@user_a:my.homeserver.com} Processed request: 0.074sec/0.004sec (0.004sec, 0.001sec) (0.001sec/0.005sec/4) 59B 200 "PUT /_matrix/client/r0/rooms/!XYwqVywzUXnTMmIwvf:matrix-dev.kryptr.li/send/m.room.encrypted/85fed1c4-ade1-4735-888e-8bdbff34462d HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
synapse_1         | 2022-05-26 07:56:16,235 - synapse.push.httppusher - 192 - INFO - httppush.process-30 - Processing 0 unprocessed push actions for @user_b:my.homeserver.com/com.myChatApp/AAA:XXXX starting at stream_ordering 24673
synapse_1         | 2022-05-26 07:56:16,237 - synapse.access.http.8008 - 427 - INFO - GET-3126 - ::ffff:172.31.0.4 - 8008 - {@user_a:my.homeserver.com} Processed request: 7.372sec/0.002sec (0.007sec, 0.001sec) (0.006sec/0.007sec/4) 1352B 200 "GET /_matrix/client/r0/sync?since=s24674_46856_0_25340_1_194_8725_1775_1&timeout=45000 HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
```
- User B logs into the app, sync with the server, but still do not receive any notifications.
- User B enters the chat. After that, synapse starts to push notifications to sygnal:
```
synapse_1         | 2022-05-26 10:52:07,952 - synapse.access.http.8008 - 427 - INFO - PUT-6256 - ::ffff:172.31.0.4 - 8008 - {@user_a:mt.homeserver.com} Processed request: 0.064sec/0.004sec (0.004sec, 0.002sec) (0.001sec/0.005sec/4) 59B 200 "PUT /_matrix/client/r0/rooms/!XYwqVywzUXnTMmIwvf:matrix-dev.kryptr.li/send/m.room.encrypted/194db016-4d33-4333-8a18-b0d043a3752e HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
synapse_1         | 2022-05-26 10:52:07,968 - synapse.access.http.8008 - 427 - INFO - GET-6249 - ::ffff:172.31.0.4 - 8008 - {@user_a:my.homeserver.com} Processed request: 11.750sec/0.001sec (0.005sec, 0.004sec) (0.009sec/0.005sec/4) 1352B 200 "GET /_matrix/client/r0/sync?since=s24678_46993_0_25342_1_194_8725_1775_1&timeout=45000 HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
synapse_1         | 2022-05-26 10:52:07,974 - synapse.access.http.8008 - 427 - INFO - GET-6250 - ::ffff:172.31.0.4 - 8008 - {@user_b:my.homeserver.com} Processed request: 11.661sec/0.001sec (0.005sec, 0.003sec) (0.005sec/0.012sec/4) 1296B 200 "GET /_matrix/client/r0/sync?since=s24678_46993_0_25342_1_194_8725_1775_1&timeout=45000 HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
synapse_1         | 2022-05-26 10:52:07,981 - synapse.push.httppusher - 192 - INFO - httppush.process-34 - Processing 1 unprocessed push actions for @user_b:my.homeserver.com/com.myApp/AAA:XXXXX starting at stream_ordering 24678
synapse_1         | 2022-05-26 10:52:08,077 - synapse.http.client - 442 - INFO - httppush.process-34 - Received response to POST https://sygnal-dev.my.homeserver.com/_matrix/push/v1/notify: 200
synapse_1         | 2022-05-26 10:52:08,274 - synapse.access.http.8008 - 427 - INFO - GET-6257 - ::ffff:172.31.0.4 - 8008 - {@user_b:my.homeserver.com} Processed request: 0.012sec/0.001sec (0.004sec, 0.001sec) (0.001sec/0.006sec/4) 883B 200 "GET /_matrix/client/r0/rooms/!XYwqVywzUXnTMmIwvf:matrix-dev.kryptr.li/event/$HTe3KFoTXDx7PLk2BmnJ-jDkKi0PAP-shwrOEj0nlnk HTTP/1.0" "okhttp/4.9.2" [0 dbevts]
```

### Version information

- **Homeserver**:

Homeserver is deployed inside VPN

If not matrix.org:

- **Version**:
- {
server_version: "1.59.1",
python_version: "3.9.13"
}:
- {
server_version: "1.53.0",
python_version: "3.8.12"
}:

- **Install method**:
via docker-compose file

- **Platform**:
Matrix ecosystem is deployed in docker containers via docker-compose. Container versions used: 
- [v1.59.1](https://hub.docker.com/layers/synapse/matrixdotorg/synapse/v1.59.1/images/sha256-b0be28073fa0e32df65e3938a7cfa419dc7a41aad44af165a9b65482eb1f5737?context=explore)
- [v1.53.0](https://hub.docker.com/layers/synapse/matrixdotorg/synapse/v1.53.0/images/sha256-2d6acbfc9c6ae225b68cd6a931513dbd4c0e4f6881237a2179b41d07ad5c32d4?context=explore)

### PR DESCRIPTION
**Pull request by laurent-treeb**
Fix #12880 : notifications stop to work if last read event has been purged in a room

Following this comment https://github.com/matrix-org/synapse/issues/12880#issuecomment-1141385913 that explains where the bug is,  i choose a third way to resolve by updating the "The second query gets all event_push_actions for rooms with no read receipts." by adding rooms that have a read receipt that pointing to purged event.

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [ ] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Review by DMRobertson — CHANGES_REQUESTED** [review]
This has a merge conflict. Can you resolve it?

**Comment by clokep** [comment]
Also -- please update the title and description with a bit of information of what this PR accomplishes and how it does it.

**Comment by laurent-treeb** [comment]
> This has a merge conflict. Can you resolve it?

Sorry no.  A big merge has been done in 1.62 with this merge : https://github.com/matrix-org/synapse/pull/13005

So the PR may be helpfull for someone who wants to override a Synapse server before the 1.62.

**Comment by clokep** [comment]
Closing as the author has stated they are not interested in continuing to work on this PR.

**Pull request closed without merging**
