### PR TITLE
add device signatures to device key query results

### PR DESCRIPTION
**Pull request by uhoreg**
fixes https://github.com/matrix-org/synapse/issues/6830

### CODE REVIEW

**Comment by turt2live** [comment]
I've tested this on my personal HS with @jryans (on matrix.org) as a victim. It appears to not work automatically, but when I rename a device it makes that device go green for him. To make myself completely green I had to rename all devices.

Is it possible to spawn a rate limited background update for those with cross signing to update device lists?

**Comment by erikjohnston** [comment]
@uhoreg could you walk through what the problem was and how this solves it? It'd be good to be able to write a sytest for this (which I'm happy to help with/do)

**Comment by uhoreg** [comment]
> It appears to not work automatically, but when I rename a device it makes that device go green for him. To make myself completely green I had to rename all devices.

Yes, this PR unfortunately doesn't fix the issue for devices that have already been signed.  It only fixes things for new or newly-signed devices (or renamed).  I haven't really thought much about how to fix old devices.

> @uhoreg could you walk through what the problem was and how this solves it? It'd be good to be able to write a sytest for this (which I'm happy to help with/do)

The issue is that cross-signing signatures were stored in a different table, and were supposed to be added when the device keys were fetched.  But this part was forgotten in two places (which were called when you asked for keys over federation, and when you sent notifications to federated servers).

An alternate way to fix this would be to move the de-JSON-ing and signature adding into the `_get_e2e_device_keys_txn` function, so that we don't need to have that replicated in three different places.

Sytest is at https://github.com/matrix-org/sytest/pull/795  Sorry I forgot to mention that earlier.

**Comment by erikjohnston** [comment]
This should have been merged to the release branch. I'm going to cherry pick it there now.

**Comment by dhopfm** [comment]
A heads-up to those coming here looking for ways to rename devices to fix cross-signing: I found this the fastest through the web app in the User Settings modal under "Security & Privacy": all device names can be double-clicked and edited. Just make sure to hit Enter after each change in order to apply it; simply leaving the field didn't have any effect.

**Pull request merged**
