### PR TITLE
Remove Jenkins & other old dev junk

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by ara4n** [comment]
deleting the copyright-maintaining scripts feels a bit savage; the bug is that we don't use them, not that they exist...

**Comment by ara4n** [comment]
likewise, the directory map, whilst stale, is surely still useful for noobs? (but could be moved into /docs)

**Comment by richvdh** [comment]
@erikjohnston the map is the thing that I most want to kill off here.

**Comment by hawkowl** [comment]
FWIW, the directory map is currently worse than nothing. If we want an explainer of what modules and folders are, we can put README.md's in them.

As far as the copyright scripter, it isn't of much use (plus, the copyright header per file is not really... useful, but that's another thing).

**Comment by richvdh** [comment]
jenkins/prepare_synapse.sh is used by `https://github.com/matrix-org/sytest/blob/develop/jenkins/sytest-sqlite.sh` btw

**Pull request merged**
