### PR TITLE
Declare support for Python 3.11

### PR DESCRIPTION
**Pull request by DMRobertson**
Closes https://github.com/matrix-org/synapse/issues/14601

See also https://github.com/matrix-org/synapse/issues/14601#issuecomment-1348741757

### CODE REVIEW

**Comment by clokep** [comment]
(I feel like that sentence should just say > 3.7 if that's what we declare programmatically, but won't bikeshed that here.)

**Comment by DMRobertson** [comment]
> (I feel like that sentence should just say > 3.7 if that's what we declare programmatically, 

I'm sympathetic to this. I also considered changing the metadata to `>=3.7.1,<3.12.0` but I suspect that's the kind of thing that might cause the packagers friction in the future.

> but won't bikeshed that here.)

I feel similarly. (:foot: :canned_food: :motorway:)

**Comment by clokep** [comment]
Ship it, we can improve it in the future. 👍

**Comment by katlol** [comment]
Hi, any plans to [bump the Docker version](https://github.com/matrix-org/synapse/blob/develop/docker/Dockerfile#L23)? Currently pinned 3.9.

**Pull request merged**
