### PR TITLE
Use sys.executable instead of hardcoded python. fixes #1161

### LINKED ISSUE #1161: Python executable hardcoded introduces error inside virtualenv
```
ubuntu@ubuntu-xenial:~/synapse$ /home/ubuntu/synapse/bin/python  bin/synctl start
Starting ...
/usr/bin/python: No module named synapse.app
error starting (exit code: 1); see above for logs
```

### PR DESCRIPTION
**Pull request by larroy**

### CODE REVIEW

**Comment by erikjohnston** [comment]
This looks sensible, thanks! Can you sign off as per the [CONTRIBUTING.rst](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off) please?

**Comment by larroy** [comment]
Ok. Do I have to do it for every contribution from now on?

**Comment by erikjohnston** [comment]
Yes, please, but it should be easy enough either by using git or adding it as a comment here.

**Comment by larroy** [comment]
I accept the contributing terms:

Signed-off-by: Pedro Larroy <pedro.larroy.lists@gmail.com>

**Comment by erikjohnston** [comment]
Thanks! Sorry for the delay in getting this merged!

**Pull request merged**
