### PR TITLE
Get CI to check PRs have been signed-off

### PR DESCRIPTION
**Pull request by DMRobertson**
Uses Half-Shot's action from
https://github.com/matrix-org/backend-meta/blob/release/v2/.github/workflows/sign-off.yml. I've set this up in the sliding sync repo and it seems to have worked well.

### CODE REVIEW

**Review by clokep — APPROVED** [review]
Seems reasonable to me. Is this waiting for anything?

**Comment by DMRobertson** [comment]
Just a review :)

**Comment by DMRobertson** [comment]
Oh, and a merge conflict to be resolved too, it seems.

**Comment by clokep** [comment]
> Just a review :)

FTR this is in draft still. 😄

**Comment by DMRobertson** [comment]
:facepalm: thanks, that'd be why GH wasn't showing me a big "merge this now" button.

**Pull request merged**
