### PR TITLE
Implement MSC4028: push all encrypted events.

### LINKED ISSUE #15847: Support MSC4028 (Push all encrypted events except for muted rooms)
### Description

The purpose of [MSC4028](https://github.com/matrix-org/matrix-spec-proposals/pull/4028) is to be able to support on mobile clients the "mentions-and-keywords-only" room notification setting in encrypted rooms. This MSC adds a new "server-default" **override** push rule (`.m.rule.encrypted_event`) in order to force the server to push all encrypted events to the registered client **except for muted room**. 

I request here to add this new "server-default" push rule with its unstable id `org.matrix.msc4028.encrypted_event`. Contrary to the stable push rule, this unstable one should not be enabled -> its `enabled` attribute must be `false`. Indeed we should not turn it on until the clients implementations are ready.

I listed [here](https://github.com/matrix-org/matrix-spec-proposals/blob/giomfo/push_encrypted_events/proposals/4028-push-all-encrypted-events-except-for-muted-rooms.md#server-side) the potential issues of this MSC server side. We talked about them in an internal discussion, the conclusion was:

> So calculating what to push and the unread counts (its the same process) is a big performance bottleneck currently when sending in large rooms. A bunch of optimisation has taken place to make that better, but its still quite expensive
I'm not so concerned about /sync, as we've mostly already done the work at that point

I would let the backend team use this issue or create new ones to handle any other dev related to this MSC.

### PR DESCRIPTION
**Pull request by clokep**
See [MSC4028](https://github.com/matrix-org/matrix-spec-proposals/pull/4028).

Fixes #15847

### CODE REVIEW

**Review by DMRobertson — COMMENTED** [review]
My gut reaction is that pushing _all_ encrypted events to clients sounds excessive and might mean the push gateway gets rate limited. But I have no actual data on that. Maybe this is what a mobile app with E2EE messaging has to do? (Are there any open source services like this (Signal?) we could compare to?)

Does this only do push-gateway push, or does it also mean that we'll send out emails to people with email notifications turned on every time they get an encrypted message?

Also: is it worth a test case for the new push rule? (Not sure if we test them individually?)

**Comment by clokep** [comment]
> My gut reaction is that pushing _all_ encrypted events to clients sounds excessive and might mean the push gateway gets rate limited. But I have no actual data on that. Maybe this is what a mobile app with E2EE messaging has to do? (Are there any open source services like this (Signal?) we could compare to?)

This sounds like feedback for the MSC, not the implementation.

> Does this only do push-gateway push, or does it also mean that we'll send out emails to people with email notifications turned on every time they get an encrypted message?

Hmm, I think this means we would end up sending emails too, which is not ideal. Again this might be good feedback for the MSC?

> Also: is it worth a test case for the new push rule? (Not sure if we test them individually?)

We don't usually test each base rule individually, but I can add one if you'd like. (Especially for really simple ones I'm unconvinced it is very useful TBH.)

**Comment by DMRobertson** [comment]
> We don't usually test each base rule individually, but I can add one if you'd like. (Especially for really simple ones I'm unconvinced it is very useful TBH.)

That's fair---just wanted to sanity check what the done thing here was.

**Comment by clokep** [comment]
I can move the feedback over to the MSC if you'd like.

**Comment by DMRobertson** [comment]
> I can move the feedback over to the MSC if you'd like.

Ahh, I left a minimum-effort block comment on the MSC just now.

**Review by DMRobertson — APPROVED** [review]
Happy that this implements the MSC.

**Comment by clokep** [comment]
> Happy that this implements the MSC.

I'm going to merge this for now, it is disabled by default so this shouldn't cause issues and we can take the concerns to the MSC?

**Pull request merged**
