### PR TITLE
Create index on user_ips in the background

### PR DESCRIPTION
**Pull request by richvdh**
user_ips is kinda big, so really we want to add the index in the background
once we're running. Replace the schema delta with one which will do that.

I've done this in a way that's reasonably easy to reuse as there a few other
indexes I need, and I don't suppose they will be the last.

### CODE REVIEW

**Comment by NegativeMjark** [comment]
LGTM apart from the test failures

**Comment by richvdh** [comment]
@NegativeMjark: please could you take a look at the hackery to fix the tests?

**Comment by NegativeMjark** [comment]
LGTM

**Comment by richvdh** [comment]
ta

**Pull request merged**
