### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by z3ntu**
**Don't merge yet, changes are party incorrect**
Fix typo and path to Dockerfile

### CODE REVIEW

**Comment by richvdh** [comment]
could you open the PR once you're ready for us to look at it?

**Comment by z3ntu** [comment]
@richvdh Should be ready now. (I hope github realizes I pushed to the branch when it gets reopened - otherwise I'll create a new PR)

**Comment by richvdh** [comment]
sorry, guess I jumped the gun. Apparently GH now won't let me reopen it. Could you make a new PR?

**Comment by richvdh** [comment]
(though please see CONTRIBUTING.rst before you do)

**Comment by z3ntu** [comment]
I hope #3778 is good :)

**Pull request closed without merging**
