### PR TITLE
Fixup media_storage_providers options comments

### PR DESCRIPTION
**Pull request by tristanlins**
Update the comments for the generated configuration.
Taken from line 46-48:

https://github.com/matrix-org/synapse/blob/9dfcf47e9bb323f0597ebf8f34a1bcc9f14a02a1/synapse/config/repository.py#L46-L48

### CODE REVIEW

**Comment by clokep** [comment]
@tristanlins Looks like this:
* Needs a news file added (see https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog)
* Regenerate the sample config by running: `scripts-dev/generate_sample_config`

**Comment by tristanlins** [comment]
@clokep What type of change might that be? A `bugfix` or a `doc` type?!

**Comment by clokep** [comment]
> @clokep What type of change might that be? A `bugfix` or a `doc` type?!

@tristanlins I think `doc` is fine.

**Comment by aaronraimist** [comment]
What is the difference between `media_storage_providers` and just setting `media_store_path`?

**Comment by tristanlins** [comment]
> What is the difference between `media_storage_providers` and just setting `media_store_path`?

Its documented here: https://github.com/matrix-org/synapse/blob/master/docs/media_repository.md
A description how the media storage system works can be found here: https://github.com/matrix-org/synapse/issues/7140#issuecomment-613467494

**Comment by tristanlins** [comment]
@clokep I'm sorry, but I need a little help. The checks are failing with an error that does not belong to my changes: `could not serialize access due to concurrent update` :fearful:

**Comment by clokep** [comment]
@tristanlins Might need to merge `develop` back into this branch? Otherwise, the builds might have done something weird and we'll kick them off again.

**Comment by tristanlins** [comment]
Thats a good point. My changes where based on master, not develop as adviced in the contribution guide :see_no_evil: 
I knew I had forgotten something. I actually wanted the PR to be rebased on develop a long time ago. :shushing_face:

**Comment by tristanlins** [comment]
One check still fails with "could not serialize access due to concurrent update" :cry:

**Comment by anoadragon453** [comment]
@tristanlins Apologies, that's just a flaky test that we need to fix. I've restarted the build and it should work fine this time :)

**Comment by clokep** [comment]
Thanks for improving those comments! 👍

**Pull request merged**
