### PR TITLE
docs: Add link to Matrix VoIP tester for turn-howto

### PR DESCRIPTION
**Pull request by rht**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by clokep** [comment]
@reivilibre Any issues with linking off to this? I'm not sure if you plan to keep it running, etc.

**Comment by reivilibre** [comment]
I'm happy for this link to be included but perhaps we could also include a link to the repository, https://github.com/matrix-org/voip-tester?

One day I'm somewhat hoping that the VoIP tester will get a home on matrix.org once it is improved, perhaps at that time we could also change the link :).

**Comment by richvdh** [comment]
I'm not quite sure if the voip tester is yet reliable enough to be linked here (see https://github.com/matrix-org/voip-tester/issues/20 for example. Also it gives spotty results on matrix.sw1v.org which I *think* I've set up right.)

**Comment by rht** [comment]
I can add a statement that says something along the line of not to rely 100% on the negative result.

I got this error
```
Error occurred during test: VoIPTesterError: M_UNKNOWN_TOKEN Invalid macaroon passed. undefined [Can't get TURN credentials from homeserver]
```

from a homeserver that has been configured with a working TURN server, where video and audio calls work.

**Comment by reivilibre** [comment]
This is very true, although the tool has some utility, there are still issues with it (and judging by the comments I received, more than I knew about).

@rht I think that means the access token you supplied is not valid. Nevertheless, I have opened an issue to get a better error message on that. https://github.com/matrix-org/voip-tester/issues/23

Looks like I'll need to find some time to work on this, which may take a while as it's a particularly hectic and draining time for me recently.

**Comment by rht** [comment]
> @rht I think that means the access token you supplied is not valid. 

I have used the exact same access token I specified in turnserver.conf and homeserver.yaml. What else could go wrong?

**Comment by reivilibre** [comment]
> > @rht I think that means the access token you supplied is not valid.
> 
> I have used the exact same access token I specified in turnserver.conf and homeserver.yaml. What else could go wrong?

You need a Matrix Client-Server API Access token, the kind you'd find after logging in to a client (in Riot/Web, you can look at Settings → Help & About → Access token: >click to reveal>.

The token in turnserver.conf is something different, for the homeserver to be able to create VoIP secrets. (I guess these might also be called access tokens? Can't remember. In any case, suppose it could do with clarifying since it's not obvious.)

**Comment by rht** [comment]
- I added the link to the repo and said that people can file bug reports there.
- I added caution about using the tester.

**Comment by rht** [comment]
@reivilibre aha, I see! I mistook "user id and password" and "access token" to be based on the nomenclature in turnserver.conf (i.e. the static-auth-secret and "user=username1:password1").

**Comment by reivilibre** [comment]
> @reivilibre aha, I see! I mistook "user id and password" and "access token" to be based on the nomenclature in turnserver.conf (i.e. the static-auth-secret and "user=username1:password1").

Yeah, I can see how that's possible, though I didn't think of it at the time.

**Review by richvdh — COMMENTED** [review]
lgtm. Thanks!

**Pull request merged**
