### PR TITLE
Return 401 for invalid access_token on logout

### LINKED ISSUE #2932: Logout returns 200 when given an invalid access_token
### Description

According to the specification for the [/logout endpoint](https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#post-matrix-client-r0-logout), it invalidates an **existing token**. However, when supplied an invalid/non-existent access_token (such as "42") it still returns a 200 status code.   

### Steps to reproduce

- Send a POST to /_matrix/client/r0/logout with an Authorization header containing an invalid access_token (e.g. "Bearer 42")
- Response is a 200 status code

Ideally this should respond with error code  M_UNKNOWN_TOKEN to provide a more verbose error

### LINKED ISSUE #2937: Consider the user_id alongside the access_token when no-oping /send
### Description

This is more of an issue for testing appservices, and likely doesn't affect real appservices as the libraries already handle incrementing the transaction. 

Appservices can use the `?user_id` query parameter to impersonate another user in their namespace. However, synapse doesn't consider this when checking to see if an event has already been sent. The easiest way to see this in action is to use the following two curl commands (assuming the appservice is registered, etc):

```bash
# Send 'Hello world' as @_test_one:domain.com with transaction ID `__TXNID__`
curl -X PUT -H "Content-Type: application/json" --data-binary '{"msgtype":"m.text","body":"Hello world"}' 'https://homeserver.org/_matrix/client/r0/rooms/!myroom:domain.com/send/m.room.message/__TXNID__?access_token=YourAppserviceAccessToken&user_id=@_test_one:domain.com

# Send 'Hello world' as @_test_two:domain.com with transaction ID `__TXNID__`
# The only thing that has changed is the user ID
curl -X PUT -H "Content-Type: application/json" --data-binary '{"msgtype":"m.text","body":"Hello world"}' 'https://homeserver.org/_matrix/client/r0/rooms/!myroom:domain.com/send/m.room.message/__TXNID__?access_token=YourAppserviceAccessToken&user_id=@_test_two:domain.com
```

Expected: two 'hello world' messages
Actual: only the first sender gets through, the second is no-oped

Tested with synapse 0.26.0

### PR DESCRIPTION
**Pull request by dklug**
Fixes #2932 

Returns errcode `M_UNKNOWN_TOKEN` upon invalid token.

### CODE REVIEW

**Comment by richvdh** [comment]
@matrixbot: test this please

**Comment by richvdh** [comment]
Any chance of a test in https://github.com/matrix-org/sytest/blob/develop/tests/13logout.pl ?

**Comment by CobaltCake** [comment]
May I suggest using `AuthError.code`, `AuthError.errcode`, and `AuthError.msg` instead of `401`, `"M_UNKNOWN_TOKEN"`, and `"Access Token unknown or expired"` respectively? This way, the correct values are returned when the token is both invalid and completely missing, and the correct HTTP status code of `403` is used.

**Comment by richvdh** [comment]
As I understand it:

401 is "I don't know who you are"
403 is "I know who you are, but you're not allowed to do what you're asking."

Invalid token is "I don't know who you are"

**Pull request merged**
