### PR TITLE
Fix typo in the login fallback javascript

### PR DESCRIPTION
**Pull request by babolivier**
This would cause the SSO login form to not show up, making it impossible to auth via SSO through the login fallback if SSO isn't the only authentication option the HS offers.

### CODE REVIEW

**Comment by richvdh** [comment]
when was this introduced? @anoadragon453 / @babolivier please can we get into the habit of recording that info in newsfiles?

**Comment by babolivier** [comment]
Woops, sorry. This was introduced in https://github.com/matrix-org/synapse/pull/7152 - which afaik hasn't been released yet, so I should even have used the same changelog file.

**Comment by richvdh** [comment]
ah right. Would you mind updating the changelog file directly on develop?

**Comment by babolivier** [comment]
Sure, done in https://github.com/matrix-org/synapse/commit/c11d24d48c2f0b0b57d70087e5659290b9ddd154

**Pull request merged**
