### PR TITLE
Add config option to auto-join new users to rooms

### PR DESCRIPTION
**Pull request by dbkr**
New users who register on the server will be dumped into all rooms in
auto_join_rooms in the config.

### CODE REVIEW

**Comment by turt2live** [comment]
ooi, how does this react with riot-bot?

**Comment by dbkr** [comment]
riot-bot is done on the client and creates a new room each time, so I guess will continue to be on the client side - other than that, they'll probably stay fairly separate.

**Comment by maxidor** [comment]
Could this be moved somewhere reachable by password providers? Else this is only available for users that directly register on the homeserver and not to users within LDAP on first login, etc.

**Comment by VectreUK** [comment]
+1 on what @maxidor said. I'm running Matrix/Riot in an environment where it would be very helpful to have these autojoin config options work with LDAP. For reference, I'm using the LDAP password providers method not MXISD.

**Comment by lockntross** [comment]
So auto-join rooms on registration is removed? 
I updated my docker file today. I was greeted with a weird static page [https://github.com/matrix-org/synapse/pull/4289]

Synapse's registration worked great. 
Riot is ok, but the signup page is not as mobile friendly -and- lacks the ability to auto-join new users to a room.
I've had to switch to eeacms's synapse docker... and I'm sure they're thinking the same thing I was. "What"

**Pull request merged**
