### PR TITLE
Handle local device list updates during partial join

### LINKED ISSUE #13891: Make outgoing device list tracking work after we partial-join
- [ ] To fix "`/keys/query` requests on a remote homeserver must not return stale data."
  - Store the current device list stream ID when we start a partial join
  - When we transition from partial to fully joined, send all device list updates in `device_list_changes_in_room` since we last joined the room (by referring to the recorded stream ID) for the room to all servers that are either:
       1. are in the room; or 
       2. have had a membership change between the state at the initial join and the new current state.

_Originally posted by @erikjohnston in https://github.com/matrix-org/synapse/issues/12993#issuecomment-1253785129_

### PR DESCRIPTION
**Pull request by erikjohnston**
Fixes #13891

### CODE REVIEW

**Comment by DMRobertson** [comment]
(sorry I haven't found the time for this; thanks for picking it up)

**Comment by erikjohnston** [comment]
> (sorry I haven't found the time for this; thanks for picking it up)

Np! I realised it was quite similar to point #3 in the end, so turned out to be easy enough to bolt on.

Thanks for adding the columns to the table!

**Comment by squahtx** [comment]
The associated complement tests are at https://github.com/matrix-org/complement/pull/474 and they all pass with this PR.

**Review by squahtx — APPROVED** [review]
LGTM! The calculation of hosts to send updates to looks sound.

**Pull request merged**
