### PR TITLE
Add a unique index to `state_group_edges` to prevent duplicates being accidentally introduced and the consequential impact to performance.

### LINKED ISSUE #11779: The `state_group_edges` table doesn't have a unique index; can severely impact `WITH RECURSIVE state(state_group) AS ...` query performance if duplicates are somehow introduced
This is similar to, but not the same as, #10301.

The `state_group_edges` table doesn't have a unique index, so it's 'easy' to introduce duplicate rows e.g. by restoring a backup twice (or potentially even due to pure bugs in Synapse).

This query as part of `_get_state_groups_from_groups`:

```sql
WITH RECURSIVE state(state_group) AS ( VALUES(3405820::bigint) UNION ALL SELECT prev_state_group FROM state_group_edges e, state s WHERE s.state_group = e.state_group ) SELECT DISTINCT ON (type, state_key) type, state_key, event_id FROM state_groups_state WHERE state_group IN ( SELECT state_group FROM state ) ORDER BY type, state_key, state_group DESC
```

would be seriously slowed down by the presence of duplicate rows (I seem to think someone mentioned it would return the square of the number of rows it would usually, but I haven't verified that and I can't find that again to reference it).

It may be worth adding a unique index or perhaps having an SQL snippet that administrators can run to recover from this (though I would favour the former — make it hard to do in the first place).

As an aside: `state_group_edges` can potentially contain loops but that shouldn't arise from recovering backups (as far as I know) and it's not so easy to do something about — but worth bearing in mind that it would cause the query to go forever.

### PR DESCRIPTION
**Pull request by reivilibre**
Fixes #11779.

To do:

- [ ] decide if we want to note in the upgrade notes, along with a query to remove duplicates if you've been bitten (considering the issue causes shocking performance and we have normally dealt with it as a support capacity, we could just deal with the support queries again)
- [ ] decide if this is the right approach.

### CODE REVIEW

**Comment by squahtx** [comment]
Out of interest, what was causing the background update error in CI?

**Comment by squahtx** [comment]
\> decide if we want to note in the upgrade notes, along with a query to remove duplicates if you've been bitten (considering the issue causes shocking performance and we have normally dealt with it as a support capacity, we could just deal with the support queries again)

Presumably the background update will fail if there are duplicates? I'm in favour of writing something in the upgrade notes to minimise the support load.

\> decide if this is the right approach
Are there any alternative approaches you have in mind?

**Comment by clokep** [comment]
(Removing from the review queue as @squahtx wrote the exact questions I had!)

**Comment by reivilibre** [comment]
> Out of interest, what was causing the background update error in CI?

My crime was putting the schema delta in the `main` database rather than the `state` database. Yes, that would blow up a SyTest and fill the disk, making it hard to debug :/.

> Presumably the background update will fail if there are duplicates? I'm in favour of writing something in the upgrade notes to minimise the support load.

Yeah, sounds reasonable to me. I will note here that these are the errors that will show up if it goes wrong:

```python
2022-05-19 11:08:17,496 - synapse.storage.background_updates - 623 - INFO - background_updates-0 - Adding index state_group_edges_unique_idx to state_group_edges
2022-05-19 11:08:17,497 - synapse.storage.background_updates - 282 - ERROR - background_updates-0 - Error doing update
Traceback (most recent call last):
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 280, in run_background_updates
    result = await self.do_next_background_update(sleep)
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 404, in do_next_background_update
    await self._do_background_update(desired_duration_ms)
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 447, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 624, in updater
    await self.db_pool.runWithConnection(runner)
  File "/home/rei/work/synapse/synapse/storage/database.py", line 927, in runWithConnection
    return await make_deferred_yieldable(
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/rei/work/synapse/synapse/storage/database.py", line 920, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 606, in create_index_sqlite
    c.execute(sql)
  File "/home/rei/work/synapse/synapse/storage/database.py", line 350, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/rei/work/synapse/synapse/storage/database.py", line 392, in _do_execute
    return func(sql, *args, **kwargs)
sqlite3.IntegrityError: UNIQUE constraint failed: state_group_edges.state_group, state_group_edges.prev_state_group
```
(^ SQLite3)

```python
2022-05-19 11:10:44,792 - synapse.storage.background_updates - 623 - INFO - background_updates-0 - Adding index state_group_edges_unique_idx to state_group_edges
2022-05-19 11:10:44,792 - synapse.storage.background_updates - 558 - DEBUG - background_updates-0 - [SQL] DROP INDEX IF EXISTS state_group_edges_unique_idx
2022-05-19 11:10:44,793 - synapse.storage.background_updates - 572 - DEBUG - background_updates-0 - [SQL] CREATE UNIQUE INDEX CONCURRENTLY state_group_edges_unique_idx ON state_group_edges (state_group, prev_state_group) 
2022-05-19 11:10:44,795 - synapse.storage.background_updates - 282 - ERROR - background_updates-0 - Error doing update
Traceback (most recent call last):
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 280, in run_background_updates
    result = await self.do_next_background_update(sleep)
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 404, in do_next_background_update
    await self._do_background_update(desired_duration_ms)
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 447, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 624, in updater
    await self.db_pool.runWithConnection(runner)
  File "/home/rei/work/synapse/synapse/storage/database.py", line 927, in runWithConnection
    return await make_deferred_yieldable(
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/home/rei/.cache/pypoetry/virtualenvs/matrix-synapse-0QZlT1cR-py3.10/lib/python3.10/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/rei/work/synapse/synapse/storage/database.py", line 920, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/home/rei/work/synapse/synapse/storage/background_updates.py", line 573, in create_index_psql
    c.execute(sql)
  File "/home/rei/work/synapse/synapse/storage/database.py", line 350, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/rei/work/synapse/synapse/storage/database.py", line 392, in _do_execute
    return func(sql, *args, **kwargs)
psycopg2.errors.UniqueViolation: could not create unique index "state_group_edges_unique_idx"
DETAIL:  Key (state_group, prev_state_group)=(2, 1) is duplicated.
```
(^ Postgres)

I'll make some notes in the upgrade notes.

> Are there any alternative approaches you have in mind?

https://github.com/matrix-org/synapse/issues/11779#issuecomment-1117520330 mentions another idea, which would supersede this table, but would be a 'pain'.
Accepting this PR doesn't impact us being able to do that in the future, though, so all in all it's not a major concern.

**Comment by reivilibre** [comment]
I've added some notes to the upgrade notes, included queries which I have tested locally on both SQLite and Postgres homeservers.

**Review by squahtx — APPROVED** [review]
lgtm!

**Pull request merged**
