### PR TITLE
Sanitize logging

### PR DESCRIPTION
**Pull request by erikjohnston**
Related to: [SYN-385](https://matrix.org/jira/browse/SYN-385) and [SYN-388](https://matrix.org/jira/browse/SYN-388)

- [x] Log outgoing requests that use `synapse.http.client.SimpleHttpClient`
- [x] Remove `access_token`'s from logs:
  - [x] `synapse.http.server`
  - [x] `SynapseSite`'s request's `__repr__` and `__str__`
  - [x] ~~`insert_client_ip`  (`DEBUG` logging)~~ SQL logging is a generic problem here. See comments below
  - [x] `synapse.rest.client.v1.transactions` `{get,store}_response`  (`DEBUG` logging)
- [x] Log the authenticated entity if one is associated with a request, e.g. the server or user.
- [x] Improve request logging and remove twisted's logging:
  - [x] IP modulo `X-Forwarded-For`
  - [x] Query params (excluding `access_token`)
  - [x] HTTP version
  - [x] Response length

### CODE REVIEW

**Comment by erikjohnston** [comment]
This pulls in #185

**Comment by erikjohnston** [comment]
`DEBUG` level logging includes personal information, like `access_token`'s and  message contents. Should these instead be logged in some sort of `TRACE` level, though python logging doesn't have such a concept.

**Comment by erikjohnston** [comment]
This is ready for review: @NegativeMjark ?

**Comment by NegativeMjark** [comment]
LGTM

**Pull request merged**
