### PR TITLE
Import mock from unittest.

### PR DESCRIPTION
**Pull request by clokep**
These tests fail for me locally with `builtins.ModuleNotFoundError: No module named 'mock'`

I'm not sure why they're working in CI since we shouldn't be install `mock` anymore.

This also adds a license header. Broken from #11306.

### CODE REVIEW

**Comment by erikjohnston** [comment]
> I think this is having some issues with async mocks. I don't understand how the original code remotely worked without `mock` installed though?

We added `mock` back in in #11306 as `mock` backports support for `AsyncMock`?

**Comment by clokep** [comment]
> > I think this is having some issues with async mocks. I don't understand how the original code remotely worked without `mock` installed though?
> 
> We added `mock` back in in #11306 as `mock` backports support for `AsyncMock`?

That's really confusing -- we put a bunch of work into removing this dependency. 😢 

Anyway, it would be great to shout that dependencies updated!

**Comment by erikjohnston** [comment]
Ah, sorry I didn't realise we'd done that :slightly_frowning_face:   TBH it was mostly me raging at the amount of faff to work around lack of async utils in py3.6

**Comment by clokep** [comment]
For cross referencing -- see #9772.

**Comment by clokep** [comment]
Oh hmm, I guess we should still grab the license header here. I'll do a separate PR.

**Pull request closed without merging**
