### PR TITLE
Fix incorrect logcontexts after a Deferred was cancelled

### PR DESCRIPTION
**Pull request by richvdh**
... mostly because I wanted to check it did the right thing with logcontexts.

### CODE REVIEW

**Comment by erikjohnston** [comment]
Although the new test has failed on one of the runs...

**Comment by richvdh** [comment]
it's found a bug in an old version of twisted, I think...

**Comment by richvdh** [comment]
@erikjohnston ptal

**Comment by richvdh** [comment]
yes.

**Pull request merged**
