### PR TITLE
Remove local threepids on account deactivation

### PR DESCRIPTION
**Pull request by anoadragon453**
Threepids bound to identity servers were being removed from a user's account on deactivation, but not local threepids. Probably best to clean these up.

### CODE REVIEW

**Comment by erikjohnston** [comment]
Don't we want to just delete the local threepids from the DB rather than trying to unbind them?

**Comment by erikjohnston** [comment]
And does `store.user_delete_threepid` delete the right thing?

**Comment by anoadragon453** [comment]
> Don't we want to just delete the local threepids from the DB rather than trying to unbind them?

True, it is unnecessary/a privacy leak to ask IS' about it.

> And does `store.user_delete_threepid` delete the right thing?

I believe so, though perhaps we should also remove any pending 3PID validation sessions so a threepid can't be added after deactivation occurs.

**Comment by erikjohnston** [comment]
> > And does `store.user_delete_threepid` delete the right thing?
> 
> I believe so, though perhaps we should also remove any pending 3PID validation sessions so a threepid can't be added after deactivation occurs.

Yeah, we want to :fire: everything to do with the user

**Comment by anoadragon453** [comment]
> We should also remove any pending 3PID validation sessions so a threepid can't be added after deactivation occurs.

This looks more involved, so I'll do it in a separate PR.

**Pull request merged**
