### PR TITLE
config,handlers/_base: added homeserver config for what state is included in a room invite

### PR DESCRIPTION
**Pull request by Rugvip**
Related SPEC bug: https://matrix.org/jira/browse/SPEC-357

### CODE REVIEW

**Comment by illicitonion** [comment]
@matrixbot ok to test

**Comment by illicitonion** [comment]
@Rugvip LGTM, will merge if jenkins is happy

**Comment by Rugvip** [comment]
Needs https://github.com/matrix-org/synapse/pull/599

**Comment by Rugvip** [comment]
Actually wth, added that commit into this instead :p

**Comment by illicitonion** [comment]
This breaks our unit tests; can you throw in this patch?:

```diff
$ git diff
diff --git a/tests/utils.py b/tests/utils.py
index bf7a31f..11d9acb 100644
--- a/tests/utils.py
+++ b/tests/utils.py
@@ -50,6 +50,7 @@ def setup_test_homeserver(name="test", datastore=None, config=None, **kargs):
         config.macaroon_secret_key = "not even a little secret"
         config.server_name = "server.under.test"
         config.trusted_third_party_id_servers = []
+        config.room_invite_state_types = []
 
     if "clock" not in kargs:
         kargs["clock"] = MockClock()
```

**Comment by ara4n** [comment]
Before merging this, we should update the spec to actually articulate what's allowed to go into an invite and not.  Agreed that it'd be nice to have this extensibility, but want to do so without creating a spam vector or encouraging fragmentation.  Created a https://matrix.org/jira/browse/SPEC-357 spec bug first.

**Comment by erikjohnston** [comment]
@Rugvip Can you fix the merge conflicts?

**Comment by erikjohnston** [comment]
LGTM

**Pull request merged**
