### PR TITLE
Pass str to twisted's IReactorTCP

### PR DESCRIPTION
**Pull request by DMRobertson**
This follows a correction made in twisted/twisted#1664.

Until that change is in a twisted release, we'll have to ignore the type
of the `host` argument. I'll raise an issue to remind us to review the
issue in a few months' time.

### CODE REVIEW

**Comment by DMRobertson** [comment]
CI running at https://github.com/matrix-org/synapse/actions/runs/1266638362

**Comment by DMRobertson** [comment]
> CI running at https://github.com/matrix-org/synapse/actions/runs/1266638362

And mypy passed on that

**Review by clokep — APPROVED** [review]
Seems reasonable if tests pass.

**Comment by DMRobertson** [comment]
Unit tests are failing against postgres. Will take a look tomorrow.

**Comment by DMRobertson** [comment]
Sorry for force push. I accidentally added commits for #10906 to this branch and pushed here.

**Comment by DMRobertson** [comment]
Thanks @richvdh for spotting that last problem

**Comment by DMRobertson** [comment]
I forgot that the twisted trunk CI job doesn't run against pull requests. Started one manually [here](https://github.com/matrix-org/synapse/actions/runs/1286554435).

**Review by clokep — APPROVED** [review]

**Pull request merged**
