### PR TITLE
Queue events by room for persistence

### PR DESCRIPTION
**Pull request by erikjohnston**

### CODE REVIEW

**Comment by NegativeMjark** [comment]
Looks good, Do we need to do anything special to make the log contexts work?

**Comment by erikjohnston** [comment]
> Looks good, Do we need to do anything special to make the log contexts work?

*nyargh*

**Comment by erikjohnston** [comment]
@NegativeMjark I've done stuff.

**Comment by NegativeMjark** [comment]
LGTM

**Pull request merged**
