### PR TITLE
Upgrade to python 3.10 by default (#13234)

### PR DESCRIPTION
**Pull request by danger89**
See title.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Signed-off-by: Melroy van den Berg <melroy at melroy dot org>

Regards,
Melroy van den Berg

### CODE REVIEW

**Comment by DMRobertson** [comment]
There are a bunch of unrelated formatting changes here which I'd prefer to be a separate change (if included at all).

We wouldn't be willing to accept this until CPython 3.11 releases, which is expected [in October 2022](https://peps.python.org/pep-0664/#release-schedule) (per the policy described here https://github.com/matrix-org/synapse/issues/8674#issuecomment-719990241).

In the meantime, you can build a version of this image yourself as described here.

https://github.com/danger89/synapse/blob/7ad995a1a4f7a68c64e9fd7134bf89b941017990/docker/Dockerfile#L15

 I appreciate that's not as convenient (and won't apply to new releases) but it might give you a way forward for now.

```

**Comment by clokep** [comment]
I've removed this from the review queue per @DMRobertson's comments.

**Comment by richvdh** [comment]
let's close this for now - @danger89 if you'd like to open a new PR once 3.12 is out, that would be grand!

**Comment by DMRobertson** [comment]
I reopened this now that 3.11 is released, but it looks like there's a merge conflict here. I'll open a new PR with this change.

**Pull request closed without merging**
