### PR TITLE
Blacklist Local and remote users' homeservers remove a room from thei…

### PR DESCRIPTION
**Pull request by anoadragon453**
Related: https://github.com/matrix-org/synapse/issues/6932

### CODE REVIEW

**Comment by erikjohnston** [comment]
Is the test hard to fix?

**Comment by anoadragon453** [comment]
I'm not sure. I haven't investigated, but wanted to blacklist the test in the meantime to keep CI happy.

**Comment by anoadragon453** [comment]
After mulling it over, I think it might be a time waster to require context-switching to investigation before blacklisting a test, which might otherwise be breaking CI elsewhere.

I think our habit of not going back and unflaking tests might be the real problem. I'm not sure if you'd have much more state at the time of noticing the test being flaky versus investigating afterwards, especially if the test is unrelated to your changes.

**Comment by anoadragon453** [comment]
And as per our later discussion, we are going to do investigation on an issue before blacklisting.

**Comment by clokep** [comment]
Per the result of #6932 I don't think this is necessary anymore.

**Pull request closed without merging**
