### PR TITLE
Print complement failure results last

### PR DESCRIPTION
**Pull request by richvdh**
Since github always scrolls to the bottom of any test output, let's put the
failed tests last and hide any successful packages.

### CODE REVIEW

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/runs/8034427245?check_suite_focus=true handily demonstrates the results here

**Comment by richvdh** [comment]
though I wonder if it is rather ominously quiet in the case of a successful run: https://github.com/matrix-org/synapse/runs/8034427350?check_suite_focus=true

Maybe we should just print "tests run successfully" after a successful run?

Or: tee the json into a logfile. If the test run is successful, run `gotestfmt` again without the `-hide` option?

**Review by squahtx — APPROVED** [review]
lgtm!

**Comment by DMRobertson** [comment]
I previously tried to do something similar in #13180; this looks great

**Pull request merged**
