### PR TITLE
Use v3 endpoints for fallback auth (Matrix 1.1)

### PR DESCRIPTION
**Pull request by turt2live**
Untested, but no reason to believe this wouldn't work. Part of [Matrix 1.1](https://github.com/matrix-org/synapse/issues/11079) work, but not blocking.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by clokep** [comment]
Related to #11474, specifically, I think?

**Comment by turt2live** [comment]
Related, yes. I didn't run across them in my relatively quick checks against the v1.1 feature set, so would recommend they be fixed in a future PR.

**Comment by babolivier** [comment]
I'm wondering if we don't want the v3 and r0 URLs coexist for a bit to give clients time to update their paths and to give users time to update their clients.

**Comment by reivilibre** [comment]
> I'm wondering if we don't want the v3 and r0 URLs coexist for a bit to give clients time to update their paths and to give users time to update their clients.

I'm not sure this is what this is getting at. It appears to be setting the URL for fallback auth to be `v3` rather than `r0`. The interaction is handled in a general-purpose web browser so clients have nothing to update.

(Please correct me if I'm wrong!)

**Comment by clokep** [comment]
Both URLs should work fine still, this just changes where Synapse redirects / point people too.

The only risk is that someone is block `v3` in their reverse proxy for some reason.

**Review by erikjohnston — APPROVED** [review]
Sounds like everyone thinks this is fine.

**Pull request merged**
