### PR TITLE
Fix mypy for platforms without epoll support.

### PR DESCRIPTION
**Pull request by clokep**
Follow-up to #11724 to fix mypy on macOS.

### CODE REVIEW

**Comment by clokep** [comment]
Without this change I get:

```
synapse/metrics/_reactor_metrics.py:38: error: Name "select.epoll" is not defined  [name-defined]
synapse/metrics/_reactor_metrics.py:74: error: Module "select" has no attribute "epoll"; maybe "poll"?  [attr-defined]
```

**Review by DMRobertson — COMMENTED** [review]
I think this means that `reveal_type(select.epoll)` will be `Any` on macos, if we were to run mypy under not-linux?

Slightly unsettled at the idea that the typechecking result is implicitly dependent on your platform, but this is Python I suppose (and maybe we have that problem anyway with the choice of python version?).

Typeshed seems to [do something similar](https://github.com/python/typeshed/blob/fe6233a8c3d4ca708a0da2ab281a20fbd148215c/stdlib/select.pyi#L102-L103).

I'd like to double check that the `'type: ignore` doesn't lose information when we run mypy under linux (in particular, under CI). Let me checkout the PR...

**Comment by DMRobertson** [comment]
> I'd like to double check that the `'type: ignore` doesn't lose information when we run mypy under linux

On my machine:

```
dmr on titan in synapse on  clokep/macos-mypy via 🐍 v3.10.1 (env) 
2022-01-19 16:29:44 ✔  $ mypy
synapse/metrics/_reactor_metrics.py:47: note: Revealed type is "select.epoll"

dmr on titan in synapse on  clokep/macos-mypy via 🐍 v3.10.1 (env) took 3s 
2022-01-19 16:30:33 ✔  $ git diff -- synapse
  diff --git a/synapse/metrics/_reactor_metrics.py b/synapse/metrics/_reactor_metrics.py
  index f38f79831..cf1f69536 100644
  --- a/synapse/metrics/_reactor_metrics.py
  +++ b/synapse/metrics/_reactor_metrics.py
  @@ -44,7 +44,7 @@ def poll(self, *args, **kwargs) -> List[Tuple[int, int]]:  # type: ignore[no-unt
           # how long it takes to run everything in the reactor - ie, how long anything
           # waiting for the next tick will have to wait.
           tick_time.observe(time.time() - self.last_polled)
  -
  +        reveal_type(self._poller)
           ret = self._poller.poll(*args, **kwargs)
   
           self.last_polled = time.time()
```

So I think this LGTM!

**Review by DMRobertson — APPROVED** [review]
It might be worth a comment to justify the type-ignore, noting that `select.epoll` is only available on Linux? Maybe that's overkill. I'll leave it to your discretion!

**Comment by clokep** [comment]
> It might be worth a comment to justify the type-ignore, noting that `select.epoll` is only available on Linux? Maybe that's overkill. I'll leave it to your discretion!

I think it is pretty implicit from the attribute / import checks in those methods.

**Pull request merged**
