### PR TITLE
Set `no_implicit_optional = True`

### PR DESCRIPTION
**Pull request by ShadowJonathan**
cc @richvdh, because you spoke about this in `#synapse-dev`

Borne from #9682

Added `no_implicit_optional = True`, and fixed some subsequent lint errors.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

### CODE REVIEW

**Comment by clokep** [comment]
Looks pretty reasonable to me, but needs a newsfile. 👍

**Comment by ShadowJonathan** [comment]
> Looks pretty reasonable to me, but needs a newsfile.

??? it has a news file?

**Comment by ShadowJonathan** [comment]
The newsfile run failed with `docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/python/manifests/3.6: EOF.`, kick, maybe?

**Comment by clokep** [comment]
> > Looks pretty reasonable to me, but needs a newsfile.
> 
> ??? it has a news file?

Oops, that was just another instance of the Docker build failing. I restarted it.

**Review by clokep — APPROVED** [review]
Looks good if CI passes.

**Pull request merged**
