### PR TITLE
Clean-up the template loading code

### PR DESCRIPTION
**Pull request by clokep**
This attempts to clean-up some of the template loading code a bit:

* Enables auto-escape by default for HTML files (this was originally done in #8037, but partially disabled in #8394).
* Adds a new `read_template` method for reading a single template.
* Some logic clean-up.

A few things to look out for here:
* Does the SSO redirect issue still exist from #8394? I don't know how to reproduce this, maybe @anoadragon453 remembers.
* Do we need to call this out in the upgrade notes?

### CODE REVIEW

**Comment by clokep** [comment]
Following-up on a conversation from #synapse-dev:matrix.org from earlier today -- both of the redirect URLs for SSO were already being manually escaped, so turning on autoescape shouldn't change anything here. It is also possible that #9128 would help with whatever problem we had been seeing.

I'll double check with some of the SSO setups though to ensure that nothing seems amiss.

**Review by erikjohnston — COMMENTED** [review]
I think the code looks fine, I don't know the answers to the questions posed in the PR description though

**Comment by clokep** [comment]
> I'll double check with some of the SSO setups though to ensure that nothing seems amiss.

I did some testing here and the redirect flows for both login and UIAuth were still working fine with this branch.

**Comment by clokep** [comment]
> I think the code looks fine, I don't know the answers to the questions posed in the PR description though

I think the first question is answered, for the second one, I suspect we should probably mention something about it.

**Comment by dkasak** [comment]
We should definitely mention something so that people know what's up if it breaks their stuff, IMO.

**Comment by clokep** [comment]
I added a note about this to the upgrade docs.

**Review by erikjohnston — APPROVED** [review]

**Comment by erikjohnston** [comment]
@clokep looks like you need to merge in develop?

**Pull request merged**
