### PR TITLE
Url thumbnail fix #2399

### LINKED ISSUE #2399: Thumbnails not generating
Dynamic thumbnails do not seem to work for me on latest stable synapse server.
The following error happens on the server:
```
2017-08-01 23:30:44,477 - synapse.http.server - 139 - ERROR - GET-251446- Failed handle request synapse.rest.media.v1.thumbnail_resource._async_render_GET on <synapse.rest.me
source.ThumbnailResource instance at 0x7f1c89cff488>: <XForwardedForRequest at 0x7f1c8047fa28 method=GET uri=/_matrix/media/v1/thumbnail/kolosowscy.pl/SmBExHmNiwzfKirHWlLuctG
100 clientproto=HTTP/1.0 site=8008>
Traceback (most recent call last):
  File "/srv/synapse/lib/python2.7/site-packages/synapse/http/server.py", line 118, in wrapped_request_handler
    yield request_handler(self, request)
  File "/srv/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/srv/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/srv/synapse/lib/python2.7/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 61, in _async_render_GET
    request, media_id, width, height, method, m_type
  File "/srv/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/srv/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/srv/synapse/lib/python2.7/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 163, in _select_or_generate_local_thumbnail
    media_id, desired_width, desired_height, desired_method, desired_type
  File "/srv/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/srv/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/srv/synapse/lib/python2.7/site-packages/synapse/rest/media/v1/media_repository.py", line 294, in generate_local_exact_thumbnail
    input_path, t_path, t_width, t_height, t_method, t_type
  File "/srv/synapse/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/srv/synapse/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/srv/synapse/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/srv/synapse/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/srv/synapse/lib/python2.7/site-packages/synapse/rest/media/v1/media_repository.py", line 258, in _generate_thumbnail
    thumbnailer = Thumbnailer(input_path)
  File "/srv/synapse/lib/python2.7/site-packages/synapse/rest/media/v1/thumbnailer.py", line 32, in __init__
    self.image = Image.open(input_path)
  File "/srv/synapse/lib/python2.7/site-packages/PIL/Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/srv/synapse/media_store/local_content/Sm/BE/xHmNiwzfKirHWlLuctGW'
```

In riot it looks like so:
image

### PR DESCRIPTION
**Pull request by jkolo**

### CODE REVIEW

**Comment by ara4n** [comment]
thanks for the PR - can you give some context on what it's doing?

**Comment by jkolo** [comment]
This PR fix problem with dynamic thumbnail for urls. See issue #2399

**Comment by ara4n** [comment]
ah, sorry - missed the link to #2399

**Comment by jkolo** [comment]
bump

**Comment by logic** [comment]
FWIW, this fixed thumbnailing for me as well.

**Comment by maciozo** [comment]
Is there a reason this still hasn't been pulled?

**Comment by johnfoo** [comment]
can confirm as of today this PR fix the still existing issue #2399 on master.

**Comment by brainbug89** [comment]
Will this fix ever be pulled? :thinking:

**Comment by krombel** [comment]
@brainbug89 This PR can currently not merged as it has merge conflicts. It will not be merged before sb. resolves them.
@jkolo Have you plans to do so?

**Comment by jkolo** [comment]
@krombel @brainbug89 PR #2791 fixed this case, so this PR is now groundless.

**Pull request closed without merging**
