### PR TITLE
Convert to python 3

### PR DESCRIPTION
**Pull request by martmists**
This PR will be updated while I convert everything. 
DO NOT MERGE YET AS THIS IS INCOMPLETE!

I will let someone know once I've finished converting.

### CODE REVIEW

**Comment by martmists** [comment]
Just as an FYI, this PR is going to end up not passing tests as those are designed for python 2.7

**Comment by ara4n** [comment]
Thanks for opening the PR!  The duplicate "Can one of the admins verify this patch?" is because Jenkins is stupid and asks N times for each test environment it tests against.

needless to say, if we're migrating the codebase to python 3, the tests will need to be migrated too in order to have any confidence that the switch has been successful - not to mention that the tests are absolutely vital for day-to-day development on the server (i.e. there's a reason they exist in the first place! :)

**Comment by martmists** [comment]
Noted, I'll see how far I come.
I'm also real quick gonna cc #2537 and #1149 if anyone checks those out

**Comment by richvdh** [comment]
@martmists: lest you do a lot of work that we are never going to be able to merge, a few thoughts on this.

Firstly, thanks for looking into this. Obviously, python 2 is somewhat outdated and moving to python 3 is a worthy goal. However, I think we need to be careful how we approach this work.

Firstly, we will need to preserve python 2 compatibility (for now at least). That means many things, but for example, this clearly breaks compatibility:
```
-        if isinstance(value, int) or isinstance(value, long):
+        if isinstance(value, int) or isinstance(value, int):
```
There are many other changes already in this PR which will make synapse incompatible with python 2. In all but the most unusual circumstances, it shouldn't be that difficult for code to be compatible with both python 2 and python 3. (For example: I suggest you use the `six` compatibility features rather than doing a blanket replacement of `xrange` with `range`).

We won't be able to merge any changes unless the tests continue to pass on python 2.

Secondly, we don't have enough confidence in our tests, or in 2to3, to be able to accept any changes without a manual review. In practice, a single massive diff is going to be impossible to review, particularly if it does things like mix up PEP8 changes, python3 compatibility, and general cleanups together.

So, thank you again for beginning this work, but please be aware that we won't be able to do anything with it in this form. Instead, we'll need it to be formed as a series of smaller PRs which we can be confident in. For instance, a single PR might fix all the `print` statements. Another might fix up the use of `xrange`.

**Comment by martmists** [comment]
Alright, I'll see what I can do about that

**Pull request closed without merging**
