### PR TITLE
Add support for running Complement against the local checkout

### PR DESCRIPTION
**Pull request by anoadragon453**
This PR adds a script that:

* Builds the local Synapse checkout using our existing `docker/Dockerfile` image.
* Downloads [Complement](https://github.com/matrix-org/complement/)'s source code.
* Builds the [Synapse.Dockerfile](https://github.com/matrix-org/complement/blob/master/dockerfiles/Synapse.Dockerfile) using the above dockerfile as a base.
* Builds and runs Complement against it.

This set up differs slightly from [that of the dendrite repo](https://github.com/matrix-org/dendrite/blob/master/build/scripts/complement.sh) (`complement.sh`, `Complement.Dockerfile`), which instead stores a separate, but slightly modified, dockerfile in Dendrite's repo rather than running the one stored in Complement's repo. That synapse equivalent to that dockerfile (`Synapse.Dockerfile`) in Complement's repo is just based on top of `matrixdotorg/synapse:latest`, which we opt to build here locally.

Thus copying over the files from Complement's repo wouldn't change any functionality, and would result in two instances of the same files. So just using the dockerfile in Complement's repo was decided upon instead.

### CODE REVIEW

**Comment by clokep** [comment]
I have a couple of questions:

* Rebuilding the docker image each time seems rather wasteful, can we mount the Synapse code instead if you've previously built the image?
* When running this on my machine the tests failed! 😢 Is that expected?

**Comment by anoadragon453** [comment]
> Rebuilding the docker image each time seems rather wasteful, can we mount the Synapse code instead if you've previously built the image?

Hm, yes we could optimise this in a number of ways. The longest time building the image seems to be spent installing dependencies.

We could have a dockerfile that simply copies and reads Synapse's dependencies, installs all of them and then allows for mounting the code. However I'd rather we didn't have to create yet another dockerfile if possible. Therefore I'm wondering how we can modify our existing two ([Synapse Dockerfile](https://github.com/matrix-org/synapse/blob/develop/docker/Dockerfile), [Complement Dockerfile](https://github.com/matrix-org/complement/blob/master/dockerfiles/Synapse.Dockerfile)) instead.

> When running this on my machine the tests failed! cry Is that expected?

Yes, Synapse does not pass all of Complement's test yet unfortunately. I suspect this will be easier to fix once we have it in CI though :slightly_smiling_face:

**Comment by clokep** [comment]
I think we talked a bit about this yesterday, but to recap:

> > Rebuilding the docker image each time seems rather wasteful, can we mount the Synapse code instead if you've previously built the image?
> 
> Hm, yes we could optimise this in a number of ways. The longest time building the image seems to be spent installing dependencies.
> 
> We could have a dockerfile that simply copies and reads Synapse's dependencies, installs all of them and then allows for mounting the code. However I'd rather we didn't have to create yet another dockerfile if possible. Therefore I'm wondering how we can modify our existing two ([Synapse Dockerfile](https://github.com/matrix-org/synapse/blob/develop/docker/Dockerfile?rgh-link-date=2020-09-16T10%3A39%3A50Z), [Complement Dockerfile](https://github.com/matrix-org/complement/blob/master/dockerfiles/Synapse.Dockerfile?rgh-link-date=2020-09-16T10%3A39%3A50Z)) instead.

Thanks! I don't think this should necessarily block merging, I just know that when things are slow, people tend not to run them.

> > When running this on my machine the tests failed! cry Is that expected?
> 
> Yes, Synapse does not pass all of Complement's test yet unfortunately. I suspect this will be easier to fix once we have it in CI though 🙂

Ah-ha! Is there a separate issue about this?

**Review by clokep — APPROVED** [review]

**Comment by clokep** [comment]
@anoadragon453 (or anyone else) Is there more to do here before merging? Not sure if I missed a conversation!

**Comment by anoadragon453** [comment]
@clokep There's not an immediate blocker no, I was just thinking about speeding up the dockerfile before merging, but I don't think I'll get to that for a bit and I don't want this PR to sit forever.

> Ah-ha! Is there a separate issue about this?

There is now! https://github.com/matrix-org/synapse/issues/8421

**Pull request merged**
