### PR TITLE
Downcase userid on registration

### PR DESCRIPTION
**Pull request by richvdh**
Force username to lowercase before attempting to register

https://github.com/matrix-org/synapse/issues/2660

### CODE REVIEW

**Comment by ara4n** [comment]
Unless we also do this in the login API (first trying with the non-squashed mxid, and then retrying with the squashed one if the non-squashed one didn't exist), we risk further UX problems, where the  user thinks they've registered `@MrFlibble:matrix.org` and then tries to log in as `MrFlibble` only to be rejected.   (This is what we did on Riot/Web and promptly forgot to do on Riot/iOS & Android - in retrospect it should probably have been all done serverside to make life easier for client implementers and avoid precisely the failure mode which screwed us here)

**Comment by richvdh** [comment]
We do already do it on login.

**Comment by richvdh** [comment]
(Serverside)

**Comment by richvdh** [comment]
retest this please

**Comment by richvdh** [comment]
ok, ptal.

**Comment by richvdh** [comment]
retest this please

**Comment by enannos** [comment]
> 
> 
> (Serverside)

How?

**Pull request merged**
