### PR TITLE
Fix #1677 and change unique on local_media_repository_thumbnails and …

### LINKED ISSUE #1677: 'dynamic_thumbnails' ignores aspect when scaling
Turning on the 'dynamic_thumbnails' option on synapse results in images you see in the riot web client being scaled to the exact dimensions given in the URL query rather than the dimensions acting as a bounding box and aspect-scaling. This makes images look very silly.

### PR DESCRIPTION
**Pull request by jkolo**
…remote_media_cache_thumbnails

### CODE REVIEW

**Comment by erikjohnston** [comment]
@matrixbot ok to test

**Comment by erikjohnston** [comment]
Why do we want to change the index?

**Comment by jkolo** [comment]
I've changed the index because under my own use case it sometimes happen that the client requested multiple thumbnails of the same size but with different scaling methods, which violated the unique constrain.

**Comment by lukebarnard1** [comment]
@jkolo, the consensus is that we're happy merge the fix for thumbnails scaling correctly but we need a bit more time to consider modifying the thumbnail table to get rid of the UNIQUE. Any chance you could split this into two PRs?

**Comment by jkolo** [comment]
Ok, no problem

2017-02-16 14:21 GMT+01:00 Luke Barnard <notifications@github.com>:

**Pull request closed without merging**
