### PR TITLE
Fix admin List Room API return type on sqlite

### LINKED ISSUE #13505: Admin `list-room` API returns integers instead of booleans on SQLite
### Description

According to https://github.com/ruma/synapse-admin-api/issues/14, the `federatable` and `public` fields in the response of the [List room API](https://matrix-org.github.io/synapse/develop/admin_api/rooms.html#list-room-api) return `0` / `1` instead of `true` / `false`, while the example in the linked documentation shows boolean values.

### Steps to reproduce

Use the list room API? 🤷🏼 

### Homeserver

any

### Synapse Version

unknown

### Installation Method

_No response_

### Platform

unknown

### Relevant log output

```shell
-
```

### Anything else that would be useful to know?

_No response_

### PR DESCRIPTION
**Pull request by DMRobertson**
Closes #13505. I think this was an oversight in #7225.

### CODE REVIEW

**Comment by jplatte** [comment]
Thanks! So are all conceptually-boolean fields supposed to be booleans in the JSON representation? The first example on https://matrix-org.github.io/synapse/develop/admin_api/user_admin_api.html shows this:

```
    "is_guest": 0,
    "admin": 0,
    "deactivated": 0,
    "shadow_banned": 0,
```

but I just noticed that some of these fields are mentioned as being `bool` further down.

**Review by squahtx — APPROVED** [review]
LGTM!

**Comment by squahtx** [comment]
> Thanks! So are all conceptually-boolean fields supposed to be booleans in the JSON representation? The first example on https://matrix-org.github.io/synapse/develop/admin_api/user_admin_api.html shows this:
> 
> ```
>     "is_guest": 0,
>     "admin": 0,
>     "deactivated": 0,
>     "shadow_banned": 0,
> ```
> 
> but I just noticed that some of these fields are mentioned as being `bool` further down.

That's a good point. Those sound like they should be booleans too. I've went and filed this as #13519.

**Comment by DMRobertson** [comment]
Oops. Pushed to wrong branch.

**Comment by DMRobertson** [comment]
> Those sound like they should be booleans too. I've went and filed this as https://github.com/matrix-org/synapse/issues/13519.

Thanks. I'll fix this up to include those when I get a chance.

**Comment by DMRobertson** [comment]
> Thanks. I'll fix this up to include those when I get a chance.

On reflection I'd rather get this in and leave the others as a TODO; if anyone else has the inclination to pick this up it'd be much appreciated!

**Pull request merged**
