### PR TITLE
Remove unused code from synapse.logging.utils

### LINKED ISSUE #7896: time.clock has been deprecated and removed in python 3.8 in favor of time.perf_counter/process_time
### Description

time.clock has been deprecated and removed in python 3.8 in favor of time.perf_counter/process_time . Reference : https://github.com/python/cpython/pull/13270

### Steps to reproduce

```
synapse/logging/utils.py
88:        start = time.clock()
95:            end = time.clock()
```

### PR DESCRIPTION
**Pull request by tirkarthi**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

Fixes #7896

### CODE REVIEW

**Comment by anoadragon453** [comment]
Thanks! I was wondering why this wasn't breaking everything though as lots of people run Synapse on Python 3.8. From what I can tell, it looks like `time_function` and a few other methods in `synapse/logging/utils.py` aren't used anywhere.

As such, it may be a better idea to modify this PR to remove this/these methods instead :)

**Comment by tirkarthi** [comment]
yes, only log_function seems to be used. Shall I just remove time_function alone? I am not sure if these are documented as part of the API to be used by someone.

```
rg 'logging.utils'                      
contrib/experiments/test_messaging.py
39:# from synapse.logging.utils import log_function

synapse/state/__init__.py
31:from synapse.logging.utils import log_function

synapse/storage/data_stores/main/events.py
33:from synapse.logging.utils import log_function

synapse/handlers/federation.py
64:from synapse.logging.utils import log_function

synapse/handlers/events.py
23:from synapse.logging.utils import log_function

synapse/handlers/presence.py
39:from synapse.logging.utils import log_function

synapse/federation/federation_server.py
60:from synapse.logging.utils import log_function

synapse/federation/federation_client.py
56:from synapse.logging.utils import log_function

synapse/federation/persistence.py
24:from synapse.logging.utils import log_function

synapse/federation/transport/client.py
30:from synapse.logging.utils import log_function

synapse/notifier.py
29:from synapse.logging.utils import log_function
```

**Comment by clokep** [comment]
> yes, only log_function seems to be used. Shall I just remove time_function alone? I am not sure if these are documented as part of the API to be used by someone.

I don't believe these are meant to be public (although `synapse.logging.context` definitely is). I think `time_function`, `trace_function`, `get_previous_frames`, and `get_previous_frame` can all be removed. You'll also need to update the newsfragment to mention removing unused code instead!

**Comment by tirkarthi** [comment]
Thanks @clokep I removed the mentioned functions and added a misc note.

**Comment by clokep** [comment]
@tirkarthi Looks good, but linting is failing! You can test this locally by running `./scripts-dev/lint.sh` (see https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style).

**Comment by tirkarthi** [comment]
Removed unused imports. Thanks.

**Pull request merged**
