### PR TITLE
Fix issues with JWT login

### PR DESCRIPTION
**Pull request by nikriek**

### CODE REVIEW

**Comment by erikjohnston** [comment]
@matrixbot ok to test

**Comment by nikriek** [comment]
Give me one day. I thought about adding another configuration parameter.

**Comment by erikjohnston** [comment]
Any news?

**Comment by nikriek** [comment]
Jep, few things. I will finish it this weekend!

**Comment by erikjohnston** [comment]
No problem! Just checking you're alive :)

**Comment by nikriek** [comment]
Actually I was already done. I thought about adding another config var that allows to change the key to get the user identifier. But in my understanding the `sub` key should be used for this. 

Btw: The Flake8 link is invalid.

**Comment by erikjohnston** [comment]
Ok cool, will try and have a look tomorrow :)

@matrixbot: test this please

**Comment by erikjohnston** [comment]
> `login.py:229` line is too long.

Other than that it looks good.

**Comment by nikriek** [comment]
Done :)

**Comment by erikjohnston** [comment]
(Looks like that test spuriously timed out.)

Thanks for this!

**Pull request merged**
