### PR TITLE
Generalize the current database drivers further to minimise engine-specific behaviour

### PR DESCRIPTION
**Pull request by ShadowJonathan**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

### CODE REVIEW

**Comment by ShadowJonathan** [comment]
(I invite people to look at the added `todo` items and give suggestions wherever possible)

**Comment by clokep** [comment]
My quick thought on this is that I'm not sure that this really generalizes things, the PR could use a more in-depth description of what this is accomplishing and why.

It seems to mostly be swapping out an isinstance check for a property saying whether something is postgres or sqlite. I understand this is related to #9294 -- would it be possible to use the same `PostgresEngine` wrapper for that? If not, then why?

**Comment by ShadowJonathan** [comment]
It wont be possible to use the same wrapper, the `PostgresEngine` isinstance check comes with the assumption that it'll either be the `psycopg2` driver, or the `sqlite3` driver, we need to generalise this to the point of "oh, what SQL dialect do i need to use?" (postgresql or sqlite), some of these `isinstance` checks were left in because the branch started using `psycopg2`-specific logic.

This PR is aimed to make the codebase more intentionally oblivious which exact driver is being used at all times, and removing assumptions it'll then either be a binary of `psycopg2` or `sqlite3` passing through, so it needs to first be generalized to the two SQL dialects coming up (`postgresql` and `sqlite`), with driver-specific logic having fallbacks that don't assume the binary of drivers.

**Comment by ShadowJonathan** [comment]
Question; does `MultiWriterIdGenerator` use `psycopg2`-specific assumptions? e.g. connections being thread-safe and/or `psycopg2`-specific methods/behaviour.

**Comment by ShadowJonathan** [comment]
Closing this PR as the changes need to be less vague and targeted, i'll come back to this later (hopefully).

**Pull request closed without merging**
