### PR TITLE
Use HTTPStatus constants in place of literals in `tests.rest.client.test_auth`.

### PR DESCRIPTION
**Pull request by reivilibre**
for consistency

### CODE REVIEW

**Review by DMRobertson — COMMENTED** [review]
LGTM. Do we want to merge in develop to get your latest fix for CI?

**Comment by DMRobertson** [comment]
I restarted the jobs; maybe that will suffice.

**Review by DMRobertson — APPROVED** [review]
I'm happy if CI is happy.

**Comment by reivilibre** [comment]
> I restarted the jobs; maybe that will suffice.

heh, I think we may have restarted the jobs roughly at the same time... oops :)

**Pull request merged**
