### PR TITLE
Limit concurrent event creation for a room to avoid state resolution when sending bursts of events to a local room

### LINKED ISSUE #14941: Apply limiter patch from Gitter import
While importing historical Gitter archives into Gitter's homeserver we added a patch to improve performance:

```diff
diff --git a/synapse/handlers/message.py b/synapse/handlers/message.py
--- a/synapse/handlers/message.py
+++ b/synapse/handlers/message.py
@@ -502,7 +502,7 @@

         # We arbitrarily limit concurrent event creation for a room to 5.
         # This is to stop us from diverging history *too* much.
-        self.limiter = Linearizer(max_count=5, name="room_event_creation_limit")
+        self.limiter = Linearizer(max_count=1, name="room_event_creation_limit")

         self._bulk_push_rule_evaluator = hs.get_bulk_push_rule_evaluator()
```

----

Digging some context out of internal issues:

> The idea is to reduce the concurrency of event sends into rooms from 5 -> 1 in order to eliminate state resolution from occurring when sending bursts of events to a local room: [matrix-org/synapse@`54c012c`/synapse/handlers/message.py#L502-L504](https://github.com/matrix-org/synapse/blob/54c012c5a8722725cf104fa6205f253b5b9b0192/synapse/handlers/message.py#L502-L504)

For cross-linking, there was an old issue about doing this in #8612.

----

Unfortunately this changes was applied at the same time as a few other changes (disabling push and increasing the number of workers), so it is unclear how much impact this change had.

### PR DESCRIPTION
**Pull request by H-Shay**
Previously concurrent event creation in a room was set to 5, this limits it to 1, thus eliminating the possibility of state resolution which can be slow. Fixes #14941. Originally this patch was applied to the Gitter instance, it is being ported to Synapse now.

### CODE REVIEW

**Review by squahtx — APPROVED** [review]
lgtm!

**Comment by clokep** [comment]
Do we have a plan to see if this helps performance at all? I guess we're hoping event creation time decreases?

**Comment by H-Shay** [comment]
> Do we have a plan to see if this helps performance at all?

Not that I am aware of - I guess it might make sense to get a sample of jaeger traces before and after the change and see if there's a significant difference? It seems like it might be hard to pin down/quantify effectively.

**Comment by clokep** [comment]
> > Do we have a plan to see if this helps performance at all?
> 
> Not that I am aware of - I guess it might make sense to get a sample of jaeger traces before and after the change and see if there's a significant difference? It seems like it might be hard to pin down/quantify effectively.

If it is just "it doesn't make send time *worse*" that's fine. I'm just hoping we have a grafana graph to point to after deploy!

**Comment by H-Shay** [comment]
So the relevant graphs would probably be the event send time and event send time quantiles? Would it make sense to grab a 7-day spread of both before this is deployed, deploy it in the next rc, let it run for 7 days (assuming nothing blows up) and then compare the graphs with the ones taken before it was deployed?

**Comment by clokep** [comment]
> Would it make sense to grab a 7-day spread of these before this is deployed, deploy it in the next rc, let it run for 7 days (assuming nothing blows up) and then compare the graphs with the ones taken before it was deployed?

There's no need to grab data before hand, just would be interesting to check it a bit after a deploy and ensure it looks the same or better.

**Pull request merged**
