### PR TITLE
Do not expose the experimental appservice login flow to clients.

### PR DESCRIPTION
**Pull request by clokep**
This was breaking logins for Element iOS.

Related to #8320

### CODE REVIEW

**Comment by clokep** [comment]
CC @Half-Shot

**Review by richvdh — APPROVED** [review]

**Comment by tulir** [comment]
You should really fix broken clients rather than making it impossible to detect if a homeserver supports appservice login :/

**Comment by clokep** [comment]
> You should really fix broken clients rather than making it impossible to detect if a homeserver supports appservice login :/

The clients are being fixed, but it was necessary to give some time to 1) figure out what's broken, 2) get users to update (app stores and such don't roll out updates to everyone when you want)

**Comment by richvdh** [comment]
I believe the bug in question is https://github.com/vector-im/element-ios/issues/3711, which appears to be fixed now? Can we revert this for synapse 1.22?

**Comment by clokep** [comment]
> I believe the bug in question is [vector-im/element-ios#3711](https://github.com/vector-im/element-ios/issues/3711), which appears to be fixed now? Can we revert this for synapse 1.22?

I think so, yes. I'll do a PR soon.

**Comment by clokep** [comment]
> > I believe the bug in question is [vector-im/element-ios#3711](https://github.com/vector-im/element-ios/issues/3711), which appears to be fixed now? Can we revert this for synapse 1.22?
> 
> I think so, yes. I'll do a PR soon.

See #8504.

**Pull request merged**
