### PR TITLE
implement `reload` by sending the HUP signal

### PR DESCRIPTION
**Pull request by gdamjan**
According to the 0.99 [release info](https://github.com/matrix-org/synapse/releases/tag/v0.99.0) synapse now uses the HUP signal to reload certificates:
> Synapse will now reload TLS certificates from disk upon SIGHUP. (#4495, #4524)

So the matrix-synapse.service unit file should include a reload directive.

### CODE REVIEW

**Comment by richvdh** [comment]
Thanks. Can you add an entry to the `debian/changelog`?

**Comment by gdamjan** [comment]
I'm not sure how that should look, do I put myself as signed?

**Comment by richvdh** [comment]
Probably best to use [dch](https://manpages.debian.org/stretch/devscripts/dch.1.en.html). Try something like `dch -v 0.99.1`, which will start an UNRELEASED version, and put your name in the maintainer field. It will then open an editor where you can add a suitable entry in the template it gives you. 

Later, when we come to do the next release, `dch` will then put our email address back in the maintainer field and record your contribution [like this](https://github.com/matrix-org/synapse/blob/master/debian/changelog#L48).

**Comment by gdamjan** [comment]
feel free to squash/merge the 2 commits

**Comment by richvdh** [comment]
thank you!

**Pull request merged**
