### PR TITLE
Update type annotations for compatiblity with prometheus_client 0.14

### LINKED ISSUE #12387: CI run against Twisted trunk is failing
See https://github.com/matrix-org/synapse/actions/runs/2101100787

### PR DESCRIPTION
**Pull request by richvdh**
Principally, `prometheus_client.REGISTRY.register` now requires its argument to extend `prometheus_client.Collector`.

Additionally, `Gauge.set` is now annotated so that passing `Optional[int]` causes an error.

Fixes #12387.

### CODE REVIEW

**Review by squahtx — APPROVED** [review]

**Review by reivilibre — CHANGES_REQUESTED** [review]
Mypy seems fine but looks like you've introduced a circular import :/. Seems fine otherwise.

EDIT: this was meant to be an approval (once the bug is fixed)

**Comment by squahtx** [comment]
LGTM though CI is unhappy due to circular imports

**Comment by DMRobertson** [comment]
Perhaps move `Collector` into `synapse.metrics.types`, and import that into `synapse.metrics.*`?

**Comment by richvdh** [comment]
> Perhaps move Collector into synapse.metrics.types, and import that into synapse.metrics.*?

indeed. thanks!

**Comment by DMRobertson** [comment]
(Sorry for wading in on this; I'm just keen to get CI going on my other branches)

**Pull request merged**
