### PR TITLE
Fix a small typo in the arguments of simple_update in update_remote_profile_cache

### PR DESCRIPTION
**Pull request by anoadragon453**
`values` is not an argument to `simple_update`, but `updatevalues` is. I believe this was an error when referencing the above function, which uses `simple_upsert`, which does have a `values` argument.

### CODE REVIEW

**Comment by richvdh** [comment]
(and if it was causing an error, when was it introduced, and do we have an idea of the likely effects?)

**Comment by anoadragon453** [comment]
> Seems reasonable. Was this causing an error or did you just see it?

I just noticed it while doing some DINSIC fixes.

> (and if it was causing an error, when was it introduced, and do we have an idea of the likely effects?)

Looks like this happened back in August 2017. https://github.com/matrix-org/synapse/commit/27ebc5c8f299488ccc0a6f100ec3b248cd81a058#diff-cd4b93e0990af0adac7019cbb0156bc5R91-R95

As far as the implications, it looks like it would cause the "Update remote profile" background job to be useless: https://github.com/matrix-org/synapse/blob/6b22921b195c24762cd7c02a8b8fad75791fce70/synapse/handlers/profile.py#L371-L374

**Comment by richvdh** [comment]
HAH! that explains a lot. This probably fixes https://github.com/matrix-org/synapse/issues/7388; when I glanced at it, it just seemed to be doing the same thing over and over.

**Comment by anoadragon453** [comment]
@richvdh I've updated the changelog with relevant information. Does that look good to you?

Is there a way to verify whether this fixes https://github.com/matrix-org/synapse/issues/7388 now or should we wait until a deployment to verify?

**Comment by richvdh** [comment]
> @richvdh I've updated the changelog with relevant information. Does that look good to you?

for the changelog, we (or rather, the audience) are probably more interested in the release that introduced the bug than the PR # ; given it's pretty prehistoric I think its fine to say "long-standing bug" like https://github.com/matrix-org/synapse/blob/75fbc1a0c6084c55c72da8ca48971d288eaf6e89/CHANGES.md#bugfixes.

For the record: introduced in #2429, probably synapse v0.23.0.

> Is there a way to verify whether this fixes #7388 now or should we wait until a deployment?

suggest we deploy it and see what happens...

**Comment by richvdh** [comment]
doesn't seem to have done much to fix #7388, ftr

**Pull request merged**
