### PR TITLE
Downgrade 'Closing scope' error to a warning to prevent hammering sentry

### PR DESCRIPTION
**Pull request by anoadragon453**
We noticed an error repeatedly coming up in Sentry after deploying e91a9290494722d48ca42bb68e560f6bd5b6f212 to matrix.org yesterday: https://sentry.tools.element.io/organizations/element/issues/725/ (internal link for those with access).

In summary, we're seeing hundreds of thousands of the following on incoming `GET /_matrix/federation/v1/event/{eventId}` requests:

```
Closing scope %s which is not the currently-active one %s
<synapse.logging.scopecontextmanager._LogContextScope object at 0x7f181f60e4f0>
```

@squahtx proposed that this was due to changes in https://github.com/matrix-org/synapse/pull/13489.

> I imagine the messed up logging contexts have been there for a long time and it's only complaining extra hard now because of the new spans.

This PR reduces the error to a warning so that Sentry data is usable again. We should still separately fix the issue.

### CODE REVIEW

**Review by babolivier — APPROVED** [review]
lgtm as long as we commit to properly fixing it in the not too distant future.

**Comment by squahtx** [comment]
May be related to #13366 or #10855.

**Comment by richvdh** [comment]
oh man, I'm not very keen on this. can't we find the actual problem rather than just ignoring it?

**Comment by richvdh** [comment]
We've investigated further and found that #13499 is the cause of the problems here. We're investigating a fix, but otherwise we'll just revert #13499 for now.

**Pull request closed without merging**
