### PR TITLE
Add new room membership APIs

### PR DESCRIPTION
**Pull request by erikjohnston**
Add two new APIs:

- `/joined_rooms` that returns the list of rooms the user is in
- `/room/<room_id>/joined_members` that returns the list of currently joined users and their profile data

These are primarily designed for ASes that may want to efficiently look up those pieces of information without otherwise needing to do a full `/sync`

---

Example output:

```http
GET /joined_rooms

{"joined_rooms": ["!foo:example.com"]}
```

```http
GET /room/!foo:example.com/joined_members

{"joined": {"@bar:example.com": { "display_name": "Bar", "avatar_url": null }}}
```

### CODE REVIEW

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/sytest/pull/329

**Comment by leonerd** [comment]
I admit it's probably a bit late now, but is there any reason why

> {"joined": {"@bar:example.com": { "display_name": "Bar", "avatar_url": null }}}

the toplevel key is `joined`? This is neither the last component of the URI (`joined_members`), nor is it the actual `membership` string value (which would be `join`).

**Comment by t3chguy** [comment]
Correction: `GET /rooms/!foo:example.com/joined_members`
s/room/rooms/

**Comment by richvdh** [comment]
updated, thanks @t3chguy

**Pull request merged**
