### PR TITLE
Collapse Docker build commands in Complement CI runs to make the logs easier to read.

### PR DESCRIPTION
**Pull request by reivilibre**
apt-get is frequently one of the spammiest things when scrolling down into Complement logs. Let's quieten it a bit.

Note that nobody seems to have found the ultimate cure for apt-get noise other than `/dev/null`, which I'm reluctant to do...

EDIT: The entire Docker building process is basically spam, so this PR now folds that away.

### CODE REVIEW

**Comment by richvdh** [comment]
got a source/link for the `-o=Dpkg::Use-Pty=0` incantation?

**Comment by DMRobertson** [comment]
Apologies for bikeshedding, but: IMO the problem here is that "Run Complement Tests" actually runs complement.sh, so includes all of the setup for complement.

Maybe we could do something like this?

- make complement.sh accept a --setup-only flag which skips tests
- use this flag in CI
- add a new job/step afterwards which invokes `go test ... | gotestfmt` and nothing else

**Comment by reivilibre** [comment]
> got a source/link for the `-o=Dpkg::Use-Pty=0` incantation?

It's one of those things I've picked up over the years. https://askubuntu.com/a/668859 seems to say that it's broken on modern Ubuntu versions though :-( — I'd agree, it still looks cluttered.

`DEBIAN_FRONTEND=noninteractive` AFAIK means that it won't pause to ask questions on stdin. `-o=Dpkg::Use-Pty=0` used to hide a lot of the spammy `(Updating xxxxxx ..... 5%)` messages.

I'm tempted to switch track a bit:

* Use `DEBIAN_FRONTEND=noninteractive` wherever, since it makes sense anyway. I don't know if it does much quietening but I have had apt block forever waiting for input without this before, so let's call it 'best practice'.
* Collapse the setup part of `complement.sh` into a collapsed group in the logs. This means that the spam will still be there, but it'll be hidden away unless you want to see it.

**Comment by DMRobertson** [comment]
> then I wonder if collapsing the logs would make more sense..?

That's a much better idea. Could even check for the existence of a githubby env var before outputting the magic collapse-me-please notation.

**Review by DMRobertson — APPROVED** [review]
Running complement.sh looks great!

I'm not sure if `-qq` will mean we don't get error messages if apt-get fails due to e.g. dodgy network conditions. But it's probably fine and easily revertable.

**Comment by reivilibre** [comment]
> Running complement.sh looks great!
> 
> I'm not sure if `-qq` will mean we don't get error messages if apt-get fails due to e.g. dodgy network conditions. But it's probably fine and easily revertable.

In my experience it will still report issues with `-qq` e.g.:
```
root@lithium:/home/rei# apt-get -yqq install orasntisorantoiasrhdoasrdnr
E: Unable to locate package orasntisorantoiasrhdoasrdnr
```

Thanks for the review

**Pull request merged**
