### PR TITLE
Persist room hierarchy pagination sessions to the database.

### PR DESCRIPTION
**Pull request by clokep**
Part of #10523.

This starts to support running the `/hierarchy` endpoint on multiple workers by persisting pagination state to the database.

## Open questions:

* Does persisting this to the database make sense? (Would it make more sense to persist it to Redis?)
* How do we reasonably share responses over federation among workers?
	* Can we put the responses in Redis/database?
	* Should we be routing those to the proper federation worker and let that cache it in memory?

This somewhat requires fixing matrix-org/complement#194 before I have high confidence in actually saying we can run this as workers, but this is definitely part of the puzzle. (This change also helps with losing state across restart, which is desirable regardless.)

### CODE REVIEW

**Comment by clokep** [comment]
I'm requesting review on this more for discussion of the open questions than an actual code review (although someone taking a look and making sure I'm not doing something crazy would be nice too!)

**Comment by richvdh** [comment]
Inst

Regarding "How do we reasonably share responses over federation among workers?" - I'm not sure I quite understand the question. Are you talking about a 

>     * Does persisting this to the database make sense? (Would it make more sense to persist it to Redis?)

Instinctively, my first reaction to this is "yes, this should be done in Redis rather than the database". Given we already have an `ExternalCache` class, I'd hope this wouldn't be too hard. However, perhaps we need to consider the behaviour when Synapse/Redis are restarted at the same time - is it acceptable for clients to see pagination errors in such a case?

>     * How do we reasonably share responses over federation among workers?
>       
>       * Can we put the responses in Redis/database?
>       * Should we be routing those to the proper federation worker and let that cache it in memory?

I think I need more context here. Are you talking about caching the response from an external server after we make a callout for information on a room? Do we really *need* to share such a cache between workers?

It might be worth taking these questions to the mailing list, for more detailed discussion?

**Comment by clokep** [comment]
> > * How do we reasonably share responses over federation among workers?
> >   
> >   * Can we put the responses in Redis/database?
> >   * Should we be routing those to the proper federation worker and let that cache it in memory?
> 
> I think I need more context here. Are you talking about caching the response from an external server after we make a callout for information on a room? Do we really _need_ to share such a cache between workers?

I think I might be over-engineering this bit. We don't seem to do this in other places and just let each worker call out over federation (e.g. `get_pdu` has a cache that isn't attempted to be shared. See #10647). I'm just going to punt this for now and say "Maybe in the future".

**Comment by clokep** [comment]
> > * Does persisting this to the database make sense? (Would it make more sense to persist it to Redis?)
> 
> Instinctively, my first reaction to this is "yes, this should be done in Redis rather than the database". Given we already have an `ExternalCache` class, I'd hope this wouldn't be too hard. However, perhaps we need to consider the behaviour when Synapse/Redis are restarted at the same time - is it acceptable for clients to see pagination errors in such a case?

I somewhat had the same thought (that this would be better to put into an `ExternalCache`), but it doesn't seem to match what we do now for similar things (UI auth sessions?). In a way this isn't really *cache* data in that it can't be rebuilt. Which makes me lean towards putting it into the database?

**Comment by richvdh** [comment]
> it doesn't seem to match what we do now for similar things (UI auth sessions?)

yeeeees, but it's worth noting that (if memory serves) UI auth session persistence was invented before we used redis for replication, and certainly before `ExternalCache` was created, so that's not necessarily a good guide to the future.

However:

> In a way this isn't really cache data in that it can't be rebuilt.

I suspect this is probably a deal breaker really.

If we're going down the path of using the database, it might still be better just to make it a table with abstract `key` and `value` columns (and possibly `expiry`), so that we don't need to create a new table and new storage methods each time we encounter something that fits this pattern?

(In an ideal world, maybe we'd have an abstract `SessionCache` which is currently backed by the database, but could also be backed by something else in future. But perhaps that's overengineering it.)

**Comment by clokep** [comment]
> If we're going down the path of using the database, it might still be better just to make it a table with abstract `key` and `value` columns (and possibly `expiry`), so that we don't need to create a new table and new storage methods each time we encounter something that fits this pattern?

I did this, I think it is generic enough that it is usable! I'm pretty sure it could replace:

* `threepid_validation_*`
* `ui_auth_sessions`
* Potential solution for #7530 (and maybe a few other spots we keep state in memory).

I'm not sure if this is really an improvement though since you're now serializing arbitrary data to JSON. 🤷 Let me know what you think!

> (In an ideal world, maybe we'd have an abstract `SessionCache` which is currently backed by the database, but could also be backed by something else in future. But perhaps that's overengineering it.)

I think you could probably add a facade in front of what I have here to do this in the future? I still hesitate on calling it a cache though!

**Review by richvdh — COMMENTED** [review]
I'm generally finding the concept of `segment` slippery to get my head around: it feels like a detail that the `SessionStore` shouldn't need to concern itself with. Looking at how it is used in the
`RoomSummaryHandler`, could it not just be part of the `value` of the session?

I also feel like what you are currently calling `key` should be a `session_type`.

**Comment by clokep** [comment]
> I'm generally finding the concept of `segment` slippery to get my head around: it feels like a detail that the `SessionStore` shouldn't need to concern itself with. Looking at how it is used in the
> `RoomSummaryHandler`, could it not just be part of the `value` of the session?

It could be specific to the implementation needed by `RoomSummaryHandler` instead of generic. I'll take a look at that.

> I also feel like what you are currently calling `key` should be a `session_type`.

This is what I originally had it called, but changed it.

**Comment by clokep** [comment]
I updated the code a bit, as requested, to remove the `segment` idea (I replaced it with explicit checks in the `RoomSummaryHandler`). I also renamed `key` -> `session_type`.

**Review by richvdh — APPROVED** [review]
lgtm!

(I slightly wonder if it would be better to use an `attr.s` class to hold the session data, converting to and from a dict when calling the storage layer. But we should probably just get on and land this rather than keep polishing it forever.)

**Comment by clokep** [comment]
> (I slightly wonder if it would be better to use an `attr.s` class to hold the session data, converting to and from a dict when calling the storage layer. But we should probably just get on and land this rather than keep polishing it forever.)

I'm not sure what benefit this would offer? If it is meant to be generic I'm not really sure how the storage layer would know what class to turn it into?

I think I'll land this and we can improve it in the future if necessary.

**Comment by richvdh** [comment]
> I'm not sure what benefit this would offer? If it is meant to be generic I'm not really sure how the storage layer would know what class to turn it into?

to be clear, I'd expect the `RoomSummaryHandler` to do the translation between attr.s and dicts. 

The benefit would essentially be to help with type-safety by collecting all the code that does the `dict` referencing into one place. Quite happy for this to land as it is though.

**Pull request merged**
