### PR TITLE
Mark the shadow_banned column as boolean in synapse_port_db.

### LINKED ISSUE #8384: Migration to postgresql is broken on table users, column shadow_banned
### Description

Migrating from sqlite to postgresql is broken, most probably since version v1.20.0, which introduced shadowbanning

### Steps to reproduce

- Boot up a new server with a database in sqlite
- Attempt to migrate this database to postgresql
- Observe error

### Version information

- **Homeserver**: v1.20.0

- **Install method**: Docker

- **Platform**: Debian 10

### Traceback

```
2020-09-23 14:39:56,457 - synapse_port_db - 298 - INFO - Table group_attestations_renewals: 0/6 (rows 1-0) already ported
user_directory_stream_pos: 100% (1/1)
event_push_summary_stream_ordering: 100% (1/1)
2020-09-23 14:39:56,496 - synapse.metrics - 545 - INFO - Collecting gc 1
appservice_stream_position: 100% (1/1)
event_push_summary: 100% (20/20)
room_tags: 100% (36/36)
pushers: 100% (1/1)
event_reports: 100% (1/1)
user_filters: 100% (11/11)
room_aliases: 100% (30/30)
deleted_pushers: 100% (4/4)
room_tags_revisions: 100% (41/41)
e2e_one_time_keys_json: 100% (300/300)
local_group_membership: 100% (86/86)
2020-09-23 14:39:57,043 - synapse.metrics - 545 - INFO - Collecting gc 1
2020-09-23 14:39:57,061 - synapse.metrics - 545 - INFO - Collecting gc 2
2020-09-23 14:39:57,498 - synapse.metrics - 545 - INFO - Collecting gc 1
2020-09-23 14:39:57,592 - synapse_port_db - 195 - ERROR - Failed to insert: users
Traceback (most recent call last):
  File "./scripts/synapse_port_db", line 193, in insert_many_txn
    txn.executemany(sql, rows)
  File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 215, in executemany
    self._do_execute(self.txn.executemany, sql, *args)
  File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 238, in _do_execute
    return func(sql, *args)
psycopg2.errors.DatatypeMismatch: column "shadow_banned" is of type boolean but expression is of type integer
LINE 1: ... 1600800333, 0, NULL, 0, 'telegram', NULL, NULL, NULL, 0, 0)
                                                                     ^
HINT:  You will need to rewrite or cast the expression.

2020-09-23 14:39:57,604 - synapse_port_db - 636 - ERROR - 
Traceback (most recent call last):
  File "./scripts/synapse_port_db", line 622, in run
    consumeErrors=True,
twisted.internet.defer.FirstError: FirstError[#14, [Failure instance: Traceback: <class 'psycopg2.errors.DatatypeMismatch'>: column "shadow_banned" is of type boolean but expression is of type integer
LINE 1: ... 1600800333, 0, NULL, 0, 'telegram', NULL, NULL, NULL, 0, 0)
                                                                     ^
HINT:  You will need to rewrite or cast the expression.

/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
./scripts/synapse_port_db:386:handle_table
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:541:runInteraction
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:590:runWithConnection
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
/usr/local/lib/python3.7/site-packages/twisted/python/compat.py:464:reraise
/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:587:inner_func
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:429:new_transaction
./scripts/synapse_port_db:374:insert
./scripts/synapse_port_db:193:insert_many_txn
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:215:executemany
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:238:_do_execute
]]
Traceback (most recent call last):
  File "./scripts/synapse_port_db", line 622, in run
    consumeErrors=True,
twisted.internet.defer.FirstError: FirstError[#14, [Failure instance: Traceback: <class 'psycopg2.errors.DatatypeMismatch'>: column "shadow_banned" is of type boolean but expression is of type integer
LINE 1: ... 1600800333, 0, NULL, 0, 'telegram', NULL, NULL, NULL, 0, 0)
                                                                     ^
HINT:  You will need to rewrite or cast the expression.

/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
./scripts/synapse_port_db:386:handle_table
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:541:runInteraction
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:590:runWithConnection
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
/usr/local/lib/python3.7/site-packages/twisted/python/compat.py:464:reraise
/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:587:inner_func
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:429:new_transaction
./scripts/synapse_port_db:374:insert
./scripts/synapse_port_db:193:insert_many_txn
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:215:executemany
/usr/local/lib/python3.7/site-packages/synapse/storage/database.py:238:_do_execute
]]
Traceback (most recent call last):
  File "./scripts/synapse_port_db", line 1078, in <module>
    sys.stderr.write(end_error)
TypeError: write() argument must be str, not FirstError
```

### PR DESCRIPTION
**Pull request by clokep**
This fixes #8384, but not the underlying issue of why tests didn't fail.

### CODE REVIEW

**Comment by clokep** [comment]
I could also target `release-v1.20.0` branch if we want. I don't know if this is enough to do a release for.

**Review by erikjohnston — APPROVED** [review]
Might be worth basing off of `release-v1.20.0` and merge without squashing in case we do want a v1.20.1?

**Comment by erikjohnston** [comment]
Might be worth adding an entry with a shadow banned entry to the users table in `.buildkite/test_db.db` so that it gets caught by CI?

**Comment by clokep** [comment]
> Might be worth adding an entry with a shadow banned entry to the users table in `.buildkite/test_db.db` so that it gets caught by CI?

Did not realize this is where that data is stored. I've done the following:

* Run the `./scripts-dev/update_database` script on `.buildkit/test_db.db`
* Manually modified the database to set `shadow_banned` to `0` for one of the users (`@01register-user-20191002_181700:localhost:8800`)

Does this sound sane? It's a binary file so...changes can't really be seen. I'm unsure if this file had some special configuration or anything or if running the `update_database` script on it is OK.

**Comment by erikjohnston** [comment]
Sounds sane to me, though I'm not hugely familiar with it. Does this sound sane to you @babolivier ?

**Comment by babolivier** [comment]
> Sounds sane to me, though I'm not hugely familiar with it. Does this sound sane to you @babolivier ?

Yep, sounds good to me!

**Pull request merged**
