### PR TITLE
GHA: reintroduce an env var for `$GITHUB_HEAD_REF`

### PR DESCRIPTION
**Pull request by DMRobertson**
This should checkout the dmr/cross-repo-branches sytest branch and run that against this

Requires the bootstrap.sh in the docker container used for sytest to have this change: https://github.com/matrix-org/sytest/pull/1123

### CODE REVIEW

**Comment by DMRobertson** [comment]
I've kicked off another CI run now that the docker containers are updated. We should convince ourselves that GHA runs a version of sytest from the same-named branch.

**Comment by DMRobertson** [comment]
And I think I'll have to create that branch in sytest since it seems to have either never existed, or else been deleted.

**Comment by DMRobertson** [comment]
> We should convince ourselves that GHA runs a version of sytest from the same-named branch.

Apart from the fact that I merged in `master` instead of `develop`, I think this looks good. At the start of "Run Sytest" on https://github.com/matrix-org/synapse/pull/10659/checks?check_run_id=3631232642, we see

```
+ export SYTEST_TARGET=synapse
+ SYTEST_TARGET=synapse
+ shift
+ '[' -d /sytest ']'
+ echo '--- Trying to get same-named sytest branch...'
+ '[' -n dmr/cross-repo-branches ']'
+ branch_name=dmr/cross-repo-branches
+ '[' synapse == dendrite ']'
+ wget -q https://github.com/matrix-org/sytest/archive/dmr/cross-repo-branches.tar.gz -O sytest.tar.gz
--- Trying to get same-named sytest branch...
+ mkdir -p /sytest
+ tar -C /sytest --strip-components=1 -xf sytest.tar.gz
+ '[' -n '' ']'
+ echo '--- Preparing sytest for synapse'
```

In particular, we didn't fall back and fetch from the `develop` branch.

**Review by anoadragon453 — APPROVED** [review]
The change that's intended to be reviewed and the accompanying CI run all LGTM! 

I think if you just checkout `develop` again and cherry-pick `daad5a0` and `6fe295e` then force-push `dmr/cross-repo-branches`, the PR should right itself.

**Comment by DMRobertson** [comment]
One failed sytest, apparently a known flake. Which I'm of a mind to try and purge. Any objections to merging @anoadragon453?

**Comment by anoadragon453** [comment]
None from me!

**Pull request merged**
