### PR TITLE
snap: Add snapcraft support

### PR DESCRIPTION
**Pull request by 3v1n0**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#changelog)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

Supports [snapcraft](http://snapcraft.io/) packaging system to easily distribute synapse in most of linux distributions as a self-contained package.

Ideally this should be maintened by upstream, by doing releases. So you should register `matrix-synapse` name at snapcraft so that you keep the ownership of this package.

You can use [build.snapcraft.io](http://build.snapcraft.io/) to generate automatic builds that lands immediately to the edge channel, once master has changed, while you can manually promote builds to stable or beta.

### CODE REVIEW

**Comment by aaronraimist** [comment]
#1651

**Comment by 3v1n0** [comment]
One possible change to do to this is to change the snap so that it runs a service automatically, so without having the user to setup a personal systemd service for running it, however it would need few more changes.

**Comment by richvdh** [comment]
My initial reaction to this, I'm afraid, is that it's a thing that we don't have the bandwidth to maintain. We have enough to do with maintaining the pypi, docker and .deb packages without adding yet a fourth way.

**Comment by 3v1n0** [comment]
@richvdh differently from all other methods, this really needs minimum maintenance since basically since it uses pypi, once you have that working also the snap will be generated correctly.
Also, as said, the fact you can have automatic builds with just one click would allow to get the CI for this set without efforts.

At the contrary brings great benefit to the anyone using a linux system as having a full and running synapse installation just needs two commands (`snap install matrix-synapse` and configuration)

**Comment by richvdh** [comment]
> @richvdh differently from all other methods, this really needs minimum maintenance since basically since it uses pypi, once you have that working also the snap will be generated correctly.

I'm afraid I just don't believe this. There are all sorts of commands and packages listed in the snap file which need keeping in sync. Also you're telling me that I need to go and register on some sort of repository and presumably we need to manage credentials for it.

The CI will probably break (it always does) and then we'll have to go and find out why. And, most important of all, we'll have to support users who use the snap, who have questions about how to configure it or run operations on it.

All in all: why would the support overhead be any less than any of the other distribution methods?

> At the contrary brings great benefit to the anyone using a linux system as having a full and running synapse installation just needs two commands (snap install matrix-synapse and configuration)

You can already do that with Docker. 

If somebody else wants to maintain the snap *and provide support to the users*, then feel free. I don't think it needs to be us.

**Pull request closed without merging**
