### PR TITLE
Clarify Error codes for GET /filter/

### PR DESCRIPTION
**Pull request by pik**
SynapseError creates errors with https://github.com/matrix-org/synapse/blob/master/synapse/api/errors.py#L66 `errcode` set to `M_UNKNOWN` by default. This just updates the errors raised at the endpoint to send the correct errors, also `get_user_filter` should catch `StoreError` which is raised (https://github.com/matrix-org/synapse/blob/master/synapse/storage/_base.py#L561) when no row is found. I also added an `M_INVALID_PARAM` for the "Invalid FilterId" error since I couldn't find an appropriately matching `errcode` (should this be a separate commit?).

https://github.com/matrix-org/matrix-js-sdk/pull/228

### CODE REVIEW

**Comment by erikjohnston** [comment]
Thanks for this! Are these error codes part of the spec, or are they entirely new?

@matrixbot test this please.

**Comment by erikjohnston** [comment]
There's a couple of flake8 violations: http://matrix.org/jenkins/job/SynapseFlake8Packaging/1168/violations/file/synapse/rest/client/v2_alpha/filter.py/ and some unit test failures: http://matrix.org/jenkins/job/SynapseUnittests/1167/testReport/.

The `Sytest Dendron (Merged PR)` failure looks like it was spuriously killed by an interrupt for some reason.

**Comment by pik** [comment]
@erikjohnston Fixed the flake8 sorry about that. Error Codes don't seem to be specified in the spec ( https://matrix.org/docs/spec/client_server/r0.2.0.html#get-matrix-client-r0-user-userid-filter-filterid); should I PR that / file a Jira issue, not sure what the normal procedure is (though these would seem to fit) ? I extracted the addition of `M_INVALID_PARAM` to do as a separate PR since that requires a new error code not present in errors.py -

**Comment by erikjohnston** [comment]
Sorry for the latency on this, but yeah, this looks good. Can you sign off as per [CONTRIBUTING.rst](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off) and then I'll merge :)

@matrixbot test this please

**Comment by erikjohnston** [comment]
@matrixbot ok to test

**Pull request merged**
