### PR TITLE
move handling of auto_join_rooms to RegisterHandler

### PR DESCRIPTION
**Pull request by krombel**
Currently the handling of `auto_join_rooms` only works when a user
registers itself via public register api. Registrations via
`registration_shared_secret` and ModuleApi do not work

This auto joins the users in the registration handler which enables
the auto join feature for all 3 registration paths.

This is related to issue #2725

Signed-Off-by: Matthias Kesler <krombel@krombel.de>

### CODE REVIEW

**Comment by turt2live** [comment]
How does this affect application services trying to register their users? For the sake of not having performance issues, application service users should not be auto-joined anywhere.

**Comment by krombel** [comment]
application services take another path which does not use `register()` which got modified.
=> This change has no effect on them

**Comment by richvdh** [comment]
@matrixbot : test this please

**Comment by kojo1984** [comment]
Hi,
I'm trying to configure autojoin feature, but with no success. Here's some facts on it:

1. Changed `register.py` on both locations `(/usr/lib/python2.7/dist-packages/synapse/rest/client/v2_alpha & /usr/lib/python2.7/dist-packages/synapse/handlers)`

2. Can't find `test_events.py` nowhere.
3. Added string `auto_join_rooms` into `homeserver.yaml` .
4. I have Matrix/Synapse install with MXISD using WordPress and WP DB for user creation and authentication.

Can you help me on this one?

**Comment by kojo1984** [comment]
@krombel I was just trying everything, because it wasn't working.

Haven't tried to configure the room that allows join to everybody, will do that and get back here.

**Comment by richvdh** [comment]
not here, please. if you have a bug please report it as a separate issue.

**Pull request merged**
