### PR TITLE
Fix error handling around when completing an AS transaction

### PR DESCRIPTION
**Pull request by babolivier**
Fixes a typo introduced in https://github.com/matrix-org/synapse/pull/8655

### CODE REVIEW

**Review by erikjohnston — APPROVED** [review]

**Comment by erikjohnston** [comment]
Looks like you branched from an old develop?

**Comment by babolivier** [comment]
> Looks like you branched from an old develop?

12h old; will merge in latest changes to see if it fixes it

**Comment by clokep** [comment]
Sorry about that. 😢 Looks like it just stops a log line though so not terrible?

**Comment by erikjohnston** [comment]
> Sorry about that.  Looks like it just stops a log line though so not terrible?

Yeah, it just spams the logs :slightly_smiling_face:

**Pull request merged**
