### PR TITLE
Make password reset email field case insensitive

### PR DESCRIPTION
**Pull request by dbkr**
Canonicalizes email addresses to lowercase when adding them: this is the very first step of migrating towards HSes having knowledge of and validating threepids. They still use the ID server to validate emails though.

Adds an index on email address: we didn't have one at all before, we probably should do.

Fixes SYN-788

### CODE REVIEW

**Comment by erikjohnston** [comment]
You'll want to merge in develop

**Comment by dbkr** [comment]
done

**Comment by erikjohnston** [comment]
Looks like sqlite doesn't like your index sql

**Comment by dbkr** [comment]
Huh... it was fine on mine. :/ Maybe an sqlite version thing?

**Comment by dbkr** [comment]
Yep: https://www.sqlite.org/expridx.html - so we need version 3.9.0. Sigh. What do we want to do?

**Comment by erikjohnston** [comment]
The usual trick is to store the lower cased email in the database, so that the normal index can be used. This also neatly side steps the issues where not all 3pids are necessarily case insensitive.

**Comment by dbkr** [comment]
Hmm, true. I guess we could have a db script to migrate the current ones. wdyt?

**Comment by erikjohnston** [comment]
Given it can be done as a simple update, if there aren't too many rows its probably easiest just to do the update in a .sql delta

**Comment by erikjohnston** [comment]
LGTM

**Comment by erikjohnston** [comment]
Oh, except you'll want the delta to be under 37/

**Pull request merged**
