### PR TITLE
Add error code to room creation error

### PR DESCRIPTION
**Pull request by mitch000001**
This error code is mentioned in the documentation at https://matrix.org/docs/api/client-server/#!/Room32creation/createRoom

Signed-off-by: Michael Wagner <mitch.wagna@gmail.com>

### CODE REVIEW

**Comment by richvdh** [comment]
thanks! looks good, but please see https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst.

**Comment by mitch000001** [comment]
Hey, just added some changes. Is that already sufficient?

**Comment by richvdh** [comment]
@matrixbot: retest this please

**Comment by richvdh** [comment]
@matrixbot: retest this please

**Comment by richvdh** [comment]
Despite jenkins getting confused about it, this lgtm, thank you :)

One point: It would be really nice if sytest could be updated with a test for this, to ensure it is implemented correctly in future server versions. In this case, https://github.com/matrix-org/sytest/blob/develop/tests/10apidoc/30room-create.pl is the right place for a test.

**Pull request merged**
