### PR TITLE
Bounce all deferreds through the reactor to make debugging easier.

### PR DESCRIPTION
**Pull request by NegativeMjark**
If all deferreds wait a reactor tick before resolving then there is
always a chance to add an errback to the deferred so that stacktraces
get reported, rather than being discarded.

### CODE REVIEW

**Comment by erikjohnston** [comment]
Is this behind a `debug` flag or some such?

**Comment by NegativeMjark** [comment]
> Is this behind a debug flag or some such?

Not at the moment. Do you think it should be?

**Comment by illicitonion** [comment]
LGTM modulo Erik's flag question

**Comment by NegativeMjark** [comment]
I can't really decide if it should be behind a flag. Not having stack traces is such a pain in so many situations that I'm slightly leaning towards either having it always on, or on by default. But I also think that monkey patching twisted by default is a bit nasty.

**Comment by erikjohnston** [comment]
> Not at the moment. Do you think it should be?

It seems like quite an evasive change to just turn on. It'd be interesting to see what this did to latency in certain cases, since under load the reactor tick time has a tendency to spike. I don't really know how many reactor RTTs this would introduce for various queries. We do yield in a *lot* of places.

**Comment by erikjohnston** [comment]
(As in, its probably fine, but its something we would probably want to be cautious about)

**Comment by erikjohnston** [comment]
LGTM

**Comment by ara4n** [comment]
itym invasive. surely we just benchmark it (prolly just by putting it live on matrix.org) and see if it's noticeable. better debugging ftw.

**Comment by erikjohnston** [comment]
> surely we just benchmark it (prolly just by putting it live on matrix.org) and see if it's noticeable. better debugging ftw.

My main concern is how it performs under load, it really is quite possible that turning this on will cause synapse to completely explode under load.

**Comment by tomprince** [comment]
This turns out to cause breakage, as some code expects `Deferred`s to fire synchronously, and are incorrect if that assumption is violated. (see https://github.com/matrix-org/synapse/issues/1778#issuecomment-272090595)

**Pull request merged**
