### PR TITLE
Implement room version 6 (MSC2240).

### LINKED ISSUE #7500: Implement room version 6
Will contain additional features:
* #6898
* https://github.com/matrix-org/synapse/pull/7381
* #7501

Do not enable by default just yet.

### PR DESCRIPTION
**Pull request by clokep**
Fixes #7500 

This implements room version 6 and removes some experimental room versions.

### CODE REVIEW

**Comment by clokep** [comment]
Some sytests: matrix-org/sytest#869.

**Comment by clokep** [comment]
I should mention that I wasn't positive if it made sense to blow away the experimental room versions, but I doubt people are using them in this case (and two of them were never in a released version of Synapse).

**Comment by clokep** [comment]
I believe I've done that in the PR referenced above: https://github.com/matrix-org/sytest/pull/869/commits/8b87284be30a6eb29eb80aab02523f240ffd628b I need to finish that up still.

**Comment by richvdh** [comment]
oops sorry, missed that

**Pull request merged**
