### PR TITLE
Allow sending a membership event to unban a user 

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/matrix-org/synapse/issues/10270

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by aaronraimist** [comment]
This is how the spec says it should work. However this would reintroduce https://github.com/vector-im/element-web/issues/1961 so maybe needs some thought at the spec level.

**Comment by anoadragon453** [comment]
Note that the Spec offers two APIs that are relevant here:

* `/_matrix/client/r0/rooms/{roomId}/kick`
* `/_matrix/client/r0/rooms/{roomId}/unban`

The Spec doesn't seem to say anywhere that calling `/kick` should necessarily unban a user. However it does make sense that manually sending a `m.room.member` event with membership `leave` for the user should unban them.

To fix both [the issue mentioned on the Element Web side](https://github.com/matrix-org/matrix-js-sdk/pull/364/files#diff-627fe08d8bba6a4fa76e7c5ed36ef6f16d126733e65e19236b391de0d34f1fe0R1387-R1391) (where one user kicking a user and another banning them may race and result in a ban -> leave [unbanned] state), and allow more advanced use-cases, perhaps we could modify Synapse such that:

* `/kick` on a banned user does not work.
* `/unban` on a banned user will unban them.
* Sending a custom `m.room.members` with membership `leave` for a banned user will unban them.

That's effectively what this PR does, besides excluding `"kick"` from the list of actions that won't raise a `SynapseError`.

**Comment by anoadragon453** [comment]
@aaronraimist I think you may need to merge `develop` into your branch in order to fix the CI errors.

**Comment by aaronraimist** [comment]
Okay I'll look in to that soon.

Element will need a change as well though. Kicking in Element doesn't use the /kick API, it just sends a membership event.

**Review by richvdh — APPROVED** [review]
lgtm. Thanks!

[it'd be nice to have system tests for this in Complement, to make sure other server implementations don't fall into the same trap]

**Pull request merged**
