### PR TITLE
Reduce run-times of tests by advancing the reactor less

### PR DESCRIPTION
**Pull request by anoadragon453**
While working on the DINUM codebase I noticed some instances of `self.pump` being:

* Handed values expecting them to be seconds, while they're actually measured in hundreds of seconds.
* Handed values that were unnecessarily large to pass the test.

Both of these result in tests taking longer to run than necessary. Here's some time measurements I took on my machine when running these test(case)s before and after this PR:

```
tests.http.test_fedclient.FederationClientTests.test_closes_connection
0.454s -> 0.267s

tests.handlers.test_stats.StatsRoomTests.test_initial_earliest_token
1.365s -> 0.610s

tests.push.test_email.EmailPusherTests._check_for_mail
0.849s -> 0.375s

tests.util.test_retryutils.RetryLimiterTestCase.test_limiter
1.902s -> 0.997s

tests.storage.test_roommember.RoomMemberStoreTestCase
2.823s -> 2.268s
```

Small improvements, and maybe we could make larger ones (or even consider dropping `self.pump` for `self.reactor.advance`), but I'd keep that out of the scope of this PR.

### CODE REVIEW

**Comment by richvdh** [comment]
> Handed values expecting them to be seconds, while they're actually measured in hundreds of seconds.

they are measured in seconds, but we do it 100 times. The difference is important: advancing the reactor 100 seconds isn't much different to advancing it 1 second. Advancing it 100 times takes 100 times as long though :)

**Comment by anoadragon453** [comment]
@richvdh Ohh, indeed, pump creates an array of 100 values... that seems a bit excessive?

**Comment by anoadragon453** [comment]
Rebasing has eliminated quite a few of the `pump`s these PR originally had already. For the remaining `pump`s, switching them to just advancing the reactor once still reduces test run time.

**Review by richvdh — APPROVED** [review]
lgtm

**Pull request merged**
