### PR TITLE
setup.py: Add synapse console entry point

### LINKED ISSUE #1075: homeserver should be a script
The README says that we should run this to set up a homeserver:

`python -m synapse.app.homeserver`

This should be a script, just like synctl. It should be defined in the setup.py so we can call it directly after the project is installed, instead of calling with `python -m` and the module name.

### PR DESCRIPTION
**Pull request by kyrias**
Fixes #1075.

Signed-off-by: Johannes Löthberg <johannes@kyriasis.com>

### CODE REVIEW

**Comment by kyrias** [comment]
@NegativeMjark ping?

**Comment by ara4n** [comment]
> Mjark
15:09
Matthew: I don't know [whether we can merge that]. I remember adding those exact entry points and then I removed them because something didn't work. But I can't remember the details and don't have time to look into it.

**Comment by kyrias** [comment]
The only way it should ever work is if the `pkg_resources` module wasn't available, which sounds strange.  All it does is write out a script that uses setuptools to look up the entrypoint module in the package metadata and then tries to import and call it.

If he does figure out what went wrong for him, that would be interesting, because it sounds like a setuptools bug.

**Comment by hawkowl** [comment]
As per the reasoning in https://github.com/matrix-org/synapse/issues/1075 -- we shouldn't have an entry point, we should just have `python -m`. IMO, synctl should also probably be replaced with something called by `python -m`, to reduce confusion when using venvs and multiple Pythons.

**Pull request closed without merging**
