### PR TITLE
Add an index to event_search

### PR DESCRIPTION
**Pull request by richvdh**
also, add some more logging

### CODE REVIEW

**Comment by erikjohnston** [comment]
Is there a reason we make this more complicated and make it UNIQUE?

**Comment by richvdh** [comment]
> Is there a reason we make this more complicated and make it UNIQUE?

does that actually make it materially more complicated? I'd argue `register_background_index_update` ought to support UNIQUE indexes anyway, at which point the difference is a single param.

**Comment by erikjohnston** [comment]
> does that actually make it materially more complicated? I'd argue register_background_index_update ought to support UNIQUE indexes anyway, at which point the difference is a single param.

It's probably be fine, I don't think UNIQUE is that much slower than non unique indices

**Comment by richvdh** [comment]
> It's probably be fine, I don't think UNIQUE is that much slower than non unique indices

I'm struggling to imagine an implementation in which a unique index is not at least as fast as a non-unique one, for any given operation.

**Comment by erikjohnston** [comment]
> I'm struggling to imagine an implementation in which a unique index is not at least as fast as a non-unique one, for any given operation.

Specifically an INSERT as the the DB would then need to check whether the unique constraint was violated or not. OTOH, that's probably not any worse than just updating the index anyway.

**Pull request merged**
