### PR TITLE
Fix /purge_room admin API

### PR DESCRIPTION
**Pull request by erikjohnston**
Presumably broken since #6115

### CODE REVIEW

**Comment by rubo77** [comment]
So what were the consequences of this bug?

Since what version was it introduced?

**Comment by richvdh** [comment]
> So what were the consequences of this bug?

the purge_room api didn't work

> Since what version was it introduced?

as per the description

**Comment by rubo77** [comment]
#6115 was merged 30.9.2019 in 16cb9a71b8b46604d49944f0b9c316687becca93 on develop and mergid into v1.5.0: https://github.com/matrix-org/synapse/releases/tag/v1.5.0

so if you are on 1.5.0 and need the purge-api, hurry up updating ;)

**Comment by richvdh** [comment]
to be clear, purge_room != purge_history.

**Pull request merged**
