### PR TITLE
Improvements to the federation test client

### PR DESCRIPTION
**Pull request by richvdh**
Make it read the config file, primarily.

### CODE REVIEW

**Comment by erikjohnston** [comment]
I'd rather we didn't get rid of the ability to specify the the key file directly, as I often use it with test keys without wanting to have a dummy homeserver config.

**Comment by erikjohnston** [comment]
@matrixbot retest this please

**Comment by richvdh** [comment]
> I often use it with test keys without wanting to have a dummy homeserver config.

How? doesn't the remote server want to fetch the keys from us?

**Comment by erikjohnston** [comment]
> How? doesn't the remote server want to fetch the keys from us?

More accurately, I just have copies of keys on my devbox for jki.re and co.

**Comment by richvdh** [comment]
Fair enough. PTAL

**Pull request merged**
