### PR TITLE
Complement test image: capture logs from nginx

### PR DESCRIPTION
**Pull request by richvdh**
Have nginx send its logs to stderr/out, so that we can debug https://github.com/matrix-org/synapse/issues/13334.

### CODE REVIEW

**Comment by DMRobertson** [comment]
What went wrong? I guess stdout/stderr that nginx sees isn't the stdout/err of `configure_workers_and_start.py`, and it's the latter which forms the docker logging output?

**Comment by richvdh** [comment]
> What went wrong? I guess stdout/stderr that nginx sees isn't the stdout/err of configure_workers_and_start.py, and it's the latter which forms the docker logging output?

It was malformed nginx config. Turns out `docker/conf-workers/nginx.conf.j2` doesn't end up as top-level nginx config; rather it is included into the top-level config under the `http` section.

According to the [lazyweb](https://stackoverflow.com/a/42369571), the symlink hack is what the nginx docker container does.

**Comment by richvdh** [comment]
> I guess stdout/stderr that nginx sees isn't the stdout/err of configure_workers_and_start.py, and it's the latter which forms the docker logging output?

That wasn't the problem. `configure_workers_and_start` replaces itself with `supervisord`, which is [configured](https://github.com/matrix-org/synapse/blob/18c25c843d0e9400d8d6b235e5e8bda9a9df4460/docker/conf-workers/supervisord.conf.j2#L14-L17) to pipe the stdout of its nginx to its own stdout, so that bit does work.

**Review by DMRobertson — APPROVED** [review]
Thanks for explaining. SGTM, let's try it!

**Pull request merged**
