### PR TITLE
Move display name rule

### PR DESCRIPTION
**Pull request by dbkr**
As per https://github.com/matrix-org/matrix-doc/pull/373 and comment

Sorry github has made such a complete dog's dinner of this diff

### CODE REVIEW

**Comment by dbkr** [comment]
Hold on, this will affect more things than I thought.

**Comment by richvdh** [comment]
looks ok, except for:
* test fail
* needs a database migration

**Comment by erikjohnston** [comment]
@matrixbot ok to test

**Comment by erikjohnston** [comment]
LGTM

**Pull request merged**
