### PR TITLE
Allow enabling the asyncio reactor in complement

### PR DESCRIPTION
**Pull request by sandhose**
This allows enabling the asyncio reactor by setting the `ASYNCIO_REACTOR=1` environment variable.
It also adds jobs to the CI to run those in CI.

- Depends on #14092
- Part of #14091

### CODE REVIEW

**Review by reivilibre — CHANGES_REQUESTED** [review]
We discussed in #synapse-dev and decided that we'd probably prefer to make this a nightly, or a develop-only, run.
We also note that Erik has been running the asyncio reactor on his homeserver and it hasn't seemed to explode. I will add to that and say I have been running my homeserver with the asyncio reactor + uvloop's asyncio event loop since Monday and have not had any trouble yet.

**Comment by DMRobertson** [comment]
As noted [here](https://github.com/matrix-org/synapse/issues/14091#issuecomment-1278876520), the forking launcher fails with this change.

```
  2022-10-07 09:56:45,026 INFO spawned: 'synapse_fork' with pid 56
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.9/site-packages/synapse/app/complement_fork_starter.py", line 218, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/synapse/app/complement_fork_starter.py", line 152, in main
      installReactor(proxy_reactor)
    File "/usr/local/lib/python3.9/site-packages/twisted/internet/main.py", line 32, in installReactor
      raise error.ReactorAlreadyInstalledError("reactor already installed")
  twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed
  2022-10-07 09:56:45,608 INFO exited: synapse_fork (exit status 1; not expected)
```

Looks like we need to install the asyncio reactor here

https://github.com/matrix-org/synapse/blob/d6b85a2a7dea2737e69d67842c2246975ec64bce/synapse/app/complement_fork_starter.py#L103-L123

and somehow not install the asyncioreactor here??

https://github.com/matrix-org/synapse/blob/dc37b68a25754240243cdca6f521919abfe71db0/synapse/__init__.py#L31-L47

**Comment by DMRobertson** [comment]
> @DMRobertson I think I found a proper solution: [`1c71e6d`](https://github.com/matrix-org/synapse/pull/14099/commits/1c71e6d223f24da843cf2a536447ed939ee24fa0) ; let's see if CI passes.
> 
> It installs the asyncioreactor before loading the rest, and unsets the environment variable, so `__init__` doesn't try to reinstall the reactor

This didn't work out. To see the problem:

```
$ SYNAPSE_ASYNC_IO_REACTOR=1 python -v -m synapse.app.complement_fork_starter aa 2>&1 | grep -E 'import.*(synapse|reactor)'
import 'synapse.logging._remote' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c68574d60>
import 'synapse.logging._terse_json' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c68851d50>
import 'synapse.logging' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c68574910>
import 'synapse.logging.context' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c675fca90>
import 'synapse.util' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c695eb1c0>
import 'synapse.synapse_rust' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7f4c68851e10>
import 'synapse.util.rust' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c66b359f0>
import 'synapse.api' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c66b1d720>
import 'synapse.api.errors' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c66b1da80>
import 'synapse.util.stringutils' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c675e6860>
import 'twisted.internet.asyncioreactor' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c66bee2f0>
import 'synapse' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c695e9570>
import 'synapse.util.check_dependencies' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c66782950>
import 'synapse.app' # <_frozen_importlib_external.SourceFileLoader object at 0x7f4c66713a90>
```

I don't know how the import order is determined, but Python is importing the top-level synapse` module (hence installing the asyncio reactor) before it imports the complement_fork_starter.

Perhaps you could pass a `--asyncio` flag to the complement_fork_starter specifically?

**Comment by sandhose** [comment]
Superseded by #14858

**Pull request closed without merging**
