### PR TITLE
Refactor relations code to avoid duplication

### PR DESCRIPTION
**Pull request by clokep**
This is some pre-work towards #11753, it injects a handler layer between the rest and datastore layers, as much of our other code has.

A partial goal of this is to make the relations code a bit closer to the pagination code, so this mirrors more of the `RoomMessageListRestServlet` -> `PaginationHandler.get_messages()` -> `StreamWorkerStore.paginate_room_events()` flow.

### CODE REVIEW

**Comment by clokep** [comment]
There's probably a bit more we could refactor here, but I think this is enough for what I need for #11753.

**Comment by clokep** [comment]
> There's probably a bit more we could refactor here, but I think this is enough for what I need for #11753.

I do kind of feel like the `get_bundled_aggregations` (and maybe `_get_bundled_aggregation_for_event`) could be in here though? WDYT?

**Review by reivilibre — APPROVED** [review]

**Comment by reivilibre** [comment]
> I do kind of feel like the get_bundled_aggregations (and maybe _get_bundled_aggregation_for_event) could be in here though? WDYT?

I would think so, probably. If it looks hairier after you've done it then you'll know it was a bad move, but sounds about right to me :)

**Comment by clokep** [comment]
> > I do kind of feel like the get_bundled_aggregations (and maybe _get_bundled_aggregation_for_event) could be in here though? WDYT?
> 
> I would think so, probably. If it looks hairier after you've done it then you'll know it was a bad move, but sounds about right to me :)

Good shout! I think I'll do that in a follow-up since the changes in here are blocking other work. 👍

**Pull request merged**
