### PR TITLE
Prevent kicking users who aren't in the room

### PR DESCRIPTION
**Pull request by anoadragon453**
Prevent kick events from succeeding if the user is not currently in the room.

Closes https://github.com/matrix-org/synapse/issues/4973

Sytest PR: https://github.com/matrix-org/sytest/pull/602

### CODE REVIEW

**Comment by erikjohnston** [comment]
I wonder whether it'd be worth rewriting this so that we specifically said what transitions were allowed, rather than adding ad hoc rules.

**Comment by anoadragon453** [comment]
@erikjohnston https://github.com/matrix-org/sytest/pull/602 is approved as well?

**Comment by anoadragon453** [comment]
Could do, yeah.

**Comment by anoadragon453** [comment]
Although we're going to want custom error messages for what isn't allowed, which may end up looking quite close to the current code anyways.

**Comment by anoadragon453** [comment]
Left a TODO.

**Pull request merged**
