### PR TITLE
Add global notification count to sync endpoint

### PR DESCRIPTION
**Pull request by KentShikama**

### CODE REVIEW

**Comment by erikjohnston** [comment]
ok tot test

**Comment by erikjohnston** [comment]
ok to test, even

**Comment by KentShikama** [comment]
Actually let me double check something before this is merged.

**Comment by ara4n** [comment]
is this just summing all the per-room notif counts? shouldn't we do this clientside rather than sending redundant data from the server?

**Comment by KentShikama** [comment]
Conversation for why this would be useful: https://kentshikama.com/messenger/#/room/#vector-dev:matrix.org/$14686556611517EDanG:kentshikama.com

Essentially I need a way to poll for the total unread notifications without doing a full sync every couple of milliseconds.

Unfortunately, I just realized that if a filter is applied then this code might return a count that is less than I expect.

**Comment by ara4n** [comment]
how about doing a full sync but with everything filtered out? you'll still get the notif counts... also, why would you do this every few ms? isn't a blocking long poll good enough?

**Comment by KentShikama** [comment]
> how about doing a full sync but with everything filtered out? 

Yeah that was our initial implementation doing this every few ms. It still made the log file bloat up quite a bit.

A blocking long poll returns only the notification counts for a specific room (assuming it was a messaging event from that room). We could use a client side dictionary to add up notification counts but how will we decrement the count if a user read a room?

**Comment by ara4n** [comment]
If the notif count changes for a room (either up or down) it will be included in the /sync response. So the right way of doing this would be to just keep polling /sync with a 30 second timeout, filtering out all the events if you don't care about the specific data, and just summing the notif counts per room when they change.

**Comment by aoh0x7DE** [comment]
That's not quite how the filtering works. If all of a room's events for the current poll are filtered out, a change in the room's notif count will neither trigger the response nor cause the notification count to be included when the response is sent. As such, with or without the global count, we'll actually need to allow one event of every type that could change the number of notifications even though we're not interested in the event at all other than as a trigger for the response being sent.

In terms of summing the notif count per room, it's a possibility we considered, but I dislike it as a solution inasmuch as it requires the client to duplicate work being done by the server (i.e., keeping track of all rooms the user is in and their individual counts) and introduces the potential for some nasty errors should the client's model of what's going on diverge from the server's.

Whether this should be part of /sync is debatable, since it is, as you say, somewhat redundant with the data already included and does also still require the client to ask for a bunch of events they're not really interested in to get the changes in real time, but I think having a clean and simple way to track the total number of unread notifications is something that should be in the API.

**Comment by ara4n** [comment]
okay. surprised that filtering out events damages the notif count for that room; feels like a bug. we'll have a think about the best approach here :)

**Comment by KentShikama** [comment]
@ara4n What do you say about a PR that would make it so that the long poll would return when the notification count for any room changes?

**Comment by KentShikama** [comment]
@ara4n So I dug up this

"always_include(bool): Always include this room in the sync response, even if empty." 
from https://github.com/matrix-org/synapse/blob/master/synapse/handlers/sync.py#L945

and 

```
            if room_sync or always_include:
                notifs = yield self.unread_notifs_for_room_id(
                    room_id, sync_config
                )

                if notifs is not None:
                    unread_notifications["notification_count"] = notifs["notify_count"]
                    unread_notifications["highlight_count"] = notifs["highlight_count"]
```

from https://github.com/matrix-org/synapse/blob/master/synapse/handlers/sync.py#L1015

which is why the room isn't part of the sync result if it doesn't contain updates. Would you accept a solution which exposes the `always_include`? Currently `always_include` is set based on whether it is a full_state sync or not.

**Comment by erikjohnston** [comment]
Hey, sorry for dropping this on the floor. To be honest, it sounds like making a separate API would be best, since you're not trying to stream anything. You should be able to just pull the counts straight out of the database table `event_push_actions` via counts.

I'm closing this for now and adding it as a matrix-doc issue https://github.com/matrix-org/matrix-doc/issues/758. Feel free to reach out if you have any questions on how to implement the above.

**Pull request closed without merging**
