### PR TITLE
Auto remove messages after predefined timeout

### PR DESCRIPTION
**Pull request by cuongnv**
I created a script that can run as cronjob to auto remove with predefined timeout.
You can choose which rooms to remove with predefined timeout or vice versa. Also, It scripts can clean up database after removed message with redacted API

### CODE REVIEW

**Comment by rubo77** [comment]
Looks great,

Can you adapt this to PostgreSQL?

**Comment by cuongnv** [comment]
@rubo77 : Ok. I will :)

**Comment by rubo77** [comment]
there should be a postgres and an sqlite option, (maybe one in comments)

And don't forget a description in the head of the file (or add a readme)

**Comment by rubo77** [comment]
Please rebase and move the script in the new folder, we three or scripts went

**Comment by rubo77** [comment]
> @rubo77 : Ok. I will :)

what about your promise? ;)

**Comment by richvdh** [comment]
This PR seems to have gone stale, and needs work to clean it up. Closing it for now; feel free to open a new PR based on latest `develop` if you're still interested in working on it.

**Comment by cuongnv** [comment]
> > @rubo77 : Ok. I will :)
> 
> what about your promise?
> 
> _Tipp: About your 99 modified files: you should reset your branch to one commit before and rebase to current master instead of the mess you have done_ ;)

I did it. However, after run in long time (several months, remove too much messages (via cronjob 5min run once), it can slow down your server because server have to process many redact requests  and server itself implement some throttle control techique.
If you are still interested this solution, you can check my script in attachments.
[autoremove_v5.py.zip](https://github.com/matrix-org/synapse/files/3844395/autoremove_v5.py.zip)

**Comment by anoadragon453** [comment]
***Please do not just try running the above script on your database.***

In its current form, it will set the `content` field of events to an empty string, which is invalid. **This will break sync and likely other things**, as we saw [here](https://github.com/matrix-org/synapse/issues/9216#issuecomment-767482119).

**Pull request closed without merging**
