### PR TITLE
Contrib: Added a invite system (PHP) + Python-Twilio appservice + Python-plugin-bot

### PR DESCRIPTION
**Pull request by Torxed**
…ons, but works as a base model.

(And just realized the logo i made in gimp is more appropriate for a 3:d party front-end at best.. might need to change that)

### CODE REVIEW

**Comment by Torxed** [comment]
Added in a Python based appservice hook for twilio.com.

This enables sending sms from matrix.

**Comment by Torxed** [comment]
Added a submodule pointing towards:
 * https://github.com/Torxed/python-matrix-appSrv-bot

Essentially a rework of the twilio bot but more expanded to be general purpose.
 * Python bot
 * Plugin support (Dynamic event catching)
 * Does Email/SMS (both send() & recieve())

**Comment by ara4n** [comment]
hey @Torxed - this looks very cool indeed!  Sorry that nobody has got back to you on it; @erikjohnston has been drowning in synapse maintenance and PRs have been stacking up.

I'm not sure that contrib/ is the right place for this - the contrib directory really is for stuff which is very specific to synapse rather than the wider Matrix ecosystem, e.g. test-jigs for bits of synapse, or visualisation of synapse's internals.  I think you should host this in a dedicated github repo, just like all the other Matrix appservices are (including the ones from matrix.org) - it doesn't need to be tightly coupled to synapse, and folks can then deploy it and file issues etc as a project in its own right.  If you can provide a PR against matrix-org/matrix-doc we'll be happy to add it to the projects page on matrix.org too :)

**Comment by Torxed** [comment]
@ara4n Will do! :D Thanks for the input! :)

**Comment by Torxed** [comment]
@ara4n here's the repo :)
I will probably need help putting this into the docs, will try to fix the known issues this weekend as well, even tho this is a working copy.

https://github.com/Torxed/matrix-synapse-invite

**Pull request closed without merging**
