### PR TITLE
Downgrade warning on client disconnect to INFO

### PR DESCRIPTION
**Pull request by richvdh**
Clients disconnecting before we finish processing the request happens from time
to time. We don't need to yell about it.

### CODE REVIEW

**Comment by clokep** [comment]
Looks like the tests are unhappy with this change though.

**Comment by richvdh** [comment]
yeah, I've just ripped out the offending test: I don't really think we need to test that we're logging something here. Would appreciate a sanity-check though.

**Comment by clokep** [comment]
Looks like that test was testing whether the access token is redacted, which seems useful? I'm guessing this failed because tests don't log at INFO by default?

I don't have a strong opinion either way about that test though.

**Comment by richvdh** [comment]
> Looks like that test was testing whether the access token is redacted, which seems useful? I'm guessing this failed because tests don't log at INFO by default?  I'm guessing this failed because tests don't log at INFO by default?

well it would be useful, if we were logging the request URI at all. It fails because the new log message doesn't inclued the request URI.

**Pull request merged**
