### PR TITLE
only add new filter when not existent prevoisly

### PR DESCRIPTION
**Pull request by krombel**
To avoid more filters then really needed I would like to have unique filters.
What do you think of to check before adding the new filter if we not have already have one with the same definition?

### CODE REVIEW

**Comment by erikjohnston** [comment]
I don't think `json.dumps` necessarily encodes the same dict to the exact same bytes. It'd probably be better to use `encode_canonical_json` which does?

@matrixbot ok to test

**Comment by krombel** [comment]
I thought it would be good to check for the same dict that would get
inserted later if the filter does not exist.

Or do you think to replace `json.dumps` with another function in this
step as well?
>
> I don't think |json.dumps| necessarily encodes the same dict to the
> exact same bytes. It'd probably be better to use
> |encode_canonical_json| which does?
>

**Comment by erikjohnston** [comment]
Yeah, I'd replace `json.dumps(..)` with `encode_canonical_json(..)`

**Comment by erikjohnston** [comment]
(I like and approve of the idea though!)

**Comment by krombel** [comment]
I would replace `json.dumps(...)` with `encode_canonical_json(...)` in another step as it is used in other parts of synapse as well.
A simple `grep` over all .py-files of the repo shows, that `json.dumps(...)` is 66 and `encode_canonical_json(...)` 23 times used.

**Comment by erikjohnston** [comment]
Thanks!

**Pull request merged**
