### PR TITLE
Fix installation issues

### PR DESCRIPTION
**Pull request by ricco386**
I have tried to install accourding the README.rst, but I had a few issues. I have  updated file so it is installable on CentOS7 without errors.

Signed-off-by: Richard Kellner <richard.kellner@gmail.com>

### CODE REVIEW

**Comment by richvdh** [comment]
thanks!

A few points:
* I don't use CentOS, so can't assess this, but I am surprised that it is necessary. We use libsodium through PyNaCl, which ships with a copy of the libsodium sources, which gets built on installation. I have a suspicion that it wasn't installing libsodium itself which fixed things for you, but something else which got installed as a side-effect of installing libsodium.
* I would expect that upgrading `pip` made upgrading `setuptools` redundant.
* We need signoff, per https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off.

**Comment by ricco386** [comment]
You are right with the first part. libsodium is not needed as a system requirement on CentOS. My problem was that it crashed during the `setuptools` upgrade so I had to install libsodium to make it works. But when I do proper upgrade, e.g. I upgrade `pip` first, than  `setuptools` upgrade does not crash and PyNaCl build without problems.

However with the second bit it doesnt upgrade both at the same time. I have to upgrade `pip` as it doesnt upgrade `setuptools`, here is an output from my command line:

```
(.synapse)[root@rhce ~]# pip install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz#md5=35f01da33009719497f01a4ba69d63c9
  Downloading pip-9.0.1.tar.gz (1.2MB): 1.2MB downloaded
  Running setup.py egg_info for package pip
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
   
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '.landscape.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching '.github'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
Installing collected packages: pip
  Found existing installation: pip 1.4.1
    Uninstalling pip:
      Successfully uninstalled pip
  Running setup.py install for pip
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
   
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '.landscape.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching '.github'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
    Installing pip script to /root/.synapse/bin
    Installing pip2.7 script to /root/.synapse/bin
    Installing pip2 script to /root/.synapse/bin
Successfully installed pip
Cleaning up...
(.synapse)[root@rhce ~]#
(.synapse)[root@rhce ~]#
(.synapse)[root@rhce ~]# pip install --upgrade setuptools
Collecting setuptools
  Downloading setuptools-34.3.2-py2.py3-none-any.whl (389kB)
    100% |████████████████████████████████| 399kB 974kB/s
Collecting six>=1.6.0 (from setuptools)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting appdirs>=1.4.0 (from setuptools)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Collecting packaging>=16.8 (from setuptools)
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting pyparsing (from packaging>=16.8->setuptools)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 5.6MB/s
Installing collected packages: six, appdirs, pyparsing, packaging, setuptools
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools-0.9.8:
      Successfully uninstalled setuptools-0.9.8
Successfully installed appdirs-1.4.3 packaging-16.8 pyparsing-2.2.0 setuptools-34.3.2 six-1.10.0
```

When I try to upgrade in one command, eg.: `pip install --upgrade pip setuptools` it crashes during the process.

**Comment by richvdh** [comment]
Ok, great, thanks very much for your investigative work. I'm afraid I still need signoff on the original commits (sigh). Can you write a signed-off-by here?

**Comment by ricco386** [comment]
Sure no problem.

**Pull request merged**
