### PR TITLE
Fix bug caused by logging raw bytes and unicode

### PR DESCRIPTION
**Pull request by erikjohnston**
c.f. #3471

### CODE REVIEW

**Comment by erikjohnston** [comment]
(cc @ara4n who initially wrote this patch)

**Comment by ara4n** [comment]
by creating a new PR you've missed the fixes i've done to the original one based on vdh's review....

**Comment by ara4n** [comment]
i.e. this is a (broken) dup of https://github.com/matrix-org/synapse/pull/3470

**Comment by erikjohnston** [comment]
Oh, sorry, didn't see that you had already done it

**Pull request closed without merging**
