### PR TITLE
setup: add new devel_version variable for later usage

### PR DESCRIPTION
**Pull request by silvio**
This is only a reference implementation for discussion purposes.

Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>

### CODE REVIEW

**Comment by silvio** [comment]
two things: its not testet with not-git builds and if some one has checkedout a tag or a commit. I think the last one (commit checkout) will crash this implementation. But Its only a reference implementation.

**Comment by erikjohnston** [comment]
I quite like the idea of having the `__devel_version__`.

We already have a get_version_string() [1] that checks for a git environment at run time. This is currently only exposed as User-Agent and Server headers on HTTP request/responses, but this should also be exposed with a --version flag.

What would be really nice is if we could get a commit id in the version when installing via pip. This is currently done by asking github for the source tarball, so I'm unsure how feasible that is.

[1] https://github.com/matrix-org/synapse/blob/master/synapse/app/homeserver.py#L212

**Comment by erikjohnston** [comment]
Also, when we start building and uploading synapse to pypi we can apply the git commit then too.

**Comment by silvio** [comment]
@erikjohnston for the pip-version thing, it should enough to add the __devel_version__ to version in setup.py, or? like `version += "-" + devel_version`.
I can add the `--version`-option.
We can move the `get_version_string()` to the setup.py function and set from here the `__devel_version__` or `version`. The `get_version_string`-function is only one time [referenced].

[referenced]: https://github.com/matrix-org/synapse/blob/master/synapse/app/homeserver.py#L283

**Comment by erikjohnston** [comment]
> We can move the `get_version_string()` to the setup.py function and set from here the `__devel_version__` or version. The get_version_string-function is only one time referenced.

The problem there is that setup.py isn't run if you're actually running servers straight from a git checkout (which is done when developing). I think we currently hit functions in synapse package from setup.py(?), so its probably nicer to stick the `get_version_string` function somewhere nicer in the synapse package.

> I can add the `--version`-option.

That would be quite useful :)

> @erikjohnston for the pip-version thing, it should enough to add the devel_version to version in setup.py, or? like version += "-" + devel_version.

The problem is when/where setup.py gets run. If you do `pip install --process-dependency-links https://github.com/matrix-org/synapse/tarball/master` then setup.py will never get run in a git checkout.

**Pull request closed without merging**
