### PR TITLE
Fix typo in generated config

### PR DESCRIPTION
**Pull request by ThiefMaster**

### CODE REVIEW

**Comment by gary-kim** [comment]
It seems like your pull request is currently missing a changelog file and a sign off. You can find out about the changelog file [here](https://github.com/matrix-org/synapse/blob/develop/CONTRIBUTING.md#changelog) and sign off [here](https://github.com/matrix-org/synapse/blob/develop/CONTRIBUTING.md#sign-off).

**Comment by ThiefMaster** [comment]
It's a simple typo that has no technical effect whatsoever. I don't think this needs a changelog.

Regarding the changelog, this was a quick commit done via the GitHub web interface. I don't think I can amend my commit there to include a sign-off in the message, and to be honest, for a typo fix I don't really want to clone the repo locally...

**Comment by ThiefMaster** [comment]
OK, this PR has a nice consecutive number (7890), so I don't want it to end up closed. Updated with signoff and changelog...

**Comment by gary-kim** [comment]
Looks like you also need to regenerate the sample config according to the CI
```
docs/sample_config.yaml is not up-to-date. Regenerate it with `scripts-dev/generate_sample_config`.
```

**Comment by ThiefMaster** [comment]
Updated. The remaining CI failures seem to be unrelated.

**Comment by clokep** [comment]
Yeah, the CI failure is unrelated. Thanks for your contribution!

**Pull request merged**
