### PR TITLE
Allow registering admin users using the module API

### PR DESCRIPTION
**Pull request by nico-famedly**
Signed-off-by: Nicolas Werner <n.werner@famedly.com>

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by nico-famedly** [comment]
We basically have some external auth system, which we plug into synapse using the module API: https://gitlab.com/famedly/company/backend/services/synapse-token-authenticator

It would make our life quite a bit easier, if we could also use that to register the admin users we need and the change to do that looks fairly trivial, so I hacked it up real quick. :3

**Review by babolivier — CHANGES_REQUESTED** [review]
Looks pretty good to me, thanks! :)

I just have one comment (which I can't add to the diff unfortunately), under the line "Added in..." could you add something like:

> Changed in Synapse v1.56.0: add 'admin' argument to register the user as admin.

please?

**Comment by nico-famedly** [comment]
Added your proposal literally :3

**Review by babolivier — APPROVED** [review]
Looks good to me! Thanks! :)

**Pull request merged**
