### PR TITLE
Disable Registration Config Option

### PR DESCRIPTION
**Pull request by erikjohnston**

### CODE REVIEW

**Comment by dbkr** [comment]
Will this not also prevent ASes from registering users?

**Comment by erikjohnston** [comment]
Probably, it is a very blunt implementation mainly intended as a first cut for people setting up their own HS who are unlikely to be running ASes.

**Comment by NegativeMjark** [comment]
Might want to say that it blocks AS signup in the help?
Otherwise LGTM.

**Comment by dbkr** [comment]
If it's just a question of adding an "if login_type != LoginType.APPLICATION_SERVICE" and moving the code by a few lines, I think this would make this much more useful and less confusing.

**Comment by ara4n** [comment]
+1 to dave

**Comment by dbkr** [comment]
Perfect. :)

**Pull request merged**
