### PR TITLE
Add the packaging metadata to build the synapse snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds for adventurous users.

### CODE REVIEW

**Comment by elopio** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

If you upload the snap to the ubuntu store you will get a great way to deliver the software, and get transactional automatic updates. I've been testing the snap [1]. It still needs more testing, and some help from you to understand the remaining errors; but it seems to me good enough to publish in the edge channel, which will make it really easy to do crowd-testing before the stable release. 

If you have any doubts or comments, please let me know.

[1] https://gist.github.com/elopio/dffcda326f5b51feedeb09f012ac9a44

**Comment by elopio** [comment]
Thanks for reviewing. I'm reaching out to a few upstreams to gather feedback that will help us sort our backlog, so I appreciate a lot your comments.

In our sprint next week we have scheduled a discussion about the version string in the yaml, because it's a pain point also for me. We are probably going to add a --version flag to the snapcraft command, so it can be overwritten, but we'll have to discuss some other options first. For now, we can use a template like in https://github.com/syncthing/syncthing/pull/3636/files. I can also move it to the contrib folder if you prefer. There are some other projects like https://github.com/nextcloud/nextcloud-snap using a separate repo, which is a nice solution too. But I can't create repos in your organization, somebody from your team would have to do that.

As a side note, I've been experimenting on the other matrix projects. Do you think it would be useful if I send snapcraft metadata to them too? I'm personally interested in matrix because I want to steer my hackerspace away from telegram, as it never released the server source code. I think having snaps for riot and a few server implementations will make it easier. It's not a requirement of course, and we'll start testing it soon anyway, but I like snaps a lot :D

**Comment by elopio** [comment]
@erikjohnston ping. I'm wondering what to do next here.

**Comment by erikjohnston** [comment]
Sorry for dropping this on the floor, its been quite hectic here. I've created: https://github.com/matrix-org/package-synapse-snap so feel free to PR against that and I can merge :)

**Comment by erikjohnston** [comment]
(I shall close this for now, but please do PR against the repo! I would but I have no experience with snap)

**Comment by elopio** [comment]
@erikjohnston will do. Thanks.

**Comment by elopio** [comment]
https://github.com/matrix-org/package-synapse-snap/pull/1

**Pull request closed without merging**
