### PR TITLE
Use recaptcha_ajax.js directly from Google

### LINKED ISSUE #1932: Replace non-free recaptcha_ajax.js
Synapse ships minified non-free JavaScript at `synapse/static/client/register/js/recaptcha_ajax.js`.
Please either dynamically load it from Google’s CDN on demand, or replace it by a free alternative.

This is **not** related to the issue #1561.

### PR DESCRIPTION
**Pull request by andrewshadura**
The script recaptcha_ajax.js contains minified non-free code which
we probably cannot redistribute. Since it talks to Google servers
anyway, it is better to just download it from Google directly instead
of shipping it.

This fixes #1932.

### CODE REVIEW

**Comment by andrewshadura** [comment]
@richvd, ping?

**Comment by richvdh** [comment]
It's hard to see why we shouldn't do this, and in any case the form is completely unspecced, so I can't imagine much is relying on it.

**Comment by richvdh** [comment]
ghah, this was against the wrong branch; have reverted.

**Comment by richvdh** [comment]
and now merged to develop.

**Pull request merged**
