### PR TITLE
Allow config file path to be configurable in in synctl

### PR DESCRIPTION
**Pull request by illicitonion**
Also, allow it to be run from directories other than the synapse directory

### CODE REVIEW

**Comment by erikjohnston** [comment]
Does this support multiple files?

**Comment by illicitonion** [comment]
It does exactly as much as it used to...

**Comment by erikjohnston** [comment]
I'll takes that as a no :)

**Comment by illicitonion** [comment]
Not that I'm aware of :) But if there's some magical way in which it used it, it still will!

**Comment by erikjohnston** [comment]
LGTM

**Pull request merged**
