### PR TITLE
Explicitly add flake8 selections

### PR DESCRIPTION
**Pull request by ShadowJonathan**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

Part of #9366

### CODE REVIEW

**Comment by ShadowJonathan** [comment]
I used `flake8 setup.py -vvvv 2> flake8.txt` and https://flake8.pycqa.org/en/latest/user/violations.html#selecting-violations-with-flake8 to determine which selections are default, apart from flake8's default, `C4` (`flake8-comprehensions`) was the only other check that was turned on by default.

**Comment by clokep** [comment]
I'm a bit confused by this -- I thought the goal was to enable additional checks only for flake8-bugbear? If that's not possible, then I think we'll need to ignore all the ones that don't pass yet.

**Comment by ShadowJonathan** [comment]
I outlined it [here](https://github.com/matrix-org/synapse/pull/9320#issuecomment-773410951), but TL;DR: It's easier to individually add the checks to `select=` rather than remove them from `ignore=` one-by-one, the latter is more susceptible to merge conflicts, and it's easier to make git figure out the diff being "ah, just adding some lines here" rather than "oh, i need to remove this line, and this line, and this line...".

It's also simply easier to work with, and easier to observe explicitly enabled > implicitly enabled, i already created some other issues which touched on those explicitly-disabled checks, to create discussion to be able to remove them.

**Comment by clokep** [comment]
I'm not too keen to merge this as I'm not a huge fan of disabling these checks (i.e. if we never finish a project to enable bugbear and new checks get added to flake8 then we'll be missing out). I think the approach should be to disable just the bugbear checks and start fixing those issues individually.

**Pull request closed without merging**
