### PR TITLE
Check room exists when authenticating an event

### PR DESCRIPTION
**Pull request by erikjohnston**
This breaks setting an alias for a room ID that doesn't exist yet, which is probably a feature. Though it does break a sytest test.

### CODE REVIEW

**Comment by NegativeMjark** [comment]
In particular it fails sytest/tests/50federation/11query-directory.pl.

Which seems to be making a request to:

    PUT https://localhost:8001/_matrix/client/api/v1/directory/room/%2350federation-11query-directory:localhost:8001
    Host: localhost
    Content-Type: application/json
    
    {"room_id":"!the-room-id-for-test:example.org","servers":["example.org"]}

**Comment by erikjohnston** [comment]
Yup, I assume it just needs for that room to be created first.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/sytest/pull/12

**Comment by erikjohnston** [comment]
Sytest should now be happy with this.

**Comment by NegativeMjark** [comment]
LGTM

**Pull request merged**
