### PR TITLE
change 'Home Server' to one word 'homeserver'

### LINKED ISSUE #11264: Documentation uses the term "Home Server" in multiple places
The protocol decided long ago that it was "homeserver" (one word). A find & replace all should fix the majority of instances. 

Noticed in the TURN docs.

### PR DESCRIPTION
**Pull request by Ashwin-exe**
### Pull Request Checklist
Changed the 'Home Server' word  to 'homeserver' as mentioned [here](https://github.com/matrix-org/synapse/issues/11264#issue-1046259412)
Closes #11264

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [ ] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by babolivier** [comment]
Hey, thanks for your contribution! Could you please follow the steps in the checklist in the PR's description? Namely adding a changelog and a sign-off :)

**Comment by Ashwin-exe** [comment]
> 
> 
> Hey, thanks for your contribution! Could you please follow the steps in the checklist in the PR's description? Namely adding a changelog file and a sign-off :)

Done. 👍

**Comment by babolivier** [comment]
> > Hey, thanks for your contribution! Could you please follow the steps in the checklist in the PR's description? Namely adding a changelog file and a sign-off :)
> 
> Done. :+1: 

Thanks! However it looks like:

1. the changelog file isn't in the right format (it's showing as a binary file but should be plain text)
2. the pull request is still missing a sign-off

**Comment by Ashwin-exe** [comment]
> > > Hey, thanks for your contribution! Could you please follow the steps in the checklist in the PR's description? Namely adding a changelog file and a sign-off :)
> > 
> > Done. :+1: 
> 
> Thanks! However it looks like:
> 
> 1. the changelog file isn't in the right format (it's showing as a binary file but should be plain text)
> 2. the pull request is still missing a sign-off

I don't know why, my changelog file is showing plain text on my system but showing binary file on github.

Also tried to ask in the matrix group but looks like i'm making mistake somewhere.

+1 also tried to make a file on github it self but still showing binary file

**Comment by reivilibre** [comment]
@Ashwin-exe It looks like you used a word document, which is not the same as plain text. (Since it's able to contain images and formatting, for example, it can't just use plain text.)
To create a plain text file, the same editor you used for your code should be able to do it. On Windows, Notepad++ is one tool that can do this properly — maybe plain Notepad too but it probably uses Windows-style line endings.

**Comment by richvdh** [comment]
given this is just a minor edit to the docs, a newsfile may not be required.

**Comment by Ashwin-exe** [comment]
> 
> 
> @Ashwin-exe It looks like you used a word document, which is not the same as plain text. (Since it's able to contain images and formatting, for example, it can't just use plain text.) To create a plain text file, the same editor you used for your code should be able to do it. On Windows, Notepad++ is one tool that can do this properly — maybe plain Notepad too but it probably uses Windows-style line endings.

 yaa it was because of the Windows-style line endings, Notepad++ works for me. Thanks, @reivilibre :)

**Review by babolivier — APPROVED** [review]
Thanks! :)

**Pull request merged**
