### PR TITLE
Stop forcing xz compression for Debian packages

### PR DESCRIPTION
**Pull request by behrmann**
### Pull Request Checklist

This PR drops the `override_dh_builddeb` introduced in #11197, since the mentioned reprepro is available in all still supported Debian version (also the ones no longer supported by Synapse) and the also mentioned Ubuntu version is no longer supported by Synapse.

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by richvdh** [comment]
Our dev team run `reprepro` in a number of non-debian environments, including Arch and Fedora, where reprepro is still stuck on older versions.

So, I don't think this is currently worthwhile.

**Comment by richvdh** [comment]
> and the also mentioned Ubuntu version is no longer supported by Synapse.

yes, but presumably (I haven't checked) later versions of Ubuntu (22.04, etc) have the same problem as impish, in that they also default to zstd?

**Comment by behrmann** [comment]
> yes, but presumably (I haven't checked) later versions of Ubuntu (22.04, etc) have the same problem as impish, in that they also default to zstd?

Yes, I don't think they will change (until something better comes along). I'm quite surprised actually, that Debian hasn't made the switch, since unpacking time on Arch has improved since they switched.

> Our dev team run `reprepro` in a number of non-debian environments, including Arch and Fedora, where reprepro is still stuck on older versions.

On Arch it is in version 5.4.1 and on Fedora 36 it was on 5.3 and seems to be on the same version in Fedora 37 and Rawhide, so that [should have resolved itself](https://pkgs.org/download/reprepro)

> So, I don't think this is currently worthwhile.

No worries, feel free to close this PR. I just looked at this between the other stuff and wondered if it was a drive-by fix. :)

**Comment by richvdh** [comment]
> On Arch it is in version 5.4.1

as of last night, yes :innocent: 

> and on Fedora 36 it was on 5.3 and seems to be on the same version in Fedora 37 and Rawhide, 

Right, but it's a version of 5.3.0 which is older than the 5.3.0-1.3 which introduces this feature.

**Comment by richvdh** [comment]
Looks like we're blocked on https://bugzilla.redhat.com/show_bug.cgi?id=2108872.

**Pull request closed without merging**
