### PR TITLE
Fix auth handler

### PR DESCRIPTION
**Pull request by jkolo**
#2678

### CODE REVIEW

**Comment by richvdh** [comment]
:+1:  thanks

**Comment by richvdh** [comment]
(normally I would ask for sign-off as per CONTRIBUTING.rst but I hope you're not going to assert copyright over 7 characters)

**Comment by richvdh** [comment]
gah also please PR against develop, not master

**Comment by richvdh** [comment]
now merged to develop as 624a8bb.

**Comment by bennabiy** [comment]
Worked for me.

**Pull request merged**
