### PR TITLE
Replace mentions of Vector with Riot

### PR DESCRIPTION
**Pull request by axelsimon**
https://github.com/vector-im/vector-web/issues/1977 --> https://github.com/vector-im/riot-web/issues/1977
And mention of Vector as a client replaced with Riot.

### CODE REVIEW

**Comment by neilisfragile** [comment]
Hi @axelsimon thanks for the PR, I know it's a pain but can you take a look at https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst 

I need 
 * your sign off and 
 * an entry in Changes.d/ and please credit yourself!
 * base off develop branch, not master

**Comment by axelsimon** [comment]
Right, I've changed the base branch from master to develop and signed off. I also created a PRnumber.type file in changelog.d in my axelsimon-patch-1 branch, but I'm not sure that's being picked up by this PR (although Github tells me "Add more commits by pushing to the patch-1 branch on axelsimon/synapse")

I think I'm missing something, any clues would be appreciated :)

**Comment by turt2live** [comment]
Your branch would be `patch-1` not `axelsimon-patch-1`.

**Comment by richvdh** [comment]
(and you'd need to remember to `git push` your changes)

**Comment by richvdh** [comment]
I think we can take this without a newsfile.

**Comment by axelsimon** [comment]
Thanks Rich!

**Comment by eMPee584** [comment]
…by the way, who on EARTH came up with that violent name, and how did the group process converge into choosing it?!
seriously, **vector** is a _much_ more appealing name, especially in academics. WTH.

**Comment by ara4n** [comment]
i’d argue the name (which can refer as much to a riot of colour, as to a riot of violence) is less violent than your comment.

**Pull request merged**
