### PR TITLE
Transfer widgets on room upgrade

### PR DESCRIPTION
**Pull request by anoadragon453**
Transfer room widgets on room upgrade.

Sytest PR: https://github.com/matrix-org/sytest/pull/603

Closes https://github.com/matrix-org/synapse/issues/4994

### CODE REVIEW

**Comment by erikjohnston** [comment]
Do we expect blindly copying widgets to work? Will this cause scalar to get confused with a widget being in a different room that it expects?

**Comment by anoadragon453** [comment]
Lemme test.

**Comment by anoadragon453** [comment]
Looks like it does indeed work.

**Comment by anoadragon453** [comment]
@rxl881 @jaywink Do you know whether sending the same 'add widget' event to another room would break anything? I know the state event in the second room would have the room ID of the first room, but I don't think that's actually used for anything other than for something unique.

**Comment by jaywink** [comment]
I don't see why it would be a problem, not from Scalar's point of view at least. As the [spec says](https://docs.google.com/document/d/1re56Br1wd4Tcw6j4ptZk3lMRmSbVbXb2lAzkudwnPvc/edit#heading=h.jlbxn2sglb5k), room based widgets are stored in room state. Scalar doesn't store room widgets.

Might be worth waiting for @rxl881 though and also possibly @turt2live might want to have a look?

**Comment by turt2live** [comment]
None of my stuff should care about the room ID it lives in, and if it does then I'd call that a bug in my stuff. I think Scalar might get confused about etherpad widgets migrating rooms because it appears to expect the pad name to be the room ID, however use of the widget should be fine.

**Comment by anoadragon453** [comment]
Have tested with an etherpad and was able to successfully share a 
document using the same pad in both rooms so... all good?

**Comment by turt2live** [comment]
This is more of my concern, which is probably a Scalar bug:
image
image

(manually copied the widget verbatim into a new state event in a new room)

**Comment by anoadragon453** [comment]
Oh, well, yeah that's just a Scalar bug. Time to file!

**Comment by erikjohnston** [comment]
What about things like go-neb which post stuff into the room? Doesn't something need to poke it to ensure it knows about the new room?

**Comment by anoadragon453** [comment]
@erikjohnston I think this would be up to go-neb to recognize a tombstone event in the sync stream and inform each plugin that a room has been upgraded, rather than a server thing.

**Comment by erikjohnston** [comment]
On further discussion with folk it sounds like scalar very much is planning to store per room per widget state, so we need to be a little bit careful here. On top of that we'd also want to support migrating integrations etc, which also have state, so we've decided to punt this for now until we have time to have a proper think about how this should all work.

**Comment by richvdh** [comment]
This also sounds like an important datapoint in the "should we just copy all the state over" debate?

Does this mean that #4994 is now descoped, or?

**Comment by anoadragon453** [comment]
I believe so. Holding pen

**Pull request closed without merging**
