### PR TITLE
Always calculate heroes for rooms without avatars

### PR DESCRIPTION
**Pull request by ara4n**
Otherwise clients may not have the membership events they need to generate an avatar for the room (typically a 1:1, but if a client chose to montage together multiple avatars, that'd break too)

Tests over at https://github.com/matrix-org/sytest/pull/493

### CODE REVIEW

**Comment by ara4n** [comment]
@matrixbot retest this please

**Comment by ara4n** [comment]
@matrixbot please retest this again

**Comment by ara4n** [comment]
retest this please

**Comment by erikjohnston** [comment]
How bad would it be if we always sent down heroes? It doesn't feel like it'd add that much overhead, and yet be a lot simpler? That way we don't have to guess if/when a client would want them (it would also allow the client to always show some members in a room while they're loading the rest?)

**Comment by richvdh** [comment]
see also #5089 which appears to duplicate some of the work done while this has been bit-rotting :/

**Comment by clokep** [comment]
I think this would need to be rebased and it sounds like at least some of this was done already. I'm going to close this.

**Pull request closed without merging**
