### PR TITLE
update debian installation instructions to recommend installing `virtualenv` instead of `python3-virtualenv`

### PR DESCRIPTION
**Pull request by txt-file**
replace python3-virutalenv by virutalenv as the latter provides the command

### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [X] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by richvdh** [comment]
please could you clarify what problem this is solving and why it is the correct way to solve it?

**Comment by txt-file** [comment]
On line 52 of INSTALL.md the virtualenv command is executed. In debian this command is in the packag "virtualenv". With only python-virtualenv there is no virtualenv command.

This pull request is work in progress as it is also missing the proper signed-of line.

**Comment by richvdh** [comment]
right yes, I see what you mean.

For (my own, mostly) reference: the `virtualenv` package has used python3 since at least [jessie](https://packages.debian.org/jessie/virtualenv). This used to work better because we [used to](https://github.com/matrix-org/synapse/pull/6443) suggest installing `python-virtualenv`, which was wrong but `python-virtualenv` recommends `virtualenv`.

If you could add a sign-off to the PR description, we can merge this. Thanks!

**Comment by anoadragon453** [comment]
@txt-file are you still around to update this?

**Comment by txt-file** [comment]
@anoadragon453 yes … Better I do it now instead of forgetting it again. ;-)

**Pull request merged**
