### PR TITLE
Add sleep timer of 0.1s in history purge

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by richvdh** [comment]
I'm not sure what this is trying to achieve, but putting calls to `sleep` in twisted code certainly isn't the right way to achieve it...

**Comment by rubo77** [comment]
The goal is, that during a purge call the front-end stays not responsive.

Atm it is like this, that the server is 100% blocked until all clearing is done.

If there were some pauses in the code,  some minor actions could be done on the front-end in between

**Comment by richvdh** [comment]
you can't just put sleeps in twisted code. It freezes the whole reactor.

you may want `synapse.util.async.sleep`, but you'll have to learn about twisted's deferred mechanism first.

In any case, I'm not sure about the wisdom of allowing other things to carry on while the purge is in progress. Perhaps @erikjohnston can comment.

**Comment by ara4n** [comment]
i'm going to close this as it's not the right solution, unfortunately, and i'm also not sure it's a massive problem.

**Comment by rubo77** [comment]
If this is a Problem them only with sqlite db

**Pull request closed without merging**
