### PR TITLE
Make /sync attempt to return device updates for both joined and invited users

### PR DESCRIPTION
**Pull request by ara4n**
This means that we can encrypt for invited users' devices before that user joins the room if the client wants.

[was intended for vector-im/riot-web#2713, but does not actually fix it]

Fwiw the clientside patches required for matrix-js-sdk and matrix-react-sdk are: https://github.com/matrix-org/matrix-js-sdk/pull/666 and https://github.com/matrix-org/matrix-react-sdk/pull/2042.

### CODE REVIEW

**Comment by ara4n** [comment]
As per matrix-js-sdk#666 this doesn't work, and in fact introduces a slight regression, as invited users who add devices between being invited and joining will no longer ever tell the room participants about these new devices (whereas previously they would be synced when the user joined the room).

This has been merged for dinsic (via the matthew/dinsic-encrypt-for-invited-users branch) but before we merge this to develop, we need to either work out how to trigger a resync of the devicelist when the user transitions from invite->join, or have some other way of synchronising devicelists implemented.

**Comment by ara4n** [comment]
Turns out this doesn't introduce a regression, as clients resync the devicelist by querying /unstable/keys/query every time the membership list changes.  However, it also doesn't help anything either due to #3503.

There's a sytest that asserts that /keys/query works for invited users (which it did already, apparently), and then a broken sytest for #3503 committed at https://github.com/matrix-org/sytest/pull/462.

**Comment by richvdh** [comment]
I'm a bit confused about what's going on here. I think it needs more work?

**Comment by ara4n** [comment]
not sure what to do with this.
 * it's a step in the right direction
 * but it doesn't help anything because of #3503
 * it got merged to the dinsic branch before we realised that it wasn't actually helping much

my hunch is probably to merge it to avoid repetition of work in future, even though in practice for it to actually improve things a bit it would need #3503 to be fixed and a solution for #3504 to be found.

**Comment by richvdh** [comment]
ok, for clarity: this does *not* fix vector-im/riot-web#2713. Will update the description accordingly so that it hopefully doesn't get auto-resolved.

**Pull request merged**
