### PR TITLE
Allow listening on UNIX sockets for HTTP listeners

### PR DESCRIPTION
**Pull request by auscompgeek**
Opening for preliminary review and CI run. Docs forthcoming after the sun comes back up at my end of the Earth, hopefully.

Closes: #4975

## Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

### CODE REVIEW

**Comment by auscompgeek** [comment]
This could probably do with a quick glance over now. I'll hopefully get docs written for this tomorrow.

A couple of open questions:
- https://github.com/matrix-org/synapse/pull/8103/files#diff-01aac508ef38061957e6fb961582e5ceR320
- Should the logging I'm adding be at ERROR?

**Comment by richvdh** [comment]
>     * https://github.com/matrix-org/synapse/pull/8103/files#diff-01aac508ef38061957e6fb961582e5ceR320
>     * Should the logging I'm adding be at ERROR?

Yes, I'd have thought it would be preferable to emit errors and bail than to carry on with warnings.

In general, it would be preferable to pick this sort of problem up during config parsing, which means that they will be reported before synapse forks (if it's run in daemonize mode) and can be reported by a config checker (cf #8160). Basically you can raise a `ConfigError` to get sensibly formatted output.

Some other thoughts:
* it would be nice to add some type annotations for the new parameters, so that we know what a `socket_options` is.
* could we have a generic `_listen_socket` function which takes a `Union[TcpListenerConfig, UnixListenerConfig]` and delegates to one of `_listen_tcp`, `_listen_ssl`, `listenUNIX` as appropriate? it seems like we have lots of copies of the same code, some of which seem unnecessarily restricted to not support unix socketts.

**Comment by clokep** [comment]
@auscompgeek Curious if you have plans to keep working on this?

**Comment by auscompgeek** [comment]
Oops, sorry, I forgot this was on my queue…

This has simply been held back by my lack of time to actually work on this. I'd like to see this get across the line, but I'll be preoccupied for at least the next couple of weeks.

**Comment by erikjohnston** [comment]
@auscompgeek I'm going to close this for now, but feel free to reopen if you get time to work on it some more!

**Pull request closed without merging**
