### PR TITLE
Add jitsi config

### PR DESCRIPTION
**Pull request by manju-rn**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by manju-rn** [comment]
This PR adds a json configuration to .well-known/matrix/client for jitsi configuration. This resolves the issue as raised in <https://github.com/matrix-org/synapse/issues/8739>.

**Comment by squahtx** [comment]
@manju-rn Thank you for contributing to Synapse! While this PR does fix the issue encountered by some users in #8739, we were hoping for a more generic solution along the lines of samiraguiar's suggestion (https://github.com/matrix-org/synapse/issues/8739#issuecomment-762844178), ie. a config option holding a dict or specifying a json file that gets merged into the `.well-known/matrix/client` response. Do you think you could implement something like that?

**Comment by squahtx** [comment]
#8739 is about all possible customizations and not just jitsi. We would like to allow server admins to [configure "io.element.e2ee"](https://github.com/vector-im/element-web/blob/develop/docs/e2ee.md#secure-backup), for example.

**Comment by manju-rn** [comment]
> #8739 is about all possible customizations and not just jitsi. We would like to allow server admins to [configure "io.element.e2ee"](https://github.com/vector-im/element-web/blob/develop/docs/e2ee.md#secure-backup), for example.

okay. don't think I would go into that as of now. So this PR is rejected?

**Comment by squahtx** [comment]
> okay. don't think I would go into that as of now. So this PR is rejected?

That's unfortunate to hear. We're going to have to decline this PR for now.
If you ever feel up for it, a PR that handles arbitrary customizations would be very welcome.

**Pull request closed without merging**
