### PR TITLE
Validate input parameters for the sendToDevice API.

### PR DESCRIPTION
**Pull request by clokep**
Properly handle if the `messages` parameter isn't provided.

See https://sentry.matrix.org/sentry/synapse-matrixorg/issues/127685/

### CODE REVIEW

**Review by anoadragon453 — COMMENTED** [review]
Hmm, [according to the spec](https://matrix.org/docs/spec/client_server/r0.6.1#put-matrix-client-r0-sendtodevice-eventtype-txnid) this field isn't required, though I assume it should be. For right now we may just want to assume `messages` is an empty dict and return `200, {}`?

I've created an issue to try and get some discussion going on this from the spec side: https://github.com/matrix-org/matrix-doc/issues/2927

**Comment by clokep** [comment]
@anoadragon453 Good thought to check the spec! 👍 I modified this PR to only process `messages` if it exists.

**Comment by clokep** [comment]
Actually, if this is considered a spec bug, should we rollback the last commit (not the merge) and just require the field?

**Comment by anoadragon453** [comment]
> Actually, if this is considered a spec bug, should we rollback the last commit (not the merge) and just require the field?

Yeah, given Travis' response it looks like it's going to go the way of being required without MSC, so we may as well align ourselves in the same way here.

**Review by anoadragon453 — APPROVED** [review]

**Comment by anoadragon453** [comment]
This was fixed in an unreleased version of the spec: https://github.com/matrix-org/matrix-doc/issues/2927

**Pull request merged**
