### PR TITLE
encode sync-response statically

### PR DESCRIPTION
**Pull request by krombel**
Motivation:
1. I would like to use the `encode_*`-methods statically to avoid duplication of code e.g. for WebSocket-Usage.
2. I wanted to reduce the used data by omiting objects that are empty. As matrix-js-sdk (e.g.) checks if the objects are empty or not I think it should be secure to omit them from a response.

Signed-off-by: Matthias Kesler <krombel@krombel.de>

### CODE REVIEW

**Comment by erikjohnston** [comment]
@matrixbot test this please

**Comment by erikjohnston** [comment]
> I would like to use the encode_*-methods statically to avoid duplication of code e.g. for WebSocket-Usage.

This is fine


> I wanted to reduce the used data by omiting objects that are empty. As matrix-js-sdk (e.g.) checks if the objects are empty or not I think it should be secure to omit them from a response.

This requires a bunch more caution, the js sdk is definitely not the only client out there. I think it may be best if these two were separate PRs so that we can merge the first point without being blocked on discussing the second?

**Comment by krombel** [comment]
OK. I now reverted the changes to just contain the changes to allow static access.
I will open a "reduce"-PR after this got merged to allow further discussion just on that topic.

**Comment by erikjohnston** [comment]
@matrixbot test this please

**Comment by erikjohnston** [comment]
LGTM; thanks!

**Pull request merged**
