### PR TITLE
State chache

### PR DESCRIPTION
**Pull request by erikjohnston**

### CODE REVIEW

**Comment by NegativeMjark** [comment]
Do we ever need to evict entries from the cache? Do we expect a server's view of the state before an event to change?

**Comment by NegativeMjark** [comment]
It'd be nice to log some hit/miss counters for the cache.

**Comment by erikjohnston** [comment]
We evict entries in def _prune_cache(self):

**Comment by NegativeMjark** [comment]
Sorry I meant: Do we need to evict entries from the cache upon receiving a new old state event?

**Comment by NegativeMjark** [comment]
Otherwise LGTM.

**Comment by erikjohnston** [comment]
We never update the state group after the initial persistence. That will probably change at some point, but that is fine for now.

**Pull request merged**
