### PR TITLE
Add config option to block users from looking up 3PIDs

### PR DESCRIPTION
**Pull request by babolivier**
Not sure this config option belongs to `register.py` since it has nothing to do with registration, however there's no `identity.py` file and all of the IS settings are there, so I figured I'd put that in there as well.

### CODE REVIEW

**Comment by babolivier** [comment]
Hmm, I meant to add some tests, but I'm not sure how to test that...

**Comment by erikjohnston** [comment]
> Hmm, I meant to add some tests, but I'm not sure how to test that...

It's actually not too bad to do a quick test, can IRL

**Comment by erikjohnston** [comment]
FTR: This doesn't stop clients from talking directly to the identity server to do lookups.

**Comment by erikjohnston** [comment]
@babolivier: We will also want to merge this into dinsic branch

**Pull request merged**
