### PR TITLE
Fix empty scope when having version mismatch between workers

### PR DESCRIPTION
**Pull request by MatMaul**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog).
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by MatMaul** [comment]
Turns out that this is because we do rolling restart and there is a mismatch in replication messages while the 2 versions are still inflight. I am closing this and adding a note to the upgrade notes instead.

**Comment by MatMaul** [comment]
After more discussion, we will add this simple fix.

**Review by DMRobertson — COMMENTED** [review]
SGTM (though a short unit test wouldn't go amiss maybe?)

**Review by DMRobertson — APPROVED** [review]
Have a :heavy_check_mark:

**Pull request merged**
