### PR TITLE
Fixes #12482 : Remove undocumented device from /pushrules

### LINKED ISSUE #12482: synapse returns undocumented `device` property from `GET /_matrix/client/v3/pushrules/`
Synapse's response to a `/pushrules` query looks something like:

```json5
[
  "global": {
    "content": { /*... */ },
    "override": { /*... */ },
    "room": { /*... */ },
    "sender": { /*... */ },
    "underride": { /*... */ }
  },
  "device": {}
]
```

This `device` property is not [specced](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3pushrules) and should be removed.

### PR DESCRIPTION
**Pull request by JeyRathnam**
Signed-off-by: Jeyachandran.rathnam [jeyrathnam@proton.me](mailto:jeyrathnam@proton.me)

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by DMRobertson** [comment]
FYI if you write `Fixes #12482` in the PR description then Github will automatically mark this PR as closing that issue.

**Review by DMRobertson — COMMENTED** [review]
Looks good, but I want to double-check no-one is relying on this before we merge.

See https://github.com/matrix-org/synapse/issues/12482#issuecomment-1352936948

**Comment by JeyRathnam** [comment]
@DMRobertson I am not sure why this issue closed, I dont remember closing it.

**Comment by clokep** [comment]
@JeyRathnam You should be able to reopen (and maybe merge in `develop`)!

**Comment by clokep** [comment]
Replaced by #14727.

**Pull request closed without merging**
