### PR TITLE
Put SAML callback URI under /_synapse/client.

### PR DESCRIPTION
**Pull request by richvdh**
Largely for consistency with OIDC, but also just to tidy it up while we're in the area.

Based on #9288.

(Unlike #9288, we can preserve backwards-compat simply by making both the old and the new endpoints work, because in the case of SAML, the redirectUrl is stored at the SAML IdP).

### CODE REVIEW

**Review by clokep — APPROVED** [review]
I think this is OK, but the diff is a bit hard to read.

**Comment by clokep** [comment]
Should we also do `/login/cas/ticket` while we're at it? I don't think this is part of the C-S spec?

**Comment by richvdh** [comment]
> Should we also do /login/cas/ticket while we're at it? I don't think this is part of the C-S spec?

yeeees, but that's defined as a `Servlet` rather than a `Resource`, which makes it more fiddly to move :)

**Comment by richvdh** [comment]
rebased; hopefully the diff will be clearer.

**Pull request merged**
