### PR TITLE
Fix /keys/query API on workers.

### PR DESCRIPTION
**Pull request by erikjohnston**
The necessary getters were added only to the master store and not the
worker stores.

### CODE REVIEW

**Comment by erikjohnston** [comment]
I think this was broke in #5769

**Comment by richvdh** [comment]
shame this wasn't picked up in any tests

**Comment by erikjohnston** [comment]
I'm updating the worker routes on sytest to match those in `docs/workers.rs`, which should hopefully pick this up

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/sytest/pull/732 hopefully tests this

**Pull request merged**
