### PR TITLE
Split out the federation reading portions into a separate. 

### PR DESCRIPTION
**Pull request by erikjohnston**

### CODE REVIEW

**Comment by NegativeMjark** [comment]
LGTM but we should probably get jenkins working before landing it.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/sytest/pull/274
https://github.com/matrix-org/dendron/pull/31

**Comment by erikjohnston** [comment]
@matrixbot test this please

**Comment by erikjohnston** [comment]
@matrixbot test this please

**Comment by erikjohnston** [comment]
@matrixbot test this please

**Pull request merged**
