### PR TITLE
Update `user_filters` table to have a unique index, and non-null columns

### PR DESCRIPTION
**Pull request by pik**
Swaps the `user_filter` Table index to Unique, the current code does not use a single transaction or optimistic locking. 

https://github.com/matrix-org/synapse/blob/master/synapse/storage/filtering.py#L43

Not sure on the procedure for PRing schema changes, so let me know if I'm missing something.

### CODE REVIEW

**Comment by erikjohnston** [comment]
@pik The way the schema upgrade stuff works is that we create a new "version" after every release, so creating a new 37 is the correct thing to do here since 36 is the latest in the release. You will need to bump the `SCHEMA_VERSION` in `synapse/storage/prepare_database.py` when bumping the version.

@matrixbot ok to test

**Comment by erikjohnston** [comment]
@matrixbot retest this please

**Comment by erikjohnston** [comment]
Hmm, this might require some more thought given its going to break starting synapse if it has duplicate filter ids.

**Comment by pik** [comment]
Yeah probably needs to come with a pre-migration 'clean-up-task'. I will update.

**Comment by pik** [comment]
So I see the current `prepare_database.py` code runs the sql from the files directly  - I'm having some difficulties in writing `sqlite3` and `postgresl` compatible code (specifically sqlite3 uses GROUP BY to achieve an effect that postgres is DISTINCT ON) - thoughts on a nice way to specify DB specific migrations? Or otherwise perhaps allow prepare_database.py to alternatively read `.py` files with a `migrate` method which takes a config file or db_engine as an argument?

**Comment by pik** [comment]
Ah, apologies, it seems what I am asking about already exists (still navigating my way around the code-base). Updated.

**Pull request merged**
