### PR TITLE
Disable push rule evaluation for rooms excluded from sync

### PR DESCRIPTION
**Pull request by mcalinghee**
Purpose of this PR : This PR use the setting `exclude_rooms_from_sync`to avoid the notification to be generated in `action_for_event_by_user`.

As part of the Tchap mainlining, `exclude_rooms_from_sync` was introduced to ease the user discovery feature across homeserver : https://github.com/matrix-org/synapse/pull/12310
Tests were conducted, we have found out that the `action_for_event_by_user` is consuming a lot of processing and not necessary for the user discovery logic : as a consequence, user discovery is not able to work for big homeserver. 
This change will allow the activation of the user discovery on larger rooms and finalise the work performed in https://github.com/matrix-org/synapse/pull/12310

Also, for information, we already have discussed this task with @anoadragon453

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Signed-off-by: Maghen Calinghee <maghen.calinghee@beta.gouv.fr>

### CODE REVIEW

**Review by clokep — CHANGES_REQUESTED** [review]
@mcalinghee Looks like this is missing a [newsfile](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog) and [sign-off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off).

Additionally it would be good to explain the rationale of *why* this is a reasonable thing to do.

**Comment by mcalinghee** [comment]
> @mcalinghee Looks like this is missing a [newsfile](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog) and [sign-off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off).
> 
> Additionally it would be good to explain the rationale of _why_ this is a reasonable thing to do.

Thank you for your comment and apologises to reply this only now.

I have performed the following actions :
- add the changelog as suggested
- add into the description of this PR the reason why of this proposed change
- performed the sign-off in the description of this PR

**Comment by clokep** [comment]
Thanks! I've put this in our generic review queue since I didn't really look at the code. 😄

**Review by reivilibre — APPROVED** [review]

**Comment by reivilibre** [comment]
Seems reasonable to me — thank you

**Pull request merged**
