### PR TITLE
Add more logging to debug slow startup

### PR DESCRIPTION
**Pull request by richvdh**
I'm hoping this will provide some pointers for debugging
https://github.com/matrix-org/synapse/issues/7968.

### CODE REVIEW

**Review by babolivier — APPROVED** [review]
lgtm, although I'm a bit worried that these lines would also get eaten up on matrix.org if there's an issue because we use a `MemoryLogger`

**Comment by richvdh** [comment]
well they will come out *eventually*, even with a MemoryLogger.

**Comment by babolivier** [comment]
Well yes but if it's an issue with a startup being so slow we need to abort it then it doesn't help.
Anyway, it looks like a good thing to have around either way :+1:

**Comment by richvdh** [comment]
I'm mostly tying to focus on #7968 here, where startup is slow even when we aren't having to run migrations. What we do about logging during schema migration is another problem...

**Pull request merged**
