### PR TITLE
Add time-based account expiration

### PR DESCRIPTION
**Pull request by babolivier**

### CODE REVIEW

**Comment by babolivier** [comment]
Hmm, opened the PR too quickly, meant to do so against develop. Closing and reopening.

**Comment by aaronraimist** [comment]
You know you can just change the base branch of an existing PR right?

**Comment by babolivier** [comment]
Errrr I didn't until @erikjohnston told me a few mins ago. TIL.

**Comment by jryans** [comment]
We have avoided this problem on Riot Web and Mobile by setting `develop` as the default branch for the repo on GH. Might be worth considering for Synapse if people get bitten by this confusion (esp. contributors).

**Comment by babolivier** [comment]
That might be an interesting idea, need to discuss it with the rest of the gang.

**Pull request closed without merging**
