### PR TITLE
Remove nuke-room-from-db.sh script

### PR DESCRIPTION
**Pull request by richvdh**
The problem with this script is that it is largely untested, entirely
unmaintained, and running it is likely to make your synapse blow up in
exciting ways.

For example, it leaves a bunch of tables with dead values in it, like
event_to_state_groups.

Having it here sends a message that it is a supported part of
synapse, which is absolutely not the case.

### CODE REVIEW

**Comment by jcgruenhage** [comment]
I probably would not have run this in the past, if I had known how unsupported it is. On the other hand, in the cases when I used it, it got my synapse back up and running after rooms got messed up somehow.

**Comment by rubo77** [comment]
If i look at the database structure: https://github.com/matrix-org/synapse/issues/934

I think it is easy: 

1. delete all entries in `event_to_state_groups` that match `entries.entry_id` with the key `event_to_state_groups.entry_id`
2. delete entries in `event_to_state_groups`

**Comment by rubo77** [comment]
I will :)

I think it  is much easyer and also deletes orphaned entries like this:

    DELETE FROM event_to_state_groups WHERE event_id NOT IN (SELECT event_id FROM events)

am I right?

@richvdh what other tables have orphaned entries after using the old nuke script?

**Comment by rubo77** [comment]
A more secure way to clear event_to_state_groups will be these commands:

```
-- check how many rows in event_to_state_groups

SELECT count(*) from event_to_state_groups;

-- create temporary TABLE event_to_state_groups_to_delete with event_ids that are missing in events TABLE

BEGIN;
SET enable_seqscan=off;
SELECT s.event_id INTO event_to_state_groups_to_delete FROM event_to_state_groups AS s 
LEFT JOIN events
ON s.event_id = events.event_id
WHERE events.event_id IS NULL;
COMMIT;

-- check how many rows will be deleted

SELECT count(*) from event_to_state_groups_to_delete;
```
-- shut synapse down here
```
DELETE FROM event_to_state_groups WHERE event_id IN (SELECT event_id FROM event_to_state_groups_to_delete);
```
-- start it up again
```
-- delete temporary TABLE event_to_state_groups_to_delete;

DROP TABLE event_to_state_groups_to_delete;
```

**Comment by karl007** [comment]
For everyone who search for a secure solution to delete a room (or something nearby), I create a php script as replacement for the `nuke-room-from-db` script, but use the API to kick all users and then let the garbage collector remove the empty room instead of deleting membership in the DB (and maybe miss something or screw up the DB): https://gist.github.com/rgpublic/0b7c44afafae71a8cc44732a5c217936

```bash
php riot_delete_room.php https://matrix.org "MDA...kYK" "#alias:domain.de"
```
The script only shows all members and the stop and ask if the members should kick. Then ask for a reason and a possible userId which should not kicked.

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_room.md

**Comment by rubo77** [comment]
The purge api seems to be  only able to remove **empty rooms**.

The old nuke script was meant to repair unaccessible rooms, or rooms that contain errors. would the php script be able to remove those rooms too?

I would love to have a real new nuke-script (if the synapse api doesn't work any more for example to remove an old broken room with some foreign-key entries missing in my database that always sais, there is an unread message, but there isn't and where I cannot post or do anything inside any more)

**Comment by worldowner** [comment]
PHP script posted above won't delete private rooms if admin is not joined to them. What would be needed is an admin api that allows server admin to kick any user from any room regardless of membership. Then purge_room api could be used.

**Comment by rubo77** [comment]
/_synapse/admin/v1/purge_room can only purge ruums, that have no users in it, does this mean no users **from your homeserver** or no users **at all**?

It would be helpful to add an option to purge it also, if there are still users in it that didn't log in for some years

**Comment by worldowner** [comment]
purge_room will delete data if no local user (any user having account on homeserver that you call purge_api on) is a member of a room being purged.

It will delete data from your homeserver even if users of remote homeserver are still in this room. Data will obviously still persist on remote homeservers.

**Comment by rubo77** [comment]
So this will be a problem, if there is at least one user from your HS (that might not be active any more or even only logged in a few years ago and then forgot his password).

**Pull request merged**
