### PR TITLE
Remove outdated worker bash scripts from contrib

### PR DESCRIPTION
**Pull request by villepeh**
### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [X] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [X] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [X] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Remove outdated worker bash scripts. Some settings like `worker_replication_host` no longer exists.

Signed-off-by: Ville Petteri Huh.

### CODE REVIEW

**Comment by clokep** [comment]
Would it make more sense to update the scripts instead of removing them?

**Comment by villepeh** [comment]
True, that makes sense if people find these scripts useful. I haven't been tinkering with workers for a while but once I do I can try to update the scripts. This PR can be closed if you decide to keep the scripts for now :)

**Review by clokep — CHANGES_REQUESTED** [review]
I think we'd rather update them then remove them completely.

**Comment by clokep** [comment]
Closing this per the reporter's comment -- if you want to reopen it, just shout.

**Pull request closed without merging**
