### PR TITLE
Fix Synapse hang during startup.

### PR DESCRIPTION
**Pull request by chrismoos**
Fixes https://github.com/matrix-org/synapse/issues/5866

### CODE REVIEW

**Comment by richvdh** [comment]
@erikjohnston I think you made this change. WDYT?

**Comment by richvdh** [comment]
I'm guessing the problem is that the dns lookups don't run until the reactor is properly 'started' so we can't do the acme request before that?

**Comment by erikjohnston** [comment]
Hmm, that's somewhat annoying. This was introduced in https://github.com/matrix-org/synapse/commit/80cfad233efc6b03c75ab5496db7079466eeb894, basically the idea was that we wouldn't consider ourselves "up" until all the setup code had run (so that e.g. systemd would do the right thing if synapse fails to start vs dies after start). We could shuffle things around and basically implement the "before start" stuff ourselves, but I was hoping that I could just reuse the twisted builtin stuff for this.

I'd be interested to know if this is expected behaviour (@hawkowl?)

Broadly: if this is breaking things then its fine for this PR to land and we can try to figure out how to fix the functionality separately.

**Comment by richvdh** [comment]
Thanks for this. I've cherry-picked it into a branch based on the current release, so it will be in v1.3.1.

**Pull request closed without merging**
