### PR TITLE
Update sync method to leave out unneeded bytes

### PR DESCRIPTION
**Pull request by ShadowJonathan**
(And fix some tests to stop assuming unilateral presence of sync keys)

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

(Partially) addresses #6579 (`room.join` is not optimized)

**Note: This PR is *potentially breaking*, it still adheres to the [spec](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-sync), but some clients or libraries could have (up to this point) fully assumed that all keys are present in the `/sync` object.**

`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

### CODE REVIEW

**Comment by ShadowJonathan** [comment]
Looks like the tests are blocked because sytest assumes some keys in `/sync` will be present...

**Comment by clokep** [comment]
@ShadowJonathan Curious if you plan to keep working on this? A PR could be made to modify sytest to avoid the unnecessary keys.

**Comment by ShadowJonathan** [comment]
@clokep this is still dependent on logic in sytest, which asserts that these keys are needed.

Does synapse still test with sytest?

**Comment by clokep** [comment]
> @clokep this is still blocked because of test logic in sytest, which asserts that these keys are needed.

Right -- but we can change sytest. sytest isn't immutable.

> Does synapse still test with sytest?

Yes.

**Comment by ShadowJonathan** [comment]
Well, then i cant progress on this.

And by the way, if that's so, then sytest is not compatible with the spec, then its incorrect to assert those keys should be there.

The spec says those keys are optional, sytest asserts otherwise, sytest is wrong, and thus should be changed, and thats why its blocked on that.

Further discussion in here, please; https://github.com/matrix-org/sytest/issues/957

And no, this PR is just blocked, if you wanna unblock it, resolve that issue first, please, dont just close it because its taking space.

**Comment by ShadowJonathan** [comment]
Due to no progress with this PR for a while, and because of some outstanding other projects i'd need to focus on, im closing this PR for the time being.

**Pull request closed without merging**
