### PR TITLE
 Add metrics to the threadpools

### PR DESCRIPTION
**Pull request by erikjohnston**
Based on #11177

### CODE REVIEW

**Comment by squahtx** [comment]
> Can we include the threadpool for database access too? It's `_db_pool.threadpool` in `DatabasePool`

Bump, in case this got lost.

**Comment by erikjohnston** [comment]
> > Can we include the threadpool for database access too? It's `_db_pool.threadpool` in `DatabasePool`
> 
> Bump, in case this got lost.

Oh, boo, I mentally assumed giving the comment a thumbs up meant I had done it :facepalm:

**Review by squahtx — APPROVED** [review]
LGTM!

**Comment by HarHarLinks** [comment]
@erikjohnston does [/contrib/grafana/synapse.json](https://github.com/matrix-org/synapse/blob/develop/contrib/grafana/synapse.json) need updating to show these?

**Pull request merged**
